plugins {
    id "io.micronaut.build.internal.data-tck"
}

dependencies {
    implementation platform(mn.micronaut.core.bom)

    annotationProcessor mn.micronaut.inject.java
    annotationProcessor mnValidation.micronaut.validation.processor
    annotationProcessor projects.micronautDataProcessor

    implementation mnValidation.micronaut.validation
    implementation mn.micronaut.http.client
    implementation mn.micronaut.http.server.netty
    implementation projects.micronautDataModel
    implementation(mnRxjava3.rxjava3)
    implementation mn.reactor
    implementation mnTest.micronaut.test.spock
    implementation mnTest.micronaut.test.core
    implementation mn.jackson.databind
    implementation libs.groovy.dateutil
    implementation(libs.managed.javax.persistence.api)
    implementation(mnSql.jakarta.persistence.api)
    implementation(libs.jupiter.engine)
    implementation(mnTest.micronaut.test.junit5)
    implementation(libs.managed.jakarta.data.api)

    compileOnly projects.micronautDataJdbc
    compileOnly mn.micronaut.inject.groovy
}

tasks.withType(Javadoc).configureEach {
    exclude("io/micronaut/data/tck/tests/AbstractJakartaDataTest.java")
}
