plugins {
    id "io.micronaut.build.internal.data-tck"
}

dependencies {
    implementation platform(mn.micronaut.core.bom)

    annotationProcessor mn.micronaut.inject.java
    annotationProcessor mnValidation.micronaut.validation.processor
    annotationProcessor projects.micronautDataProcessor
    annotationProcessor projects.micronautDataJpaMetamodelProcessor

    api mnValidation.micronaut.validation
    api mn.micronaut.http.client
    implementation mn.micronaut.http.server.netty
    api projects.micronautDataModel
    api projects.micronautDataTx
    api(mnRxjava3.rxjava3)
    api mn.reactor
    api mnTest.micronaut.test.spock
    api mnTest.micronaut.test.core
    implementation mn.jackson.databind
    implementation libs.groovy.dateutil
    api(libs.managed.javax.persistence.api)
    api(mnSql.jakarta.persistence.api)
    api(libs.jupiter.api)
    implementation(libs.jupiter.engine)
    api(mnTest.micronaut.test.junit5)
    api(libs.managed.jakarta.data.api)

    compileOnly projects.micronautDataJdbc
    compileOnly mn.micronaut.inject.groovy
}

tasks.named("prepareJavadocAggregation").configure {
    dependsOn(tasks.named("compileJava"))
    getSources().from(layout.buildDirectory.dir("generated/sources/annotationProcessor/java/main"))
}
