The quickest way to get started is to create a new Micronaut application with https://micronaut.io/launch/[Micronaut Launch] and choose the `data-mongodb` or `data-mongodb-async`.


TIP: You can also find a great guides on building Micronaut Data MongoDB applications including sample code in a variety of languages in the Micronaut Guides: https://guides.micronaut.io/latest/micronaut-data-mongodb-synchronous.html[Access a MongoDB Database with Micronaut Data MongoDB] and https://guides.micronaut.io/latest/micronaut-data-mongodb-asynchronous.html[Access a MongoDB Database Asynchronously with Micronaut Data MongoDB and Reactive Streams]

Clicking on one of the links in the table below will take you to https://micronaut.io/launch/[Micronaut Launch] with the appropriate options already pre-configured with your selected language and build tool:


.Creating a MongoDB application with Micronaut Launch

[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*
|https://micronaut.io/launch?features=data-mongodb&lang=JAVA&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb&lang=JAVA&build=MAVEN[Open]


|*Kotlin*
|https://micronaut.io/launch?features=data-mongodb&lang=JAVA&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb&lang=JAVA&build=MAVEN[Open]

|*Groovy*
|https://micronaut.io/launch?features=data-mongodb&lang=GROOVY&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb&lang=GROOVY&build=MAVEN[Open]

|===

.Creating a reactive MongoDB application with Micronaut Launch

[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=JAVA&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=JAVA&build=MAVEN[Open]


|*Kotlin*
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=JAVA&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=JAVA&build=MAVEN[Open]

|*Groovy*
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=GROOVY&build=GRADLE[Open]
|https://micronaut.io/launch?features=data-mongodb-reactive&lang=GROOVY&build=MAVEN[Open]

|===

.Creating an application with the CLI
[source,bash]
----
# For Maven add: --build maven
$ mn create-app --lang java example --features data-mongodb
----

Or via `curl`:

.Creating an application with `curl`
[source,bash]
----
# For Maven add to the URL: &build=maven
$ curl https://launch.micronaut.io/demo.zip?lang=java&features=data-mongodb -o demo.zip && unzip demo.zip -d demo && cd demo
----

Pre-generated applications should have everything properly setup. You can follow the manual configuration instructions for proper understanding of the dependency setup.

To get started with Micronaut Data MongoDB add the following dependency to your annotation processor path:

dependency:io.micronaut.data:micronaut-data-document-processor[scope="annotationProcessor""]

NOTE: For Kotlin the dependency should be in the `kapt` scope and for Groovy it should be in `compileOnly` scope.

You should then configure a compile-scoped dependency on the `micronaut-data-mongodb` module:

dependency:io.micronaut.data:micronaut-data-mongodb[]

And include MongoDB Sync driver:

dependency:org.mongodb:mongodb-driver-sync[scope="runtime"]

Or reactive MongoDB driver:

dependency:org.mongodb:mongodb-driver-reactivestreams[scope="runtime"].

NOTE: It's not possible to use both drivers at the same time. If you have both drivers on the classpath you can use property `micronaut.data.mongodb.driver-type` and value: `sync` or `reactive` to select proper driver.

Next up you need to configure at least one data source. The following snippet from the application configuration file is an example of configuring the default MongoDB data source:

[configuration]
----
mongodb:
  uri: mongodb://username:password@localhost:27017/databaseName
----

To retrieve objects from the database you need to define a class annotated with ann:data.annotation.MappedEntity[]:

snippet::example.Book[project-base="doc-examples/mongo-example", source="main", tags="book"]

Followed by an interface that extends from api:data.repository.CrudRepository[]

snippet::example.BookRepository[project-base="doc-examples/mongo-example", source="main", tags="repository"]

<1> The interface is annotated with ann:data.annotation.MongoRepository[]
<2> The `CrudRepository` interface take 2 generic arguments, the entity type (in this case `Book`) and the ID type (in this case `ObjectId`)

You can now perform CRUD (Create, Read, Update, Delete) operations on the entity. The implementation of `example.BookRepository` is created at compilation time. To obtain a reference to it simply inject the bean:

snippet::example.BookRepositorySpec[project-base="doc-examples/mongo-example", tags="inject", indent="0"]

=== Saving an Instance (Create)

To save an instance use the `save` method of the `CrudRepository` interface:

snippet::example.BookRepositorySpec[project-base="doc-examples/mongo-example", tags="save", indent="0"]

=== Retrieving an Instance (Read)

To read a book back use `findById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/mongo-example", tags="read", indent="0"]

=== Updating an Instance (Update)

With Micronaut Data MongoDB, you must manually implement an `update` method since the MongoDB implementation doesn't include any dirty checking or persistence session notion. So you have to define explicit update methods for updates in your repository. For example:

snippet::example.BookRepository[project-base="doc-examples/mongo-example", source="main" tags="update", indent="0"]

Which can then be called like so:

snippet::example.BookRepositorySpec[project-base="doc-examples/mongo-example", tags="update", indent="0"]

=== Deleting an Instance (Delete)

To delete an instance use `deleteById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/mongo-example", tags="delete", indent="0"]

Congratulations you have implemented your first Micronaut Data MongoDB repository! Read on to find out more.

NOTE: Micronaut Data MongoDB supports creating collections by setting property `micronaut.data.mongodb.create-collections` to `true`. MongoDB will create them automatically except for a few cases like transactional context, where collection needs to be already present.
