As seen in the <<mongoQuickStart, Quick Start>> MongoDB repositories in Micronaut Data are defined as interfaces that are annotated with the ann:data.mongodb.annotation.MongoRepository[].

In multiple servers scenario, the `serverName` annotation property can be used to specify the datasource configuration to use. By default, Micronaut Data will look for the default server.

For example:
[source,java]
----
@MongoRepository(serverName = "inventoryServer") // <1>
public interface PhoneRepository extends CrudRepository<Phone, Integer> {
    Optional<Phone> findByAssetId(@NotNull Integer assetId);
}
----
<1> @MongoRepository marking the interface to access MongoDB and pointing to the server configuration 'inventoryServer'

The entity to treat as the root entity for the purposes of querying is established either from the method signature or from the generic type parameter specified to the api:data.repository.GenericRepository[] interface.

If no root entity can be established then a compilation error will occur.

The same interfaces supported by the JPA implementation are supported by MongoDB.

Note that in addition to interfaces you can also define repositories as abstract classes:

snippet::example.AbstractBookRepository[project-base="doc-examples/mongo-example", source="main"]

NOTE: You can specify MongoDB's database name using the repository annotation: `@MongoRepository(databaseName = "mydb")` or in the connection url: `mongodb://username:password@localhost:27017/mydb`

Micronaut Data MongoDB introduces one special repository interface api:data.mongodb.repository.MongoQueryExecutor[] which accepts `Bson`/`List<Bson>` filter/pipeline/update parameters intended to be used in combination with MongoDB DSL API:

 - `com.mongodb.client.model.Filters`
 - `com.mongodb.client.model.Aggregates`
 - `com.mongodb.client.model.Updates`

Specific criteria supported by Micronaut Data MongoDB that allows to filter documents by checking occurrences in list or array of strings in given field can be achieved using `ArrayContains` or `CollectionContains` criteria. Here is an example of repository method declaration which will search people which interests field (list of strings) contains given value(s):

snippet::example.PersonRepository[project-base="doc-examples/mongo-example",source="main" tags="method_collection_contains",indent="0"]

Micronaut Data MongoDB supports array or list containment check for single or multiple values using `ArrayContains` or `CollectionContains` criteria.
