#
# Copyright 2017-2026 original authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
datasources.default.password=${JDBC_PASSWORD:}
datasources.default.url=${JDBC_URL:`jdbc:h2:~/devDb:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
datasources.default.username=${JDBC_USER:sa}
datasources.default.driver-class-name=${JDBC_DRIVER:org.h2.Driver}
jpa.default.entity-scan.enabled=true
jpa.default.enabled=true
jpa.default.compile-time-hibernate-proxies=true
jpa.default.properties.hibernate.hbm2ddl.auto=create
jpa.default.properties.hibernate.show_sql=true


