The quickest way to get started is to create a new Micronaut application with https://micronaut.io/launch/[Micronaut Launch] and choose the `data-jpa`, a database driver, pooling and a database migration framework features.

TIP: You can also find a great guide on building Micronaut Data JPA applications including sample code in a variety of languages in the Micronaut Guide: https://guides.micronaut.io/latest/micronaut-jpa-hibernate.html[Access a Database with Micronaut Data JPA]

Clicking on one of the links in the table below will take you to https://micronaut.io/launch/[Micronaut Launch] with the appropriate options already pre-configured with your selected language and build tool:

.Creating an application with Micronaut Launch

[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=JAVA&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=JAVA&build=MAVEN[Open]


|*Kotlin*

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=KOTLIN&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=KOTLIN&build=MAVEN[Open]

|*Groovy*

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=GROOVY&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jpa&features=flyway&features=mysql&features=jdbc-hikari&lang=GROOVY&build=MAVEN[Open]

|===

.Creating an application with the CLI
[source,bash]
----
# For Maven add: --build maven
$ mn create-app --lang java example --features data-jpa,flyway,mysql,jdbc-hikari
----

Or via `curl`:

.Creating an application with `curl`
[source,bash]
----
# For Maven add to the URL: &build=maven
$ curl https://launch.micronaut.io/demo.zip?lang=java&features=data-jpa,flyway,mysql,jdbc-hikari -o demo.zip && unzip demo.zip -d demo && cd demo
----

NOTE: When working with JDBC drivers it's required to add a JDBC Connection Pool Module (Hikari, Tomcat JDBC or DBCP ) from the Micronaut SQL project.

Use Micronaut SQL project documentation for more information regarding configuring https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#hibernate[Hibernate], https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#jdbc[JDBC and pooling].

You need to configure the data source in the application configuration file. For example for H2:

[configuration]
----
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
----

And add the following configuration in the application configuration file.

[configuration]
----
jpa:
  default:
    entity-scan:
        packages: 'example.domain'
----

Where `jpa.default.entity-scan.packages` references the root package where your `@Entity` classes are located.

And ensure the implementation is configured correctly.

You can then define an `@Entity`:

snippet::example.Book[project-base="doc-examples/hibernate-example", source="main"]

Followed by an interface that extends from api:data.repository.CrudRepository[]

snippet::example.BookRepository[project-base="doc-examples/hibernate-example", source="main", tags="repository"]

<1> The interface is annotated with ann:data.annotation.Repository[]
<2> The `CrudRepository` interface take 2 generic arguments, the entity type (in this case `Book`) and the ID type (in this case `Long`)

You can now perform CRUD (Create, Read, Update, Delete) operations on the entity. The implementation of `example.BookRepository` is created at compilation time. To obtain a reference to it simply inject the bean:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="inject", indent="0"]

=== Saving an Instance (Create)

To save an instance use the `save` method of the `CrudRepository` interface:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="save", indent="0"]

=== Retrieving an Instance (Read)

To read a book back use `findById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="read", indent="0"]

=== Updating an Instance (Update)

To update an instance use `save` again:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="update", indent="0"]

For partial entity updates, custom update method like this can be used:

snippet::example.BookRepository[project-base="doc-examples/hibernate-example", source="main" tags="update3", indent="0"]

In this example, in order for update to be propagated in the current session you can add `QueryHint` annotation to force session flush.

For Hibernate 6 instead of `javax.persistence.FlushModeType` need to use `jakarta.persistence.FlushModeType`.

=== Deleting an Instance (Delete)

To delete an instance use `deleteById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="delete", indent="0"]
