plugins {
	id "io.micronaut.build.internal.data-module"
    id 'antlr'
}

dependencies {
	api projects.micronautDataModel
	api(mnSql.jakarta.persistence.api)

    implementation libs.antlr.runtime

	compileOnly mn.micronaut.core.processor
    compileOnly libs.managed.jakarta.data.stateful
    compileOnly mn.micronaut.inject.java

	testAnnotationProcessor mn.micronaut.inject.java
	testAnnotationProcessor projects.micronautDataProcessor

	testImplementation mnReactor.micronaut.reactor
	testImplementation mn.micronaut.inject.groovy
    testImplementation mn.micronaut.inject.groovy.test
	testImplementation mn.micronaut.inject.java.test
	testImplementation(libs.managed.javax.persistence.api)
	testImplementation(mnSql.jakarta.transaction.api)
	testImplementation libs.spring.data.jpa
	testImplementation projects.micronautDataTck
	testImplementation projects.micronautDataTx
	testImplementation projects.micronautDataJdbc
    testImplementation libs.managed.jakarta.data.api

    antlr libs.antlr
}

tasks.named("generateGrammarSource") {
    outputDirectory = file("$outputDirectory/io/micronaut/data/jq")
    arguments += ["-package", "io.micronaut.data.jq"]
}
