This section documents breaking changes between Micronaut versions

== 4.0.0

=== Repositories validation

Default repository interfaces no longer have Jakarta Validation annotations to validate the entity and the ID.
To add the validation, annotate the repository's generic type argument with Jakarta Validation annotations:

[source,java]
----
@Repository
public interface BookRepository implements CrudRepository<@jakarta.validation.Valid Book, @jakarta.validation.constraints.NotNull Long> {
}
----

=== Repositories now return `List`

Find all return type changed to be `List` instead of `Iterable`

=== Hibernate transaction manager

The signature of the Hibernate transaction manager has changed to include `org.hibernate.Session` instead of a data source connection:

[source,java]
----
@Inject
public TransactionOperations<org.hibernate.Session> hibernateTransactionOperations;
----

=== Transaction manager

Micronaut 4 comes with a rewritten transaction propagation and management. It replaces the previous implementation forked form Spring Framework.
The new implementation has a newly added connection management, allowing to share a connection between multiple repositories and services without an open transaction. The new method supporting extracting the current transaction status `TransactionOperations#findTransactionStatus`. The `TransactionStatus` now includes information about the connection and the transaction definition.

=== Async and Reactive repositories

Async and reactive repositories are no longer throw `EmptyResultException` if the entity is not found.

== 5.0.0

=== Composite Id Naming Strategy

Before Micronaut Data 5.0.0 version, for classes using composite key using `@EmbeddedId` annotation
Micronaut Data would generate column names using field name annotated with `@EmbeddedId` annotation.

For such entity class:

snippet::example.Project[project-base="doc-examples/jdbc-example", source="main"]

and composite id class:

snippet::example.ProjectId[project-base="doc-examples/jdbc-example", source="main"]

create table before Micronaut Data 5.0.0 SQL script would look like this:

[source,sql]
----
CREATE TABLE `project` (`project_id_department_id` INT NOT NULL,`project_id_project_id` INT NOT NULL,`name` VARCHAR(255) NOT NULL, PRIMARY KEY(`project_id_department_id`,`project_id_project_id`));
----

which is not correct since `project_id_` prefix is not really needed. After 5.0.0, create table SQL script will look like this:

[source,sql]
----
CREATE TABLE `project` (`department_id` INT NOT NULL,`project_id` INT NOT NULL,`name` VARCHAR(255) NOT NULL, PRIMARY KEY(`department_id`,`project_id`));
----

If you have such tables in your system, after 5.0.0 you might need to annotate your composite id like this:

[source,java]
----
@EmbeddedId
@MappedProperty("project_id_")
private ProjectId projectId;
----

which will generate column names to be backward compatible.
