This section documents breaking changes between Micronaut Data versions:

== Micronaut Data 5.0.0

=== Deprecations

- Several members of the annotation `io.micronaut.data.intercept.annotation.DataMethod` deprecated previously have been removed.
`@DataMethod` is an internal annotation and the removed members are no longer used.

- The interface method `io.micronaut.data.model.PersistentProperty.getCapitilizedName()` deprecated previously has been removed.
It is replaced by `getCapitalizedName()`.

- The method `io.micronaut.data.model.query.builder.AbstractSqlLikeQueryBuilder.buildOrderBy(String, PersistentEntity, AnnotationMetadata, Sort)` deprecated previously has been removed.
Use `buildOrderBy(String, PersistentEntity, AnnotationMetadata, Sort, boolean)` instead.

- The following interface methods of `io.micronaut.data.model.runtime.StoredQuery` deprecated previously have been removed. They are no longer used.
** `boolean useNumericPlaceholders()`
** `Optional<Class<?>> getEntityIdentifierType()`
** `Class<?>[] getArgumentTypes()`
** `boolean isSingleResult()`
- As a consequence of the `StoredQuery` method removals, the following types that were overriding these methods have been changed to remove their implementations:
** Internal class `io.micronaut.data.runtime.query.internal.BasicStoredQuery`
** Internal class `io.micronaut.data.runtime.query.internal.DefaultStoredQuery`
** Interface `io.micronaut.data.runtime.query.internal.DelegateStoredQuery`
** Anonymous inner class of `io.micronaut.data.runtime.query.DefaultStoredQueryResolver`

- The following classes, deprecated previously have been removed. They are no longer used.
** `io.micronaut.data.processor.visitors.finders.AbstractPatternMethodMatcher`
** `io.micronaut.data.runtime.mapper.sql.SqlDTOMapper`

- TODO: document `io.micronaut.transaction.support.AbstractDataSourceTransactionManagerCondition.transactionManagerProperty(ConditionContext, String)` deprecation and removal.

== Micronaut Data 4.0.0

=== Repositories validation

Default repository interfaces no longer have Jakarta Validation annotations to validate the entity and the ID.
To add the validation, annotate the repository's generic type argument with Jakarta Validation annotations:

[source,java]
----
@Repository
public interface BookRepository implements CrudRepository<@jakarta.validation.Valid Book, @jakarta.validation.constraints.NotNull Long> {
}
----

=== Repositories now return `List`

Find all return type changed to be `List` instead of `Iterable`

=== Hibernate transaction manager

The signature of the Hibernate transaction manager has changed to include `org.hibernate.Session` instead of a data source connection:

[source,java]
----
@Inject
public TransactionOperations<org.hibernate.Session> hibernateTransactionOperations;
----

=== Transaction manager

Micronaut 4 comes with a rewritten transaction propagation and management. It replaces the previous implementation forked form Spring Framework.
The new implementation has a newly added connection management, allowing to share a connection between multiple repositories and services without an open transaction. The new method supporting extracting the current transaction status `TransactionOperations#findTransactionStatus`. The `TransactionStatus` now includes information about the connection and the transaction definition.

=== Async and Reactive repositories

Async and reactive repositories are no longer throw `EmptyResultException` if the entity is not found.


