Since Micronaut Data is a build time tool, it will not work correctly unless your build is configured correctly.

There are two important aspects to Micronaut Data:

1. The build time annotation processors
2. The runtime APIs

The build time processor is added by adding the `micronaut-data-processor` module to your annotation processor configuration in either Gradle or Maven:

dependency:io.micronaut.data:micronaut-data-processor[scope="annotationProcessor"]

For document databases like <<mongo, MongoDB>> instead of dependency above you need to use:

dependency:io.micronaut.data:micronaut-data-document-processor[scope="annotationProcessor"]

You can use Micronaut Launch to create a pre-configured project:

[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*

|https://micronaut.io/launch?features=data-jdbc&lang=JAVA&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jdbc&lang=JAVA&build=MAVEN[Open]


|*Kotlin*

|https://micronaut.io/launch?features=data-jdbc&lang=KOTLIN&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jdbc&lang=KOTLIN&build=MAVEN[Open]

|*Groovy*

|https://micronaut.io/launch?features=data-jdbc&lang=GROOVY&build=GRADLE[Open]

|https://micronaut.io/launch?features=data-jdbc&lang=GROOVY&build=MAVEN[Open]

|===

==== Micronaut Data and Lombok

If you intend to use Lombok with Micronaut Data then you must place the Lombok annotation processor *before* the Micronaut processors in your build configuration since Micronaut needs to see the mutations to the AST that Lombok applies.

WARNING: Lombok plugins like the Gradle plugin `io.franzbecker.gradle-lombok` are not supported as they place the annotation processors in an incorrect order.
