Hibernate Reactive brings reactive to the traditional JPA.

By using Hibernate Reactive in combination with Micronaut Data you can use the same features as repositories, JPA criteria etc. but in a reactive way.

For more information about Hibernate Reactive refer to https://hibernate.org/reactive/documentation/[the official documentation].

Include Hibernate reactive Micronaut Data support:

dependency:io.micronaut.data:micronaut-data-hibernate-reactive[]

NOTE: Hibernate Reactive requires Java 11 and Hibernate 5

The configuration differs from the ordinary <<hibernateQuickStart, Hibernate quick start>> since Hibernate Reactive does not use traditional JDBC drivers but instead custom drivers provided by the https://vertx.io/docs/#databases[Vertx project]. You  need to select an appropriate driver for your database:

For MySQL:

dependency:vertx-mysql-client[groupId="io.vertx"]

For Postgres:

dependency:vertx-pg-client[groupId="io.vertx"]

For Microsoft SQLServer:

dependency:vertx-mssql-client[groupId="io.vertx"]

For Oracle:

dependency:vertx-oracle-client[groupId="io.vertx"]

And configure it based on https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#hibernate[Micronaut SQL Hibernate Reactive support].

[configuration]
----
include::doc-examples/hibernate-reactive-example-java/src/main/resources/application.yml[]
----

Hibernate reactive is non-blocking that repository interfaces and classes you define extend one of the reactive repositories:

.Builtin Reactive Repository Interfaces
[cols=2*]
|===
|*Interface*
|*Description*

|api:data.repository.reactive.ReactiveStreamsCrudRepository[]
|Extends api:data.repository.GenericRepository[] and adds CRUD methods that return rs:Publisher[]

|api:data.repository.reactive.ReactorCrudRepository[]
|Extends api:data.repository.ReactiveStreamsCrudRepository[] and is using Reactor return types

|api:data.repository.reactive.RxJavaCrudRepository[]
|Extends api:data.repository.GenericRepository[] and adds CRUD methods that return RxJava 2 types

|api:data.repository.kotlin.CoroutineCrudRepository[]
|Extends api:data.repository.GenericRepository[] and is using Kotlin coroutines for reactive CRUD operations

|api:data.repository.jpa.reactive.ReactiveStreamsJpaSpecificationExecutor[]
|Reactive JPA Criteria executor

|api:data.repository.jpa.reactive.ReactorJpaSpecificationExecutor[]
|Reactive JPA Criteria executor that exposes methods using Reactor `Flux`/`Mono` classes
|===

The following is an example Hibernate Reactive repository:

snippet::example.BookRepository[project-base="doc-examples/hibernate-reactive-example", source="main", tags="repository"]

<1> The interface is annotated with ann:data.annotation.Repository[]
<2> The `ReactorCrudRepository` interface take 2 generic arguments, the entity type (in this case `Book`) and the ID type (in this case `Long`)


=== Saving an Instance (Create)

To save an instance use the `save` method of the `ReactorCrudRepository` interface:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-reactive-example", tags="save", indent="0"]

=== Retrieving an Instance (Read)

To read a book back use `findById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-reactive-example", tags="read", indent="0"]

=== Updating an Instance (Update)

To update an instance we use a custom method to do an update in a transaction:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-reactive-example", tags="update", indent="0"]

=== Deleting an Instance (Delete)

To delete an instance use `deleteById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-reactive-example", tags="delete", indent="0"]

NOTE: The examples are using `block` to retrieve the result, in your application you should never block the reactive repository as it can lead to performance problems, and it might not be supported by the backing implementation.



