Micronaut Data features general Spring support that is provided through the `micronaut-data-spring` dependency:

dependency:io.micronaut.data:micronaut-data-spring[version="{version}"]

In addition to this dependency you will need either `spring-orm` (for Hibernate) or `spring-jdbc` (for JDBC) on your classpath to enable support for Spring-based transaction management:

dependency:org.springframework:spring-orm[version="5.2.0.RELEASE"]

You can then compile existing Spring Data repository interfaces and use Spring annotations such as `org.springframework.transaction.annotation.Transactional` in your application.

You can extend from existing Spring Data interfaces such as `CrudRepository`, `PagingAndSortingRepository` and so on.

The following Spring Data types are also supported:

* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html[Pageable]
* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Sort.html[Sort]
* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html[Page]
* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/PageRequest.html[PageRequest]
* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html[CrudRepository]
* https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/PagingAndSortingRepository.html[PagingAndSortingRepository]

=== Spring Data JPA Specification Support

To obtain additional support for https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#specifications[Spring Data JPA Specifications] when using Hibernate and JPA you should add the following dependency to your classpath:

dependency:io.micronaut.data:micronaut-data-spring-jpa[version="{version}"]

You can then implement the `JpaSpecificationExecutor` (the generic argument to the interface should be a domain class) interface as per the https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#specifications[Spring Data JPA documentation].
