introduction:
  title: Introduction
  releaseHistory: Release History
quickStart:
  title: Quick Start
buildConfig:
  title: Build Configuration
repositories:
  title: Repository Interfaces
querying:
  title: Writing Queries
  criteria: Query Criteria
  pagination: Pagination
  ordering: Ordering
  projections: Query Projections
  dto: DTO Projections
  joinQueries: Join Queries
  explicitQueries: Explicit Queries
  whereAnnotation: Modifying Queries with @Where
  nativeQueries: Native Queries
  async: Asynchronous Queries
  reactive: Reactive Queries
dataUpdates:
  title: Updating Data
  transactions:
    title: Transactions
    programmaticTransactions: Programmatic Transactions
    transactionalEvents: Transactional Events
  batchUpdates: Batch Updates
  batchDeletes: Batch Deletes
  timestamps: Entity Timestamps
  entityEvents: Entity Events
howItWorks:
  title: How Micronaut Data Works
sql:
  title: Micronaut Data with SQL
  jdbc:
    title: Micronaut Data JDBC
    jdbcQuickStart: JDBC Quick Start
    jdbcConfiguration: JDBC Configuration
    jdbcRepositories:
      title: JDBC Repositories
      sqlInserts: Inserts and Updates
      pessimisticLocking: Pessimistic Locking
    sqlMapping:
      title: Mapping Entities
      sqlAnnotations: SQL Annotations
      sqlIdGenerator: ID Generation
      sqlCompositeId: Composite Primary Keys
      sqlConstructorArguments: Constructor Arguments
      sqlNaming: SQL Naming Strategies
      sqlAssociations: Association Fetching
      columnTransformer: Using @ColumnTransformer
      sqlJsonType: JSON Column Support
      javaRecords: Support for Java 14+ Records
    jdbcJoinQueries: JDBC Join Queries
    jdbcDataTypes: JDBC Data Types
    jdbcNativeQueries: Explicit JDBC Queries
graal:
  title: Going Native with GraalVM
spring:
  title: Spring Data Support


