introduction:
  title: Introduction
  whatsNew: What's New?
  releaseHistory: Release History
buildConfig:
  title: Build Configuration
shared:
  title: Shared Concepts
  repositories:
    title: Repository Interfaces
  querying:
    title: Writing Queries
    criteria: Query Criteria
    pagination: Pagination
    ordering: Ordering
    projections: Query Projections
    dto: DTO Projections
    explicitQueries: Explicit Queries
    whereAnnotation: Modifying Queries with @Where
    async: Asynchronous Queries
    reactive: Reactive Queries
  dataUpdates:
    title: Accessing data
    inserts: Inserting
    updates: Updating
    deletes: Deleting
    timestamps: Entity Timestamps
    entityEvents: Entity Events
  transactions:
    title: Transactions
    programmaticTransactions: Programmatic Transactions
    transactionalEvents: Transactional Events
  kotlinCriteria: Kotlin Criteria API extensions
  multitenancy: Multi-tenancy

hibernate:
  title: Micronaut Data JPA Hibernate
  hibernateJpaAnnotations: JPA Annotations
  hibernateQuickStart:
    title: Quick Start
  hibernateLogging: Logging SQL with Micronaut Data JPA Hibernate
  hibernateJoinQueries: Join queries
  hibernateExplicitQueries: Explicit queries
  hibernateNativeQueries: Native queries
  hibernateSpecifications: JPA specifications
hibernateReactive: Micronaut Data Hibernate Reactive
dbc:
  title: Micronaut Data JDBC and R2DBC
  jdbc:
    title: JDBC
    jdbcQuickStart: Quick Start
    jdbcConfiguration: Configuration
  r2dbc:
    title: R2DBC
    r2dbcQuickStart: Quick Start
    r2dbcConfiguration: Configuration
    r2querying: Reactive repositories
    r2transactionManagement: Transactions
    r2entityEvents: Reactive Entity Events
  dbcRepositories:
    title: Repositories
    sqlInserts: Accessing data
    optimisticLocking: Optimistic locking
    pessimisticLocking: Pessimistic Locking
  dbcCriteriaSpecifications:
    title: Repositories with Criteria API
    criteriaExecuteQuery: Querying
    criteriaExecuteUpdate: Updating
    criteriaExecuteDelete: Deleting
    otherRepositoryVariations: Other repository variations
    typeSafeJava: Type-Safe Java queries
  sqlMapping:
    title: Mapping Entities
    sqlAnnotations: SQL Annotations
    sqlExpandableQueries: Expandable queries
    sqlIdGenerator: ID Generation
    sqlCompositeId: Composite Primary Keys
    sqlConstructorArguments: Constructor Arguments
    sqlNaming: SQL Naming Strategies
    sqlAssociationMapping: Association Mapping
    sqlAssociationFetching: Association Fetching
    columnTransformer: Using @ColumnTransformer
    mappedPropertyAlias: Using @MappedProperty alias
    sqlJsonType: JSON Column Support
    javaRecords: Support for Java 16 Records
    kotlinData: Support for Kotlin immutable data classes
  dbcDataTypes: Data Types
  dbcAttributeConverter: Using Attribute Converter
  dbcJoinQueries: Join Queries
  dbcNativeQueries: Explicit Queries
mongo:
  title: Micronaut Data MongoDB
  mongoQuickStart: Quick Start
  mongoRepositories:
    title: Repositories
    mongoInsertsAndUpdates: Accessing data
    mongoCustomQueries: Custom Queries and Options
  mongoMapping:
    title: Mapping Entities
    mongoAnnotations: Mapping Annotations
    mongoIdGenerator: ID Generation
    mongoCompositeId: Composite Primary Keys
    mongoConstructorArguments: Constructor Arguments
    mongoNaming: Naming Strategies
    mongoAssociationMapping: Association Mapping
    mongoAssociationFetching: Association Fetching
  mongoJoinQueries: Join Queries
  mongoAttributeConverter: Using Attribute Converter
  mongoCriteriaSpecifications:
    title: Repositories with Criteria API
    mongoCriteriaExecuteQuery: Querying
    mongoCriteriaExecuteUpdate: Updating
    mongoCriteriaExecuteDelete: Deleting
    mongoOtherRepositoryVariations: Other repository variations
  mongoOptimisticLocking: Optimistic locking
azureCosmos:
  title: Micronaut Data Azure Cosmos
  azureCosmosQuickStart: Quick Start
  azureCosmosConfiguration: Configuration
  azureCosmosRepositories:
    title: Repositories
  azureCosmosCriteriaSpecifications:
    title: Repositories with Criteria API
    azureCosmosCriteriaExecuteQuery: Querying
    azureCosmosCriteriaExecuteUpdate: Updating
    azureCosmosCriteriaExecuteDelete: Deleting
  azureCosmosSpecifics: Azure Cosmos Specifics
  azureCosmosAttributeConverter: Using Attribute Converter
  azureCosmosOptimisticLocking: Optimistic locking
howItWorks:
  title: How Micronaut Data Works
graal:
  title: Going Native with GraalVM
spring:
  title: Spring Data Support


