introduction:
  title: Introduction
  whatsNew: What's New?
  releaseHistory: Release History
quickStart:
  title: Quick Start
buildConfig:
  title: Build Configuration
repositories:
  title: Repository Interfaces
querying:
  title: Writing Queries
  criteria: Query Criteria
  pagination: Pagination
  ordering: Ordering
  projections: Query Projections
  dto: DTO Projections
  joinQueries: Join Queries
  explicitQueries: Explicit Queries
  whereAnnotation: Modifying Queries with @Where
  nativeQueries: Native Queries
  async: Asynchronous Queries
  reactive: Reactive Queries
  specifications: JPA specifications
dataUpdates:
  title: Inserting and modifying data
  inserts: Inserting
  updates: Updating
  deletes: Deleting
  timestamps: Entity Timestamps
  entityEvents: Entity Events
  transactions:
    title: Transactions
    programmaticTransactions: Programmatic Transactions
    transactionalEvents: Transactional Events
howItWorks:
  title: How Micronaut Data Works
sql:
  title: Micronaut Data with SQL
  dbc:
    title: Micronaut Data JDBC / R2DBC
    dbcQuickStart:
      title: Quick Start
      jdbcQuickStart: JDBC
      r2dbcQuickStart: R2DBC
    dbcConfiguration: Configuration
    dbcRepositories:
      title: Repositories
      sqlInserts: Inserts and Updates
      optimisticLocking: Optimistic locking
      pessimisticLocking: Pessimistic Locking
    dbcCriteriaSpecifications:
      title: Respositories with Criteria API
      criteriaExecuteQuery: Querying
      criteriaExecuteUpdate: Updating
      criteriaExecuteDelete: Deleting
      otherRepositoryVariations: Other repository variations
    sqlMapping:
      title: Mapping Entities
      sqlAnnotations: SQL Annotations
      sqlExpandableQueries: Expandable queries
      sqlIdGenerator: ID Generation
      sqlCompositeId: Composite Primary Keys
      sqlConstructorArguments: Constructor Arguments
      sqlNaming: SQL Naming Strategies
      sqlAssociationMapping: Association Mapping
      sqlAssociationFetching: Association Fetching
      columnTransformer: Using @ColumnTransformer
      sqlJsonType: JSON Column Support
      javaRecords: Support for Java 16 Records
      kotlinData: Support for Kotlin immutable data classes
    dbcDataTypes: Data Types
    dbcAttributeConverter: Using Attribute Converter
    dbcJoinQueries: Join Queries
    dbcNativeQueries: Explicit Queries
    r2dbc:
      title: R2DBC specifics
      r2querying: Reactive repositories
      r2transactionManagement: Transactions
      r2entityEvents: Reactive Entity Events
mongo:
  title: Micronaut Data MongoDB
  mongoQuickStart: Quick Start
  mongoRepositories: Repositories
  mongoMapping:
    title: Mapping Entities
    mongoAnnotations: Mapping Annotations
    mongoIdGenerator: ID Generation
    mongoCompositeId: Composite Primary Keys
    mongoConstructorArguments: Constructor Arguments
    mongoNaming: Naming Strategies
    mongoAssociationMapping: Association Mapping
    mongoAssociationFetching: Association Fetching
  mongoJoinQueries: Join Queries
  mongoAttributeConverter: Using Attribute Converter
  mongoCriteriaSpecifications:
    title: Respositories with Criteria API
    mongoCriteriaExecuteQuery: Querying
    mongoCriteriaExecuteUpdate: Updating
    mongoCriteriaExecuteDelete: Deleting
    mongoOtherRepositoryVariations: Other repository variations
  mongoOptimisticLocking: Optimistic locking
graal:
  title: Going Native with GraalVM
spring:
  title: Spring Data Support


