introduction:
  title: Introduction
  releaseHistory: Release History
quickStart:
  title: Quick Start
buildConfig:
  title: Build Configuration
repositories:
  title: Repository Interfaces
querying:
  title: Writing Queries
  criteria: Query Criteria
  pagination: Pagination
  ordering: Ordering
  projections: Query Projections
  dto: DTO Projections
  joinQueries: Join Queries
  explicitQueries: Explicit Queries
  whereAnnotation: Modifying Queries with @Where
  nativeQueries: Native Queries
  async: Asynchronous Queries
  reactive: Reactive Queries
dataUpdates:
  title: Inserting and modifying data
  inserts: Inserting
  updates: Updating
  deletes: Deleting
  timestamps: Entity Timestamps
  entityEvents: Entity Events
  transactions:
    title: Transactions
    programmaticTransactions: Programmatic Transactions
    transactionalEvents: Transactional Events
howItWorks:
  title: How Micronaut Data Works
sql:
  title: Micronaut Data with SQL
  jdbc:
    title: Micronaut Data JDBC
    jdbcQuickStart: JDBC Quick Start
    jdbcConfiguration: JDBC Configuration
    jdbcRepositories:
      title: JDBC Repositories
      sqlInserts: Inserts and Updates
      optimisticLocking: Optimistic locking
      pessimisticLocking: Pessimistic Locking
    sqlMapping:
      title: Mapping Entities
      sqlAnnotations: SQL Annotations
      sqlIdGenerator: ID Generation
      sqlCompositeId: Composite Primary Keys
      sqlConstructorArguments: Constructor Arguments
      sqlNaming: SQL Naming Strategies
      sqlAssociationMapping: Association Mapping
      sqlAssociationFetching: Association Fetching
      columnTransformer: Using @ColumnTransformer
      sqlJsonType: JSON Column Support
      javaRecords: Support for Java 16 Records
      kotlinData: Support for Kotlin immutable data classes
    jdbcJoinQueries: JDBC Join Queries
    jdbcDataTypes: JDBC Data Types
    jdbcNativeQueries: Explicit JDBC Queries
  r2dbc:
    title: Micronaut Data R2DBC
    r2querying: Writing Queries
    r2crud: Performing CRUD Operations
    r2transactionManagement: Micronaut Data Transactions with R2DBC
    r2entityEvents: Reactive & Entity Events
graal:
  title: Going Native with GraalVM
spring:
  title: Spring Data Support


