plugins {
    id "io.micronaut.build.internal.data-benchmark"
    id "org.springframework.boot"
    id "io.spring.dependency-management"
}

springBoot {
    mainClass= 'example.Application'
}

dependencyManagement {
    imports {
        mavenBom libs.benchmark.spring.data.bom.get().toString()
        // Ensure Spring Boot's BOM wins to align Spring Framework/Data with Boot version
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
        exclude group: 'junit', module: 'junit'
    }
}
