plugins {
    id "io.micronaut.build.internal.data-base"
    id "io.micronaut.build.internal.module"
    id "java-library"
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly mnSerde.micronaut.serde.jackson
    testRuntimeOnly(mnTest.junit.platform.suite)
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.data:micronaut-data-model"
    }
}

def testModulesOptional = rootProject.tasks.findByName("testModules")
def testModules
if (testModulesOptional) {
    testModules = testModulesOptional
} else {
    testModules = rootProject.tasks.register("testModules").get()
}

testModules.mustRunAfter(tasks.named("test"))

test {
    useJUnitPlatform()
}
