plugins {
    id "io.micronaut.build.internal.parent"
    id "io.micronaut.build.internal.data-dependencies"
}

repositories {
    mavenCentral()
}

if (System.getenv("SONAR_TOKEN") != null) {
    sonarqube {
        properties {
            property "sonar.exclusions", "**/example/**"
        }
    }
}
