CREATE TABLE team
(team_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 points     INTEGER NOT NULL,
 CONSTRAINT team_pk PRIMARY KEY(team_id));

CREATE TABLE driver
(driver_id  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 points     INTEGER NOT NULL,
 team_id    INTEGER,
 CONSTRAINT driver_pk PRIMARY KEY(driver_id),
 CONSTRAINT driver_fk FOREIGN KEY(team_id) REFERENCES team(team_id));

CREATE TABLE race
(race_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 laps       INTEGER NOT NULL,
 race_date  DATE,
 podium     VARCHAR(255),
 CONSTRAINT race_pk PRIMARY KEY(race_id));

-- Mapping table, to bridge the tables DRIVER and RACE.
--
CREATE TABLE driver_race_map
(driver_race_map_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 race_id            INTEGER NOT NULL,
 driver_id          INTEGER NOT NULL,
 position           INTEGER,
 CONSTRAINT driver_race_map_uk  UNIQUE (race_id, driver_id),
 CONSTRAINT driver_race_map_pk  PRIMARY KEY(driver_race_map_id),
 CONSTRAINT driver_race_map_fk1 FOREIGN KEY(race_id)
     REFERENCES race(race_id),
 CONSTRAINT driver_race_map_fk2 FOREIGN KEY(driver_id)
     REFERENCES driver(driver_id));
-- Create foreign-key indexes
--
CREATE INDEX driver_fk_idx ON driver (team_id);
CREATE INDEX driver_race_map_fk1_idx ON driver_race_map (race_id);
CREATE INDEX driver_race_map_fk2_idx ON driver_race_map (driver_id);
