When using Micronaut Data with JDBC you can execute native SQL queries using the ann:data.annotation.Query[] annotation:

snippet::example.BookRepository[project-base="doc-examples/jdbc-example", source="main", tags="native", indent="0"]

The above example will execute the raw SQL against the database.

NOTE: For <<pagination, Pagination>> queries that return a api:data.model.Page[] you also need to specify a native `countQuery`.

=== Explicit Queries and Joins

When writing an explicit SQL query if you specify any joins within the query you may want the resulting data bound to the returned entity. Micronaut Data will not automatically do this, instead you need to specify the associated ann:data.annotation.Join[] annotation.

For example:

snippet::example.ProductRepository[project-base="doc-examples/jdbc-example", source="main",tags="native"]

In the above example the query uses an alias called `m_` to query the `manufacturer` table via an `INNER JOIN`. Since the returned `Product` entity features a `manufacturer` association it may be nice to materialize this object as well. The `alias` member of the ann:data.annotation.Join[] annotation is used to specify which alias to materialize the `Manufacturer` instance from.
