As mentioned in the <<jdbcQuickStart, Quick Start>> section, if you need to customize how entities map to the table and column names of the database you can use JPA annotations to do so or Predators own annotations in the `io.micronaut.data.annotation` package.

An important aspect of Predator JDBC is that regardless whether you use JPA annotations of Predator annotations the entity classes must be compiled with Predator.

This is because Predator pre-computes the persistence model (the relationships between entities, the class/property name to table/column name mappings) at compilation time, which is one of the reasons Predator JDBC can startup so fast.

An example of mapping with Predator annotations can be seen below:

.Predator Annotation Mapping Example
[source,java]
----
include::predator-tck/src/main/java/io/micronaut/data/tck/entities/Country.java[]
----

The following table summarizes the different annotations and what they enable. If you are familiar with and prefer the JPA annotations then feel free to skip to the next section:

.Predator Annotations
[cols=2*]
|===
|*Annotation*
|*Description*

|ann:data.annotation.AutoPopulated[]
|Meta annotation for a value that should be auto-populated by Predator (such as time stamps and UUIDs)

|ann:data.annotation.DateCreated[]
|Allows assigning a data created value (such as a `java.time.Instant`) prior to an insert

|ann:data.annotation.DateUpdated[]
|Allows assigning a last updated value (such as a `java.time.Instant`) prior to an insert

|ann:data.annotation.GeneratedValue[]
|Specifies that the property value is generated by the database and not included in inserts

|ann:data.annotation.Id[]
|Specifies the ID of an entity

|ann:data.annotation.MappedEntity[]
|Specifies the entity is mapped to the database

|ann:data.annotation.MappedProperty[]
|Used to customize the column name, definition and data type

|ann:data.annotation.Relation[]
|Used to specify a relationship (one-to-one, one-to-many etc.)

|ann:data.annotation.Transient[]
|Used to specify a property is transient

|===


=== Supported JPA Annotations

In the case of using JPA only a subset of annotations are supported including the following:

* `@Table`
* `@Id`
* `@Column`
* `@Transient`
* `@JoinTable`
* `@OneToMany`
* `@OneToOne`
* `@ManyToOne`
* `@ManyToMany`

Again Predator JDBC is not an ORM, but instead a simple data mapper so many of the concepts in JPA simply don't apply, however for users familiar with these annotations it is handy being able to use them.

=== ID Generation

The default ID generation expects the database to populate a value for the ID such as an `IDENTITY` column.

You can remove the `@GeneratedValue` annotation and in this case the expectation is that you will assign an ID before calling `save()`.

If you wish to uses sequences for the ID you should invoke the SQL that generates the sequence value and assign it prior to calling `save()`.

Automatically assigned UUIDs are also supported by adding a property annotated with `@Id` and `@AutoPopulated`.

=== Constructor Arguments

Predator JDBC also allows the definition of immutable objects using constructor arguments instead of getters/setters. If you define multiple constructors then the one used to create the object from the database should be annotated with `io.micronaut.core.annotation.Creator`.

For example:

snippet::example.Manufacturer[project-base="doc-examples/jdbc-example", source="main"]

As you can see from the example above, the `ID` of the object should however include a setter since this has to be assigned from the database generated value.

=== Naming Strategies

The default naming strategy when converting camel case class and property names to database tables and columns is to use underscore separated lower case. In other words `FooBar` becomes `foo_bar`.

If this is not satisfactory then you can customize this by setting the `namingStrategy` member of the ann:data.annotation.MappedEntity[] annotation on the entity:

.Predator Naming Strategy
[source,java]
----
include::predator-tck/src/main/java/io/micronaut/data/tck/entities/CountryRegion.java[tags="namingStrategy"]
    ...
}
----

Few important things to note. Since Predator pre-computes the table and column name mappings at compilation time the specified api:data.model.naming.NamingStrategy[] implementation must be on the annotation processor classpath (`annotationProcessor` scope for Java or `kapt` for Kotlin).

In addition if you don't want to repeat the above annotation definition on every entity it is handy to define a meta-annotation where the above annotation definition is applied to another annotation that you add to your class.
