package io.micronaut.data.jdbc.postgres

import io.micronaut.context.ApplicationContext
import io.micronaut.data.annotation.GeneratedValue
import io.micronaut.data.annotation.Id
import io.micronaut.data.annotation.MappedEntity
import io.micronaut.data.connection.jdbc.advice.DelegatingDataSource
import io.micronaut.data.jdbc.annotation.JdbcRepository
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.repository.CrudRepository
import io.micronaut.data.runtime.config.SchemaGenerate
import io.micronaut.inject.qualifiers.Qualifiers
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification

import javax.sql.DataSource
import java.time.LocalDateTime

/**
 * Test for https://github.com/micronaut-projects/micronaut-data/issues/2694 .
 *
 * A non-identity {@code @GeneratedValue} property (a column whose value is generated by the database,
 * e.g. via a {@code DEFAULT} expression) must be bound back onto the entity returned by {@code save()},
 * the same way the identity already is.
 */
class PostgresGeneratedValueSpec extends Specification implements PostgresTestPropertyProvider {

    @Override
    SchemaGenerate schemaGenerate() {
        return SchemaGenerate.NONE
    }

    @AutoCleanup
    @Shared
    ApplicationContext applicationContext = ApplicationContext.run(properties)

    DataSource dataSource = DelegatingDataSource.unwrapDataSource(applicationContext.getBean(DataSource.class, Qualifiers.byName("default")))

    void setup() {
        dataSource.connection.withCloseable {
            it.prepareStatement("CREATE TABLE gv_event(id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, created_at TIMESTAMP NOT NULL DEFAULT now(), property VARCHAR(255))").execute()
        }
    }

    void cleanup() {
        dataSource.connection.withCloseable {
            it.prepareStatement("DROP TABLE IF EXISTS gv_event").execute()
        }
    }

    void "test a non-identity generated value is bound back onto the entity returned by save()"() {
        given:
        def eventRepository = applicationContext.getBean(GvEventRepository)

        when:
        def saved = eventRepository.save(new GvEvent(property: "hello"))

        then:
        saved.id != null
        saved.createdAt != null
    }
}

@MappedEntity("gv_event")
class GvEvent {

    @Id
    @GeneratedValue
    Integer id

    @GeneratedValue
    LocalDateTime createdAt

    String property
}

@JdbcRepository(dialect = Dialect.POSTGRES)
interface GvEventRepository extends CrudRepository<GvEvent, Integer> {
}
