plugins {
    id "java-library"
    id "groovy"
}

dependencies {
//    annotationProcessor(mn.micronaut.inject.java)
//    annotationProcessor(mn.micronaut.graal)
//    annotationProcessor(libs.micronaut.docs)
//

//
//    api(projects.micronautDataRuntime)
//    api(projects.micronautDataTxJdbc)
//    api(projects.micronautDataConnectionJdbc)
//
//    implementation(mn.micronaut.json.core)
//    implementation(mnSql.micronaut.jdbc)
//
//    compileOnly(mnRxjava2.micronaut.rxjava2)
//    compileOnly(projects.micronautDataHibernateJpa)
//
//    testAnnotationProcessor(mn.micronaut.inject.java)

//    testAnnotationProcessor(mnValidation.micronaut.validation.processor)
//

    testImplementation(projects.micronautDataProcessor)
//    testImplementation(mnRxjava2.micronaut.rxjava2)
    testImplementation(mnReactor.micronaut.reactor)
//    testImplementation(libs.managed.javax.persistence.api)
//    testImplementation(mnSql.jakarta.persistence.api)
//    testImplementation(libs.groovy.sql)
//
//    testImplementation(mn.micronaut.http.client)
//
//    testCompileOnly(mn.micronaut.inject.groovy)
//
//    testImplementation(mnMultitenancy.micronaut.multitenancy)
//
//    testImplementation(mn.micronaut.http.netty)
//    testRuntimeOnly(mnSql.micronaut.jdbc.tomcat)
//    testRuntimeOnly(mnSql.sqlite.jdbc)
//
//    testImplementation(mnSerde.micronaut.serde.support)
//    testRuntimeOnly(libs.jupiter.engine)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(libs.managed.jakarta.data.api)

    testAnnotationProcessor(projects.micronautDataProcessor)
    testImplementation(projects.micronautDataJdbc)
    testImplementation(projects.micronautDataTck)

    // Validation
    testImplementation(mnValidation.micronaut.validation)
    testImplementation(mnValidation.micronaut.validation.processor)

    // Serialization
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
}
tasks.withType(Test).configureEach {
    jvmArgs '-Xmx1024m'
    systemProperty "oracle.jdbc.timezoneAsRegion", "false"
}
