As seen in the <<jdbcQuickStart, Quick Start>> JDBC / R2DBC repositories in Micronaut Data are defined as interfaces that are annotated with the ann:data.jdbc.annotation.JdbcRepository[] annotation, ann:data.r2dbc.annotation.R2dbcRepository[] accordingly.


In a multiple datasource scenario, the ann:io.micronaut.data.annotation.Repository[] and ann:io.micronaut.transaction.annotation.Transactional[] annotations can be used to specify the datasource configuration to use. By default, Micronaut Data will look for the default datasource.

For example:
[source,java]
----
@JdbcRepository(dialect = Dialect.ORACLE, dataSource = "inventoryDataSource") // <1>
@io.micronaut.transaction.annotation.Transactional("inventoryDataSource") // <2>
public interface PhoneRepository extends CrudRepository<Phone, Integer> {
    Optional<Phone> findByAssetId(@NotNull Integer assetId);
}
----
<1> @JdbcRepository with a specific dialect and data source configuration 'inventoryDataSource'
<2> @Transactional annotation, pointing to the data source configuration 'inventoryDataSource'


The entity to treat as the root entity for the purposes of querying is established either from the method signature or from the generic type parameter specified to the api:data.repository.GenericRepository[] interface.

If no root entity can be established then a compilation error will occur.

The same interfaces supported by the JPA implementation are supported by JDBC.

Note that because queries are computed at compilation time the `dialect` you use must be specified on the repository.

TIP: It is recommended you test against your target dialect. The https://www.testcontainers.org[Test Containers] project is a great solution for this. If you must test against another dialect (like H2) then you can define a subinterface that `@Replaces` the repository with a different dialect for the scope of testing.

Note that in addition to interfaces you can also define repositories as abstract classes:

snippet::example.AbstractBookRepository[project-base="doc-examples/jdbc-example", source="main"]

As you can see from the above example, using abstract classes can be useful as it allows you to combine custom code that performs your own SQL queries.

The example above uses the api:data.jdbc.runtime.JdbcOperations[] interface which simplifies executing JDBC queries within the context of transactions.

You can also integrate whichever other tool you wish to use to handle more complex queries, such as QueryDSL, JOOQ, Spring JdbcTemplate etc.

For example, to use link:https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html[Spring JdbcTemplate], add the following dependencies:

dependency:micronaut-data-jdbc[groupId="io.micronaut.data"]

dependency:micronaut-data-spring-jdbc[groupId="io.micronaut.data"]

The following code illustrates an example that integrates a `JdbcTemplate` instance as part of a api:data.jdbc.annotation.JdbcRepository[@JdbcRepository].

snippet::example.AbstractBookRepository[project-base="doc-examples/jdbc-spring-template-example",source="main",tags="clazz"]

<1> Inject the `java.sql.DataSource` configured by the application.
<2> Instantiate a `JdbcTemplate` object using the injected `DataSource`.
<3> Now the `JdbcTemplate` API can be used to implement repository methods.

In addition, the transaction manager for Spring JDBC needs to be set in application configuration.

[configuration]
----
datasources:
  default:
    transaction-manager: springJdbc
----

