/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.data.processor.visitors;

import io.micronaut.core.annotation.Internal;
import io.micronaut.data.annotation.Embeddable;
import io.micronaut.data.annotation.GenerateJakartaDataMetamodel;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.model.Association;
import io.micronaut.data.processor.model.SourcePersistentEntity;
import io.micronaut.data.processor.model.SourcePersistentProperty;
import io.micronaut.inject.ast.ClassElement;
import io.micronaut.inject.ast.PackageElement;
import io.micronaut.inject.ast.PrimitiveElement;
import io.micronaut.inject.processing.ProcessingException;
import io.micronaut.inject.visitor.PackageElementVisitor;
import io.micronaut.inject.visitor.TypeElementQuery;
import io.micronaut.inject.visitor.TypeElementVisitor;
import io.micronaut.inject.visitor.VisitorContext;
import io.micronaut.inject.writer.GeneratedFile;

import java.io.IOException;
import java.io.Writer;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.function.Function;

/**
 * The Jakarta Data static metamodel generator.
 *
 * @author Denis Stepanov
 * @since 5.0
 */
@Internal
public class GenerateJakartaDataMetamodelVisitor implements TypeElementVisitor<GenerateJakartaDataMetamodel, Object>, PackageElementVisitor<GenerateJakartaDataMetamodel> {

    @Override
    public void visitPackage(PackageElement element, VisitorContext context) throws ProcessingException {
        for (ClassElement classElement : context.getClassElements(element)) {
            visitClass(classElement, context);
        }
    }

    @Override
    public Set<String> getSupportedAnnotationNames() {
        return TypeElementVisitor.super.getSupportedAnnotationNames();
    }

    @Override
    public void visitClass(ClassElement element, VisitorContext context) {
        if (!element.hasAnnotation(MappedEntity.class) && !element.hasAnnotation(Embeddable.class)) {
            return;
        }

        SourcePersistentEntity sourcePersistentEntity = new SourcePersistentEntity(element, new Function<>() {
            @Override
            public SourcePersistentEntity apply(ClassElement classElement) {
                return new SourcePersistentEntity(classElement, this);
            }
        });

        String metamodelClassName = "_" + element.getSimpleName();
        String packageName = element.getPackageName();

        Optional<GeneratedFile> generatedFileOpt = context.visitGeneratedSourceFile(packageName, metamodelClassName, element);
        if (generatedFileOpt.isEmpty()) {
            return;
        }
        GeneratedFile generatedFile = generatedFileOpt.get();
        try (Writer writer = generatedFile.openWriter()) {

            writer.write("package " + packageName + ";\n\n");
            writer.write("import jakarta.data.metamodel.*;\n");
            writer.write("import jakarta.annotation.Generated;\n\n");
            writer.write("@Generated(\"Generated by Micronaut Data\")\n");
            writer.write("@StaticMetamodel(" + element.getSimpleName() + ".class)\n");
            writer.write("public class " + metamodelClassName + " {\n\n");

            // Add string constants for field names
            for (String name : sourcePersistentEntity.getPersistentPropertyNames()) {
                SourcePersistentProperty persistentProperty = sourcePersistentEntity.getPropertyByName(name);
                Objects.requireNonNull(persistentProperty);
                String fieldName = persistentProperty.getName().toUpperCase();
                writer.write("    public static final String " + fieldName + " = \"" + persistentProperty.getName() + "\";\n");
            }
            writer.write("\n");

            // Add attribute fields
            for (String name : sourcePersistentEntity.getPersistentPropertyNames()) {
                SourcePersistentProperty persistentProperty = sourcePersistentEntity.getPropertyByName(name);
                Objects.requireNonNull(persistentProperty);
                String fieldName = persistentProperty.getName();
                ClassElement propertyType = persistentProperty.getType();

                if (persistentProperty instanceof Association) {
                    writer.write("    public static final NavigableAttribute<" + element.getSimpleName() + ", " + propertyType.getName() + "> " + fieldName + " = NavigableAttribute.of(" + element.getSimpleName() + ".class, " + fieldName.toUpperCase() + ", " + propertyType.getName() + ".class);\n");
                    continue;
                }

                String attributeDeclaration = getAttributeDeclaration(element, propertyType);
                String initializer = getAttributeInitializer(element, propertyType, fieldName.toUpperCase());

                writer.write("    public static final " + attributeDeclaration + " " + fieldName + " = " + initializer + ";\n");
            }

            writer.write("\n}\n");
        } catch (IOException e) {
            context.fail("Failed to generate metamodel class: " + e.getMessage(), element);
        } catch (Exception e) {
            context.fail("Failed to access generated file writer: " + e.getMessage(), element);
        }
    }

    private String getAttributeDeclaration(ClassElement entityElement, ClassElement propertyType) {
        String entityName = entityElement.getSimpleName();
        if (propertyType.isArray()) {
            return  "BasicAttribute<" + entityName + ", " + toTypeString(propertyType) + ">";
        }
        String type = getBoxedType(propertyType);
        // Handle wrapper types and other basic types
        return switch (type) {
            case "java.lang.Byte", "java.lang.Short", "java.lang.Integer",
                 "java.lang.Long", "java.lang.Float", "java.lang.Double", "java.math.BigInteger",
                 "java.math.BigDecimal" -> "NumericAttribute<" + entityName + ", " + type + ">";
            case "java.time.LocalDate", "java.time.LocalDateTime",
                 "java.time.LocalTime", "java.time.Year", "java.time.Instant" -> "TemporalAttribute<" + entityName + ", " + type + ">";
            case "java.lang.String" -> "TextAttribute<" + entityName + ">";
            case "java.lang.Boolean", "java.util.UUID" -> "ComparableAttribute<" + entityName + ", " + type + ">";
            default -> {
                // For enum types
                if (propertyType.isEnum()) {
                    yield "ComparableAttribute<" + entityName + ", " + type + ">";
                }
                // For other types, use BasicAttribute
                yield "BasicAttribute<" + entityName + ", " + type + ">";
            }
        };
    }

    private String getBoxedType(ClassElement propertyType) {
        String type = propertyType.getName();
        if (propertyType.isPrimitive()) {
            if (propertyType.equals(PrimitiveElement.BOOLEAN)) {
                return Boolean.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.INT)) {
                return Integer.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.CHAR)) {
                return Character.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.LONG)) {
                return Long.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.FLOAT)) {
                return Float.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.DOUBLE)) {
                return Double.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.BYTE)) {
                return Byte.class.getName();
            }
            if (propertyType.equals(PrimitiveElement.SHORT)) {
                return Short.class.getName();
            }
        }
        return type;
    }

    private String toTypeString(ClassElement classElement) {
        if (classElement.isArray()) {
            return toTypeString(classElement.fromArray()) + "[]";
        }
        return classElement.getName();
    }

    private String getAttributeInitializer(ClassElement entityElement, ClassElement propertyType, String fieldNameConstant) {
        String entityName = entityElement.getSimpleName();
        String type = getBoxedType(propertyType);

        // Handle primitive types - all map to SortableAttribute with NumericAttribute.of
        if (propertyType.isArray()) {
            return "BasicAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", " + toTypeString(propertyType) + ".class)";
        }

        // Handle wrapper types and other basic types
        return switch (type) {
            case "java.lang.Boolean" ->
                "ComparableAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Boolean.class)";
            case "java.lang.Byte" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Byte.class)";
            case "java.lang.Short" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Short.class)";
            case "java.lang.Integer" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Integer.class)";
            case "java.lang.Long" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Long.class)";
            case "java.lang.Float" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Float.class)";
            case "java.lang.Double" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", Double.class)";
            case "java.lang.String" ->
                "TextAttribute.of(" + entityName + ".class, " + fieldNameConstant + ")";
            case "java.math.BigInteger" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.math.BigInteger.class)";
            case "java.math.BigDecimal" ->
                "NumericAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.math.BigDecimal.class)";
            case "java.time.LocalDate" ->
                "TemporalAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.time.LocalDate.class)";
            case "java.time.LocalDateTime" ->
                "TemporalAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.time.LocalDateTime.class)";
            case "java.time.LocalTime" ->
                "TemporalAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.time.LocalTime.class)";
            case "java.time.Year" ->
                "TemporalAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.time.Year.class)";
            case "java.time.Instant" ->
                "TemporalAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.time.Instant.class)";
            case "java.util.UUID" ->
                "ComparableAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", java.util.UUID.class)";
            default -> {
                // For enum types
                if (propertyType.isEnum()) {
                    yield "ComparableAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", " + type + ".class)";
                }
                // For other types, use BasicAttribute
                yield "BasicAttribute.of(" + entityName + ".class, " + fieldNameConstant + ", " + type + ".class)";
            }
        };
    }

    @Override
    public int getOrder() {
        return -100; // Run before repository element visitor
    }

    @Override
    public TypeElementQuery query() {
        return TypeElementQuery.onlyClass();
    }

    @Override
    public VisitorKind getVisitorKind() {
        return VisitorKind.ISOLATING;
    }
}
