micronaut:
  application:
    name: jdbc-sessionless-transaction-booking-java
  data:
    oracle:
      sessionless:
        http:
          enabled: true

datasources:
  default:
    driverClassName: oracle.jdbc.OracleDriver
    dialect: ORACLE
    url: jdbc:oracle:thin:@localhost:1521/freepdb1
    username: test
    password: test
