micronaut:
  application:
    name: micronautguide
  http:
    client:
      read-timeout: "10m"
---
datasources:
  default:
    url: "jdbc:oracle:thin:@127.0.0.1:1521/FREEPDB1"
    username: system
    password: test
    dialect: ORACLE
    driverClassName: oracle.jdbc.OracleDriver
    initialization-fail-timeout: -1 # Disable fail fast pool init
---
