CREATE TABLE team
(team_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 points     INTEGER NOT NULL,
 CONSTRAINT team_pk PRIMARY KEY(team_id));

CREATE TABLE driver
(driver_id  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 points     INTEGER NOT NULL,
 team_id    INTEGER,
 CONSTRAINT driver_pk PRIMARY KEY(driver_id),
 CONSTRAINT driver_fk FOREIGN KEY(team_id) REFERENCES team(team_id));

CREATE TABLE race
(race_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 name       VARCHAR2(255) NOT NULL UNIQUE,
 laps       INTEGER NOT NULL,
 race_date  DATE,
 podium     JSON,
 CONSTRAINT race_pk PRIMARY KEY(race_id));

-- Mapping table, to bridge the tables DRIVER and RACE.
--
CREATE TABLE driver_race_map
(driver_race_map_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 race_id            INTEGER NOT NULL,
 driver_id          INTEGER NOT NULL,
 position           INTEGER,
 CONSTRAINT driver_race_map_uk  UNIQUE (race_id, driver_id),
 CONSTRAINT driver_race_map_pk  PRIMARY KEY(driver_race_map_id),
 CONSTRAINT driver_race_map_fk1 FOREIGN KEY(race_id)
     REFERENCES race(race_id),
 CONSTRAINT driver_race_map_fk2 FOREIGN KEY(driver_id)
     REFERENCES driver(driver_id));

-- Views

CREATE JSON RELATIONAL DUALITY VIEW team_dv AS
SELECT JSON {'teamId' : t.team_id,
               'name'   : t.name,
               'points' : t.points,
               'driver' :
                 [ SELECT JSON {'driverId' : d.driver_id,
                                'name'     : d.name,
                                'points'   : d.points WITH NOCHECK}
                   FROM driver d WITH INSERT UPDATE
                                                 WHERE d.team_id = t.team_id ]}
                                             FROM team t WITH INSERT UPDATE DELETE;

CREATE JSON RELATIONAL DUALITY VIEW driver_dv AS
SELECT JSON {'driverId' : d.driver_id,
               'name'     : d.name,
               'points'   : d.points,
               'teamInfo' :
                 (SELECT JSON {'teamId' : t.team_id,
                               'name'   : t.name WITH NOCHECK}
                    FROM team t WITH NOINSERT NOUPDATE NODELETE
                    WHERE t.team_id = d.team_id),
               'race'     :
                 [ SELECT JSON {'driverRaceMapId' : drm.driver_race_map_id,
                                'raceInfo'        :
                                  (SELECT JSON {'raceId' : r.race_id,
                                                'name'   : r.name}
                                     FROM race r WITH NOINSERT NOUPDATE NODELETE
                                     WHERE r.race_id = drm.race_id),
                                'finalPosition'   : drm.position}
                   FROM driver_race_map drm WITH INSERT UPDATE NODELETE
                                                        WHERE drm.driver_id = d.driver_id ]}
                                                        FROM driver d WITH INSERT UPDATE DELETE;

CREATE JSON RELATIONAL DUALITY VIEW race_dv AS
SELECT JSON {'raceId' : r.race_id,
               'name'   : r.name,
               'laps'   : r.laps WITH NOUPDATE,
    'date'   : r.race_date,
    'podium' : r.podium WITH NOCHECK,
    'result' :
    [ SELECT JSON {'driverRaceMapId' : drm.driver_race_map_id,
                                'position'        : drm.position,
                                'driverInfo'      :
                                  (SELECT JSON {'driverId' : d.driver_id,
                                                'name'     : d.name}
                                     FROM driver d WITH NOINSERT UPDATE NODELETE
                                     WHERE d.driver_id = drm.driver_id)}
      FROM driver_race_map drm WITH INSERT UPDATE DELETE
                                           WHERE drm.race_id = r.race_id ]}
                                           FROM race r WITH INSERT UPDATE DELETE;
