import io.micronaut.testresources.buildtools.KnownModules

plugins {
    id "io.micronaut.build.internal.data-module"
    id 'io.micronaut.test-resources'
}

dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor mn.micronaut.graal
    annotationProcessor libs.micronaut.docs

    api projects.micronautDataRuntime
    api projects.micronautDataTxJdbc
    api projects.micronautDataConnectionJdbc

    implementation mn.micronaut.json.core
    compileOnly mnSerde.micronaut.serde.oracle.jdbc.json
    implementation mnSql.micronaut.jdbc

    implementation mn.jackson.annotations

    compileOnly(mnRxjava3.micronaut.rxjava3)
    compileOnly projects.micronautDataHibernateJpa
    compileOnly mnSql.ojdbc11
    compileOnly mnSql.postgresql
    compileOnly mnSql.mysql.connector.j
    compileOnly libs.managed.pg.vector

    testAnnotationProcessor mn.micronaut.inject.java
    testAnnotationProcessor projects.micronautDataProcessor
    testAnnotationProcessor mnValidation.micronaut.validation.processor

    testImplementation projects.micronautDataTck
    testImplementation libs.managed.pg.vector
    testImplementation projects.micronautDataProcessor
    testImplementation(mnRxjava3.micronaut.rxjava3)
    testImplementation mnReactor.micronaut.reactor
    testImplementation(libs.managed.javax.persistence.api)
    testImplementation(mnSql.jakarta.persistence.api)
    testImplementation libs.groovy.sql
    testImplementation mnValidation.micronaut.validation
    testImplementation mnValidation.micronaut.validation.processor
    testImplementation mn.micronaut.http.client

    testImplementation(mnTestResources.testcontainers.mysql)
    testImplementation(mnTestResources.testcontainers.mariadb)
    testImplementation(mnTestResources.testcontainers.postgres)
    testImplementation(mnTestResources.testcontainers.mssql)
    testImplementation(mnTestResources.testcontainers.oracle.xe)

    testCompileOnly mn.micronaut.inject.groovy
    testImplementation mnSql.ojdbc11


    testImplementation mnMultitenancy.micronaut.multitenancy

    testImplementation mn.micronaut.http.netty
    testRuntimeOnly mnSql.micronaut.jdbc.tomcat
    testRuntimeOnly mnSql.h2
    testRuntimeOnly mnSql.mariadb.java.client
    testRuntimeOnly mnSql.mysql.connector.j
    testRuntimeOnly mnSql.postgresql
    testRuntimeOnly mnSql.mssql.jdbc
    testRuntimeOnly mn.snakeyaml
    testRuntimeOnly libs.h2gis

    testResourcesService mnSql.mariadb.java.client
    testResourcesService mnSql.ojdbc11
    testResourcesService mnSql.mysql.connector.j
    testResourcesService mnSql.postgresql
    testResourcesService mnSql.mssql.jdbc

    testImplementation mnSerde.micronaut.serde.support
    testImplementation mnTestResources.micronaut.test.resources.extensions.junit.platform
    testRuntimeOnly(libs.jupiter.engine)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(libs.managed.jakarta.data.api)

    testRuntimeOnly mnSerde.micronaut.serde.oracle.jdbc.json
    testAnnotationProcessor mnSerde.micronaut.serde.processor
}

micronaut {
    version libs.versions.micronaut.platform.get()
    testResources {
        enabled = true
        inferClasspath = false
        additionalModules.add(KnownModules.JDBC_POSTGRESQL)
        additionalModules.add(KnownModules.JDBC_MYSQL)
        additionalModules.add(KnownModules.JDBC_MARIADB)
        additionalModules.add(KnownModules.JDBC_ORACLE_FREE)
        additionalModules.add(KnownModules.JDBC_ORACLE_XE)
        additionalModules.add(KnownModules.JDBC_MSSQL)
        clientTimeout = 300
        version = libs.versions.micronaut.testresources.get()
    }
}

tasks.withType(Test).configureEach {
    jvmArgs '-Xmx1024m'
    systemProperty "oracle.jdbc.timezoneAsRegion", "false"
}

micronautBuild {
    resolutionStrategy {
        componentSelection {
            all { selection ->
                if (selection.candidate.module == 'mssql-jdbc' && !selection.candidate.version.contains("jre8")) {
                    selection.reject("Not a JDK8 compatible MS SQL driver")
                }
            }
        }
    }
}
