CREATE TABLE "TBL_CONTACT"
(	"ID" NUMBER(*,0) NOT NULL ENABLE,
     "NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "AGE" INTEGER,
     CONSTRAINT "TBL_CONTACT_PK" PRIMARY KEY ("ID")
);

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW CONTACT_VIEW AS
SELECT JSON{'id': c.id,
            'name': c.name WITH UPDATE,
            'age': c.age
            } FROM TBL_CONTACT c WITH UPDATE INSERT DELETE;
