[versions]
micronaut = "5.1.9"
micronaut-platform = "5.0.5"
micronaut-docs = "3.0.0"
micronaut-gradle-plugin = "5.0.2"
micronaut-testresources = "4.0.0"

micronaut-azure = "6.1.0"
micronaut-reactor = "4.1.0"
micronaut-rxjava3 = "4.1.0"
micronaut-r2dbc = "7.1.0"
micronaut-sql = "7.1.0"
micronaut-serde = "3.1.0"
micronaut-spring = "6.1.0"
micronaut-test = "5.0.0"
micronaut-mongo = "6.1.0"
micronaut-kotlin = "5.1.0"
micronaut-multitenancy = "6.1.0"
micronaut-validation = "5.1.0"
micronaut-logging = "2.1.0"
micronaut-flyway = "8.1.0"
micronaut-coherence = "7.0.1"
micronaut-sourcegen = "2.1.0"
nitrite = "4.3.2"
jackson-datatype-jts = "2.21.0"

groovy = "5.0.7"

managed-javax-persistence = "2.2"
managed-jakarta-data = "1.1.0-M3"
managed-pg-vector = "0.1.6"

spring-data = "4.1.0"

# Lombok

lombok = "1.18.46"

# Testing and benchmarking

benchmark-spring-data = "2026.0.0"
jmh = "1.37"
h2gis = "2.2.5"

# Gradle plugins

ksp-gradle-plugin = "2.3.10"
kotlin-gradle-plugin = "2.3.21"
jmh-gradle-plugin = "0.7.3"
spring-boot-gradle-plugin = "4.1.0"
spring-dependency-management-gradle-plugin = "1.1.7"
shadow-gradle-plugin = "9.6.0"
errorprone-gradle-plugin = "5.1.0"
nullaway = "0.13.8"
error_prone_core = "2.50.0"
groovy_yaml = "5.0.7"

antlr = "4.13.2"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

micronaut-testresources-client = { module = 'io.micronaut.testresources:micronaut-test-resources-client', version.ref = "micronaut-testresources" }
micronaut-testresources-extensions-junit-platform = { module = 'io.micronaut.testresources:micronaut-test-resources-extensions-junit-platform', version.ref = "micronaut-testresources" }

# BOMs

micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-rxjava3 = { module = 'io.micronaut.rxjava3:micronaut-rxjava3-bom', version.ref = "micronaut-rxjava3" }
micronaut-kotlin = { module = 'io.micronaut.kotlin:micronaut-kotlin-bom', version.ref = "micronaut-kotlin" }
micronaut-multitenancy = { module = 'io.micronaut.multitenancy:micronaut-multitenancy-bom', version.ref = "micronaut-multitenancy" }
micronaut-testresources = { module = 'io.micronaut.testresources:micronaut-test-resources-bom', version.ref = "micronaut-testresources" }
micronaut-validation = { module = 'io.micronaut.validation:micronaut-validation-bom', version.ref = "micronaut-validation" }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
micronaut-mongo = { module = "io.micronaut.mongodb:micronaut-mongo-bom", version.ref = "micronaut-mongo" }
micronaut-spring = { module = "io.micronaut.spring:micronaut-spring-bom", version.ref = "micronaut-spring" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-r2dbc = { module = "io.micronaut.r2dbc:micronaut-r2dbc-bom", version.ref = "micronaut-r2dbc" }
micronaut-flyway = { module = "io.micronaut.flyway:micronaut-flyway-bom", version.ref = "micronaut-flyway" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-coherence = { module = "io.micronaut.coherence:micronaut-coherence-bom", version.ref = "micronaut-coherence" }
micronaut-sourcegen = { module = "io.micronaut.sourcegen:micronaut-sourcegen-bom", version.ref = "micronaut-sourcegen" }

micronaut-docs = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

managed-javax-persistence-api = { module = "javax.persistence:javax.persistence-api", version.ref = "managed-javax-persistence" }
managed-jakarta-data-api = { module = 'jakarta.data:jakarta.data-api', version.ref = "managed-jakarta-data" }
managed-jakarta-data-stateful = { module = 'jakarta.data:jakarta.data-stateful', version.ref = "managed-jakarta-data" }
managed-pg-vector = { module = 'com.pgvector:pgvector', version.ref = "managed-pg-vector"}
# JPA

spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "spring-data" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons", version.ref = "spring-data" }

# Lombok

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# AZURE COSMOS

micronaut-azure-cosmos = { module = "io.micronaut.azure:micronaut-azure-cosmos", version.ref = "micronaut-azure" }

# Nitrite
nitrite = { module = "org.dizitart:nitrite", version.ref = "nitrite" }
nitrite-mvstore-adapter = { module = "org.dizitart:nitrite-mvstore-adapter", version.ref = "nitrite" }
nitrite-jackson-mapper = { module = "org.dizitart:nitrite-jackson-mapper", version.ref = "nitrite" }
nitrite-rocksdb-adapter = { module = "org.dizitart:nitrite-rocksdb-adapter", version.ref = "nitrite" }
nitrite-spatial = { module = "org.dizitart:nitrite-spatial", version.ref = "nitrite" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-datatype-jts = { module = "com.graphhopper.external:jackson-datatype-jts", version.ref = "jackson-datatype-jts" }

# Antlr

antlr = { module = "org.antlr:antlr4", version.ref = "antlr"}
antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr"}

# Test

jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }
jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api' }
groovy-sql = { module = "org.apache.groovy:groovy-sql" }
groovy-dateutil = { module = "org.apache.groovy:groovy-dateutil", version.ref = "groovy" }

jakarta-data-tck = { module = 'jakarta.data:jakarta.data-tck', version.ref = "managed-jakarta-data" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine" }

nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
error-prone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "error_prone_core" }
groovy-yaml = { module = "org.apache.groovy:groovy-yaml", version.ref = "groovy_yaml" }

h2gis = { module = "org.orbisgis:h2gis", version.ref = "h2gis"}

# Benchmark

jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

benchmark-spring-data-bom = { module = "org.springframework.data:spring-data-bom", version.ref = "benchmark-spring-data" }

# TESTCONTAINERS

testcontainers-azure = { module = "org.testcontainers:testcontainers-azure" }

# PLUGINS

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
gradle-kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin-gradle-plugin" }
gradle-kotlin-noarg = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin-gradle-plugin" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp-gradle-plugin" }
gradle-jmh = { module = "me.champeau.jmh:jmh-gradle-plugin", version.ref = "jmh-gradle-plugin" }
gradle-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot-gradle-plugin" }
gradle-spring-dependencies = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependency-management-gradle-plugin" }
gradle-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow-gradle-plugin" }
gradle-errorprone = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-gradle-plugin"}
gradle-nullaway = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-gradle-plugin"}
