The default ID generation expects the database to populate a value for the ID such as an `IDENTITY` column.

You can remove the `@GeneratedValue` annotation and in this case the expectation is that you will assign an ID before calling `save()`.

If you wish to use sequences for the ID you should invoke the SQL that generates the sequence value and assign it prior to calling `save()`.

Automatically assigned UUIDs are also supported by adding a property annotated with `@Id` and `@AutoPopulated`.

If you want to sometimes provide the ID yourself for UUID identifiers and otherwise let Micronaut Data generate it, use:

[source,java]
----
@Id
@AutoPopulated(skipIfPresent = true)
UUID id;
----

With `skipIfPresent = true`, if `id` already has a non-null value at `save()` time, it will not be overwritten by the UUID generator. If it is null, a UUID will be generated at PrePersist.

NOTE: `@GeneratedValue` implies the ID is generated by the database and the column is omitted from INSERT statements. If you need to assign IDs manually, remove `@GeneratedValue` and use either manual assignment or `@AutoPopulated` as shown above.
