Since Micronaut Data 4.0 and Oracle23c database, an entity can be mapped to an JSON VIEW as follows:

snippet::example.ContactView[project-base="doc-examples/jdbc-example", source="main", tags="record-example"]

where "CONTACT_VIEW" is actual name of duality json view object in the database. It is currently supported only by the Oracle database, since version 23c.
More about Oracle JSON VIEW can be read here https://docs.oracle.com/en/database/oracle/oracle-database/23/jsnvu/overview-json-relational-duality-views.html.

Essentially, json view will be treated like mapped entity and will return JSON structure from the database and be mapped to java entity. All CRUD operations can be
performed against json view mapped entities.

Also, entity can be mapped to a ann:io.micronaut.data.annotation.JsonView[] as follows:

snippet::example.AddressSubView[project-base="doc-examples/jdbc-example", source="main", tags="record-example"]

The main difference between ann:io.micronaut.data.annotation.JsonView[] and ann:io.micronaut.data.annotation.JsonSubView[], and the reason for the existence of the ann:io.micronaut.data.annotation.JsonSubView[] annotation, is to specify for which classes the creation
SQL script will be generated. SQL scripts are generated for JsonViews, but not for JsonSubViews.

==== Specifying joins

You can define relationships between entities within JSON views by using ann:io.micronaut.data.annotation.Relation[]. Tables are
joined automatically, on columns annotated with ann:io.micronaut.data.annotation.Id[] by default, but if user specified columns to join in
by ann:io.micronaut.data.annotation.JoinColumn[], those columns will be used.

NOTE: If ann:io.micronaut.data.annotation.JoinColumn[] is not specified, property name of Json View class needs to match the name of the corresponding entity class property name.

For example, to associate a `StudentView` with its related `StudentScheduleSubView` entries in a one-to-many relationship,
annotate your view class using `JoinColumn`, where `name` is the identifier for `StudentView`, and `referencedColumnName`
is the identifier for `StudentScheduleSubView`, as follows:

snippet::example.StudentView[project-base="doc-examples/jdbc-example", source="main", tags="class-example"]

==== Using `@MappedProperty` annotation

Json view field names do not need to match the underlying table field names, and if it's not matching, then users must annotate the field
The fields of types annotated annotated with ann:io.micronaut.data.annotation.JsonView[] or ann:io.micronaut.data.annotation.JsonSubView[] do not need the match the corresponding entities field names as specified by the `entity` member (in the below case `Teacher`).

The `@MappedProperty` annotation can be used to control which underlying field the view matches in the entity.

The following example uses a different name in the view the `Teacher` entities `id` and `name` fields, remapping them to `teachID` and `teacher` respectively.

Json view field names do not need to match the underlying table field names, and if it's not matching, then users must annotate the field

snippet::example.TeacherSubView[project-base="doc-examples/jdbc-example", source="main", tags="class-example"]

==== Schema generation

Given the example entities above the following JSON Duality View definition is generated:

[source,sql]
----
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW STUDENT_VIEW AS
    SELECT JSON {
        '_id' : S.ID, -- <1>
        'name' : S.NAME, -- <2>
        'schedule' : [SELECT JSON { -- <3>
            'id' : SC.ID
        }
        FROM TBL_STUDENT_CLASSES SC
        WITH UPDATE INSERT DELETE -- <4>
        WHERE S."ID" = SC."STUDENT_ID" -- <5>
        ]}
    FROM TBL_STUDENT S
    WITH UPDATE INSERT DELETE -- <6>
----

<1> Generated identity column, annotated with ann:io.micronaut.data.annotation.Generated[] and ann:io.micronaut.data.annotation.Id[]
<2> Ordinary column
<3> Relation column, annotated with ann:io.micronaut.data.annotation.Relation[]
<4> Operations supported, specified by operations field in ann:io.micronaut.data.annotation.JsonSubView[]
<5> Column matching, specified by ann:io.micronaut.data.annotation.JoinColumn[]
<6> Operations supported, specified by operations field in ann:io.micronaut.data.annotation.JsonView[] (defaults to UPDATE INSERT DELETE)

More documentation: https://docs.oracle.com/en/database/oracle/oracle-database/26/jsnvu/overview-json-relational-duality-views.html/[link]

==== Operations supported

Users can specify sql operations supported for `JsonView` and `JsonSubView` using the `operations` field, if not specified, it defaults to `{ INSERT, UPDATE, DELETE }`.

snippet::example.StudentScheduleSubView[project-base="doc-examples/jdbc-example", source="main", tags="class-example"]

More documentation: https://docs.oracle.com/en/database/oracle/oracle-database/26/jsnvu/overview-json-relational-duality-views.html/[link]

==== Optimistic Locking

You can use optimistic/lock-free concurrency control with duality views, writing JSON documents or committing their updates only when other sessions haven't modified them concurrently.

Optimistic concurrency control at the document level uses embedded ETAG values in field etag, which is in the object that is the value of field `_metadata`.

Example of class used to map `_metadata` field:

[source,java]
----
/**
 * The Json Duality View metadata.
 *
 * @param etag A unique identifier for a specific version of the document, as a string of hexadecimal characters.
 * @param asof The latest system change number (SCN) for the JSON document, as a JSON number.
*              This records the last logical point in time at which the document was generated.
 */
@Introspected
public record Metadata(
    String etag,
    String asof
) {
}
----

Then this metadata class can be declared as property of class mapped to Json Duality View like this:

[source,java]
----
@JsonProperty("_metadata")
Metadata metadata;
----

If Json Duality View mapped entity is updated with invalid or unexpected `etag` value of the `metadata` field
then `OptimisticLockingException` will be thrown.

NOTE: Using `@Version` is not supported in Json Duality View mapped classes.

==== Limitations

* During schema creation, json view mapped entities are skipped, and it is expected for users to create them manually or via migration scripts.
