Getting your project ready for a native GraalVM build is JDBC driver dependent.

WARNING: GraalVM substrate remains an evolving and experimental feature of GraalVM, hence support for GraalVM substrate in Micronaut Data is also regarded as experimental and evolving.

Generally you need to add a `@TypeHint(...)` declaration to your `Application` class that tells GraalVM what is the class that represents the JDBC driver and you need to add the driver to the class that are initialized at build time with the `--initialize-at-build-time=DRIVER_CLASS_NAME` flag which you can add to the `native-image.properties` file found in `src/main/resources/META-INF/native-image` for a project that was created with `mn create-app my-app --features graal-native-image`.

NOTE: MySQL is as of this time unsupported in native image due to https://bugs.mysql.com/bug.php?id=91968[this issue].

==== Configuration for H2

The changes for H2 are:

.`@TypeHint` Declaration in Application Class
[source,java]
----
@TypeHint(typeNames = {"org.h2.Driver", "org.h2.mvstore.db.MVTableEngine"})
----

.GraalVM Flags
[source,bash]
----
--report-unsupported-elements-at-runtime --initialize-at-build-time=org.h2.Driver
----

NOTE: The `--report-unsupported-elements-at-runtime` flag is needed for H2 if you use the embedded H2 server otherwise can be omitted.

==== Configuration for Postgres

The changes for Postgres JDBC Driver (`org.postgresql:postgresql:42.2.8` or above) are:

.`@TypeHint` Declaration in Application Class
[source,java]
----
@TypeHint(org.postgresql.Driver.class)
----

.GraalVM Flags
[source,bash]
----
--initialize-at-build-time=org.postgresql.Driver,org.postgresql.util.SharedTimer
----

==== Configuration for Oracle

The changes for Oracle JDBC driver (`com.oracle.ojdbc:ojdbc8:19.3.0.0` or above) are quite extensive and are documented in https://github.com/oracle/graal/issues/1748#issuecomment-542353582[this Github issue].

==== Configuration for Microsoft SQL Server

The changes for SQL Server JDBC Driver (`com.microsoft.sqlserver:mssql-jdbc:7.2.2.jre8` or above) are:

.`@TypeHint` Declaration in Application Class
[source,java]
----
@TypeHint(typeNames = "com.microsoft.sqlserver.jdbc.SQLServerDriver")
----

.GraalVM Flags
[source,bash]
----
-H:IncludeResourceBundles=com.microsoft.sqlserver.jdbc.SQLServerResource \
--initialize-at-build-time=com.microsoft.sqlserver.jdbc.SQLServerResource \
--initialize-at-run-time=java.sql.DriverManager
----
