Since Azure Cosmos database is not relational like most of the database Micronaut Data supports, it does have different implementations in some specifics.

=== Relation Mapping ===

Since this database is not relational and cross container and cross document joins are not supported, relations between entities/containers are not mappable. The only type of relations supported is `@Relation(value = Relation.Kind.EMBEDDED)` and `@Relation(value = Relation.Kind.ONE_TO_MANY)` which are actually relations between document and its embedded objects or arrays. Here is an example of such mapping:

snippet::example.Family[project-base="doc-examples/azure-cosmos-example", source="main", tags="relations", indent="0"]

where `Relation` mapping in this case is needed for our query builder to generate projections, ordering and filtering by the fields in the embedded objects or arrays which can be seen in methods declared in `FamilyRepository`

snippet::example.FamilyRepository[project-base="doc-examples/azure-cosmos-example", source="main", tags="relations"]

Due to the nature of the database and implementation of relations, cascading does not have much sense either. Embedded objects and arrays in the documents are being automatically saved when the document is saved.

=== Identity ===

With Azure Cosmos Db, every document has got internal id property of String type. Micronaut Data Cosmos expects @Id to be of types: Short, Integer, Long, String or UUID. When saving and reading the type is serialized to String and deserialized from a String stored in the id property. Declaring a property annotated with @Id with an unsupported type will result in an exception.
Generation of ids will work only for String and UUID where UUID can be generated either by using the @GeneratedValue or @AutoPopulated annotations. String id can be generated only by using @GeneratedValue annotation. Numerical ids cannot be auto generated, and it is up to user to set the id value before saving.
Composite identities are not supported.

=== Partition Key ===

In Azure Cosmos Db partition keys are the core element to distributing data efficiently into different logical and physical sets so that the queries performed against the database are completed as quickly as possible. Every mapped entity should have partition key defined. Like explained above, it can be defined using ann:io.micronaut.data.cosmos.annotation.PartitionKey[] annotation on appropriate entity field or via configuration as explained in <<azureCosmosConfiguration, configuration>> section. Efficiently using well defined partition key will improve operations performance and reduce request unit costs.
Micronaut Data Cosmos tries to use a partition key whenever possible. Here are some repository method examples that make use of a partition key in read, update or delete operations

snippet::example.FamilyRepository[project-base="doc-examples/azure-cosmos-example", source="main", tags="partitionkey"]

=== Diagnostics ===

Azure Cosmos Db provides operations diagnostics so users can get that information and perhaps integrate  with their logging or metrics system. In Micronaut Data Azure we expose interface api:io.micronaut.data.cosmos.operations.CosmosDiagnosticsProcessor[]. Users need to implement this interface and add it to the context so it can be available to our operations classes. It has only one method
[source,java]
----
void processDiagnostics(String operationName, @Nullable CosmosDiagnostics cosmosDiagnostics, @Nullable String activityId, double requestCharge);
----
which is being called after each operation against Azure Cosmos Db. Parameter `operationName` is internal operation name in Micronaut Data Azure and it has got these known values:
[source,java]
----
String CREATE_DATABASE_IF_NOT_EXISTS = "CreateDatabaseIfNotExists";
String REPLACE_DATABASE_THROUGHPUT = "ReplaceDatabaseThroughput";
String CREATE_CONTAINER_IF_NOT_EXISTS = "CreateContainerIfNotExists";
String REPLACE_CONTAINER_THROUGHPUT = "ReplaceContainerThroughput";
String REPLACE_CONTAINER = "ReplaceContainer";
String QUERY_ITEMS = "QueryItems";
String EXECUTE_BULK = "ExecuteBulk";
String CREATE_ITEM = "CreateItem";
String REPLACE_ITEM = "ReplaceItem";
String DELETE_ITEM = "DeleteItem";
----
so user is aware for which operation diagnostics are being processed.
