When using an existing Azure Cosmos database with existing containers no special configuration is needed, except the endpoint, key and database name. However, for test purposes or when database containers need to be created during application startup there are additional options to configure containers.

As mentioned in the <<azureCosmosQuickStart, Quick Start>> every class annotated with @MappedEntity will correspond to one container in Azure Cosmos Db. If the property azure.cosmos.database.update-policy is set to NONE then no attempt to create the container will be made. If that value is set to CREATE_IF_NOT_EXISTS then the application will attempt to create container if the container does not already exist. Whilst, if the value is UPDATE the application will try to replace existing any containers and its properties.

Currently, it is only possible to configure a small subset of properties for the database and containers. For the database throughput properties can be configured whilst for containers the throughput properties and partition key path are configurable.

NOTE: An additional way to configure the partition key value is adding the annotation ann:io.micronaut.data.cosmos.annotation.PartitionKey[]

The below is an example application configuration showing container and db properties used when creating new containers if the containers don't already exist:

[configuration]
----
include::doc-examples/azure-cosmos-example-java/src/main/resources/application-example.yml[]
----
