jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
    compileTimeHibernateProxies: true
test-resources:
  containers:
    mysql:
      image-name: mysql:8.4.5
