jpa:
  default:
    reactive: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: create-drop
        show_sql: true
    compileTimeHibernateProxies: true
