/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.data.model.schema.sql;

import io.micronaut.core.annotation.Internal;
import org.jspecify.annotations.Nullable;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.exceptions.MappingException;
import io.micronaut.data.model.DataType;
import io.micronaut.data.model.JsonDataType;
import io.micronaut.data.model.query.builder.sql.Dialect;

/**
 * Represents a SQL database column mapped from persistent entity field.
 *
 * @author radovanradic
 * @since 4.13.0
 */
@Internal
public final class SqlColumnMapping {

    private static final String NUMERIC_TYPE = "NUMERIC";
    private static final String NUMBER_TYPE = "NUMBER";

    private final String name;
    private final DataType dataType;
    private final SqlDbType dbType;
    private final @Nullable Integer length;
    private final @Nullable Integer precision;
    private final @Nullable Integer scale;
    private final boolean required;
    private final boolean autoGenerated;
    private final GeneratedValue.Type generatedValueType;
    private final @Nullable String definition;
    private final @Nullable JsonDataType jsonDataType;
    @Nullable
    private String sqlType;

    /**
     * Constructs a new Column instance.
     *
     * @param name               the name of the column
     * @param dataType           the data type of the column
     * @param dbType             the database-specific type
     */
    public SqlColumnMapping(String name, DataType dataType, SqlDbType dbType) {
        this(name, dataType, dbType, null, null, null, false, false, GeneratedValue.Type.AUTO, null, null);
    }

    /**
     * Constructs a new Column instance.
     *
     * @param name               the name of the column
     * @param dataType           the data type of the column
     * @param dbType             the database-specific type
     * @param length             the length of the column (optional)
     * @param precision          the precision of the column (optional)
     * @param scale              the scale of the column (optional)
     * @param required           whether the column is required
     * @param autoGenerated      whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition         the definition of the column (optional)
     * @param jsonDataType       the JSON data type (optional)
     */
    public SqlColumnMapping(String name, DataType dataType, SqlDbType dbType, @Nullable Integer length, @Nullable Integer precision, @Nullable Integer scale,
                            boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, @Nullable String definition, @Nullable JsonDataType jsonDataType) {
        this.name = name;
        this.dataType = dataType;
        this.dbType = dbType;
        this.length = length;
        this.precision = precision;
        this.scale = scale;
        this.required = required;
        this.autoGenerated = autoGenerated;
        this.generatedValueType = generatedValueType;
        this.definition = definition;
        this.jsonDataType = jsonDataType;
    }

    /**
     * Constructs a new Column instance with simplified parameters.
     *
     * @param name              the name of the column
     * @param dataType          the data type of the column
     * @param dbType            the database-specific type code
     * @param primaryKey        whether the column is a primary key
     * @param length            the length of the column (optional)
     * @param required          whether the column is required
     * @param autoGenerated     whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition        the definition of the column (optional)
     */
    public SqlColumnMapping(String name, DataType dataType, SqlDbType dbType, boolean primaryKey, @Nullable Integer length, boolean required,
                            boolean autoGenerated, GeneratedValue.Type generatedValueType, @Nullable String definition) {
        this(name, dataType, dbType, length, null, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    /**
     * Constructs a new Column instance with additional precision parameter.
     *
     * @param name              the name of the column
     * @param dataType          the data type of the column
     * @param dbType            the database-specific type code
     * @param primaryKey        whether the column is a primary key
     * @param length            the length of the column (optional)
     * @param precision         the precision of the column (optional)
     * @param required          whether the column is required
     * @param autoGenerated     whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition        the definition of the column (optional)
     */
    public SqlColumnMapping(String name, DataType dataType, SqlDbType dbType, boolean primaryKey, @Nullable Integer length,
                            @Nullable Integer precision, boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, @Nullable String definition) {
        this(name, dataType, dbType, length, precision, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    /**
     * Returns the name of the column.
     *
     * @return the name of the column
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the data type of the column.
     *
     * @return the data type of the column
     */
    public DataType getDataType() {
        return dataType;
    }

    /**
     * Returns the database-specific type of this column.
     *
     * @return the database-specific type of this column
     */
    public SqlDbType getDbType() {
        return dbType;
    }

    /**
     * Returns whether the column is required.
     *
     * @return true if the column is required, false otherwise
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Indicates whether the column is automatically generated.
     *
     * @return true if the column is auto-generated, false otherwise
     */
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    /**
     * Returns the type of generated value for this column, if any.
     *
     * @return the type of generated value, or null if no generated value is defined
     */
    public GeneratedValue.Type getGeneratedValueType() {
        return generatedValueType;
    }

    /**
     * Returns the definition of the column, if available.
     *
     * @return the definition of the column, or null if not specified
     */
    @Nullable
    public String getDefinition() {
        return definition;
    }

    /**
     * Returns the SQL type representation of this column for the given dialect.
     *
     * @param dialect the SQL dialect to generate the type for
     * @return the SQL type representation of this column
     */
    @SuppressWarnings("java:S3776")
    public  String getSqlType(Dialect dialect) {
        if (this.sqlType != null) {
            return this.sqlType;
        }
        this.sqlType = switch (dataType) {
            case STRING -> varcharType(length);
            case UUID -> {
                if (dialect == Dialect.ORACLE || dialect == Dialect.MYSQL) {
                    yield varcharType(36);
                } else if (dialect == Dialect.SQL_SERVER) {
                    yield "UNIQUEIDENTIFIER";
                } else {
                    yield "UUID";
                }
            }
            case BOOLEAN -> {
                if (dialect == Dialect.ORACLE) {
                    yield "NUMBER(1)";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // TODO: was "BIT NOT NULL";
                    yield "BIT";
                } else {
                    yield "BOOLEAN";
                }
            }
            case TIMESTAMP -> {
                if (dialect == Dialect.ORACLE) {
                    yield "TIMESTAMP";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // sql server timestamp is an internal type, use datetime instead
                    yield "DATETIME2";
                } else if (dialect == Dialect.MYSQL) {
                    // mysql doesn't allow timestamp without default?
                    yield "TIMESTAMP(6) DEFAULT NOW(6)";
                } else {
                    yield "TIMESTAMP";
                }
            }
            case DATE -> "DATE";
            case TIME -> {
                if (dialect == Dialect.ORACLE) {
                    // OracleDB doesn't have a TIME type, so DATE is used
                    yield "DATE ";
                } else {
                    yield "TIME(6)";
                }
            }
            case LONG -> {
                if (dialect == Dialect.ORACLE) {
                    yield "NUMBER(19)";
                } else if (autoGenerated) {
                    yield "INTEGER";
                } else {
                    yield "BIGINT";
                }
            }
            case CHARACTER -> "CHAR(" + length + ")";
            case INTEGER -> {
                if (precision != null) {
                    String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                    yield numericName + "(" + precision + ")";
                } else if (dialect == Dialect.ORACLE) {
                    yield "NUMBER(10)";
                } else if (autoGenerated) {
                    yield "INTEGER";
                } else if (dialect == Dialect.POSTGRES) {
                    yield "INTEGER";
                } else {
                    yield "INT";
                }
            }
            case BIGDECIMAL -> {
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        yield numericName + "(" + precision + "," + scale + ")";
                    } else {
                        yield floatType(precision);
                    }
                } else if (dialect == Dialect.ORACLE) {
                    yield floatType(126);
                } else {
                    yield "DECIMAL";
                }
            }
            case FLOAT -> {
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        yield numericName + "(" + precision + "," + scale + ")";
                    } else {
                        yield floatType(precision);
                    }
                } else if (dialect == Dialect.ORACLE || dialect == Dialect.SQL_SERVER) {
                    yield floatType(53);
                } else if (dialect == Dialect.POSTGRES) {
                    yield "REAL";
                } else {
                    yield "FLOAT";
                }
            }
            case BYTE_ARRAY -> {
                if (dialect == Dialect.POSTGRES) {
                    yield "BYTEA";
                } else if (dialect == Dialect.SQL_SERVER) {
                    yield "VARBINARY(MAX)";
                } else if (dialect == Dialect.ORACLE) {
                    yield "BLOB";
                } else {
                    yield "BLOB";
                }
            }
            case DOUBLE -> {
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        yield numericName + "(" + precision + "," + scale + ")";
                    } else {
                        yield floatType(precision);
                    }
                } else if (dialect == Dialect.ORACLE) {
                    yield floatType(23);
                } else if (dialect == Dialect.MYSQL || dialect == Dialect.H2) {
                    yield "DOUBLE";
                } else {
                    yield "DOUBLE PRECISION";
                }
            }
            case SHORT -> {
                if (dialect == Dialect.ORACLE) {
                    yield "NUMBER(5)";
                } else  {
                    yield "SMALLINT";
                }
            }
            case BYTE -> {
                if (dialect == Dialect.ORACLE) {
                    yield "NUMBER(3)";
                } else if (dialect == Dialect.POSTGRES) {
                    yield "SMALLINT";
                } else {
                    yield "TINYINT";
                }
            }
            case JSON -> getJsonSqlType(dialect);
            // TODO: Array types are not supported for all dialects so might throw an error?
            // Think only H2 and Postgres support these type defs
            case STRING_ARRAY, CHARACTER_ARRAY -> "VARCHAR(255) ARRAY";
            case SHORT_ARRAY -> {
                if (dialect == Dialect.POSTGRES) {
                    yield "SMALLINT ARRAY";
                } else {
                    yield "TINYINT ARRAY";
                }
                }
            case INTEGER_ARRAY -> {
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    yield "INTEGER ARRAY";
                } else {
                    yield "INT ARRAY";
                }
            }
            case LONG_ARRAY -> "BIGINT ARRAY";
            case FLOAT_ARRAY -> {
                if (dialect == Dialect.H2 || dialect == Dialect.POSTGRES) {
                    yield "REAL ARRAY";
                } else {
                    yield "FLOAT ARRAY";
                }
            }
            case DOUBLE_ARRAY -> {
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    yield "DOUBLE PRECISION ARRAY";
                } else {
                    yield "DOUBLE ARRAY";
                }
            }
            case BOOLEAN_ARRAY -> "BOOLEAN ARRAY";
            case DURATION -> {
                if (dialect == Dialect.ORACLE) {
                    yield "INTERVAL DAY TO SECOND";
                }
                yield varcharType(255);
            }
            case PERIOD -> {
                if (dialect == Dialect.ORACLE) {
                    yield "INTERVAL YEAR TO MONTH";
                }
                yield varcharType(255);
            }
            default -> {
                if (dbType == SqlDbType.ENUM) {
                    // Special case for enum
                    yield varcharType(255);
                } else if (dbType == SqlDbType.CLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        yield "TEXT";
                    } else {
                        yield "CLOB";
                    }
                } else if (dbType == SqlDbType.BLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        yield "BYTEA";
                    } else {
                        yield "BLOB";
                    }
                } else {
                    throw new MappingException("Unable to create table column for property [" + name + "] with unknown data type: " + dataType);
                }
            }
        };
        return this.sqlType;
    }

    /**
     * Returns the SQL type representation for JSON data type based on the provided dialect.
     *
     * @param dialect the SQL dialect to determine the JSON SQL type for
     * @return the SQL type representation for JSON data type
     */
    private String getJsonSqlType(Dialect dialect) {
        return switch (dialect) {
            case POSTGRES -> "JSONB";
            case SQL_SERVER -> "NVARCHAR(MAX)";
            case ORACLE -> {
                if (jsonDataType == JsonDataType.DEFAULT) {
                    yield "JSON";
                } else if (jsonDataType == JsonDataType.BLOB) {
                    yield "BLOB";
                } else {
                    yield "CLOB";
                }
            }
            default -> "JSON";
        };
    }

    private static String floatType(Integer precision) {
        return "FLOAT(" + precision + ")";
    }

    private static String varcharType(@Nullable Integer length) {
        return length == null ? "VARCHAR" : "VARCHAR(" + length + ")";
    }
}
