It is common to want to add a field that represents the time when an entity was first persisted and the time when it was last updated.

You can annotate a property that is a date type of entity with ann:data.annotation.DateCreated[] which will be automatically populated when saving entities and indicates the date a record was created.

You can also annotate a property that is a date type of entity with ann:data.annotation.DateUpdated[] which will be automatically populated whenever the entity is updated either via the `persist` method or when using one of the batch update methods of Micronaut Data.

If you sometimes want to provide values yourself and otherwise let Micronaut Data populate them, you can use the optional `skipIfPresent` flag:

[source,java]
----
@DateCreated(skipIfPresent = true)
Instant created;

@DateUpdated(skipIfPresent = true)
Instant updated;
----

Behavior:

* `@DateCreated`: `skipIfPresent = true` preserves a non-null value on insert; otherwise Micronaut Data assigns the timestamp.
* `@DateUpdated`: `skipIfPresent = true` is considered only on insert. On updates, `@DateUpdated` is always refreshed by Micronaut Data (it is not skipped), regardless of the current value.

NOTE: If you update the entity with an external SQL statement or custom logic you will need to update the underlying `DateUpdated` column manually.

=== JPA Hibernate and Entity Timestamps

The ann:data.annotation.DateCreated[] and ann:data.annotation.DateUpdated[] annotations require a `ValidatorFactory` bean to be present in the application context when used with JPA Hibernate.
This can be provided by ensuring one of

dependency::io.micronaut.validation:micronaut-validation[]

or

dependency::io.micronaut.beanvalidation:micronaut-hibernate-validator[]

is added to your project.
