plugins {
    id "io.micronaut.build.internal.data-example"
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime 'netty'
    testRuntime "junit5"
}

dependencies {
    annotationProcessor mn.micronaut.http.validation
    annotationProcessor projects.micronautDataProcessor
    annotationProcessor projects.micronautDataJpaMetamodelProcessor
    annotationProcessor mnSerde.micronaut.serde.processor

    implementation libs.managed.jakarta.data.api
    implementation mnSql.jakarta.persistence.api
    implementation projects.micronautDataJdbc
    implementation mn.micronaut.http.client.core
    implementation mnSerde.micronaut.serde.jackson
    implementation mnSql.micronaut.jdbc.hikari

    runtimeOnly mnLogging.logback.classic
    runtimeOnly mnSql.h2
    testImplementation mnTest.micronaut.test.junit5
}

application {
    mainClass = "com.example.Application"
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += [
            "-Amicronaut.data.jpa.metamodel.enabled=true"
    ]
}

