plugins {
    id "java-library"
    id "io.micronaut.build.internal.data-base"
    id "io.micronaut.build.internal.data-dependencies"
}

dependencies {

    testImplementation projects.micronautJakartaDataTck.micronautSupport
    testImplementation projects.micronautDataJdbc
    testImplementation projects.micronautDataProcessor
    testImplementation mnValidation.micronaut.validation.processor
    testImplementation mnValidation.micronaut.validation

    testRuntimeOnly mnTest.junit.jupiter.engine
    testRuntimeOnly mnSql.micronaut.jdbc.tomcat
    testRuntimeOnly mnLogging.logback.classic
    testRuntimeOnly mnSql.h2
    testRuntimeOnly mn.snakeyaml
}

test {
    scanForTestClasses true
    systemProperty("junit.jupiter.extensions.autodetection.enabled", "true")
    useJUnitPlatform()
    maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
}
