import io.micronaut.testresources.buildtools.KnownModules

plugins {
    id "io.micronaut.build.internal.data-add-lombok-first"
    id "io.micronaut.build.internal.data-native-example"
}

application {
    mainClass = "example.Application"
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime "netty"
    testRuntime "junit5"
    testResources {
        enabled = true
        inferClasspath = false
        if (providers.environmentVariable('TESTPILOT_USERNAME').isPresent()) {
            additionalModules.add(KnownModules.JDBC_ORACLE_TEST_PILOT)
        }
        clientTimeout = 300
        version = libs.versions.micronaut.testresources.get()
    }
}

dependencies {
    annotationProcessor projects.micronautDataProcessor
    annotationProcessor mnSql.hibernate.jpamodelgen
    annotationProcessor mnValidation.micronaut.validation
    compileOnly libs.lombok
    implementation projects.micronautDataJdbc
    implementation(mnRxjava3.micronaut.rxjava3)
    implementation mn.micronaut.http.client
    implementation mnValidation.micronaut.validation
    implementation(mnSql.jakarta.persistence.api)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnSerde.micronaut.serde.support)

    runtimeOnly mnSql.micronaut.jdbc.tomcat
    runtimeOnly mnLogging.logback.classic
    runtimeOnly mnSql.h2
    runtimeOnly mnSql.ojdbc11

    testResourcesService mnSql.ojdbc11
}

sourceSets {
    generated {
        java {
            srcDirs = [layout.buildDirectory.dir("generated/java")]
        }
    }
}

//compileJava.options.fork = true
//compileJava.options.forkOptions.jvmArgs = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005']

