micronaut:
  data:
    multi-tenancy:
      mode: DATASOURCE
  multitenancy:
    tenantresolver:
      httpheader:
        enabled: true

r2dbc:
  datasources:
    foo:
      db-type: mariadb
      schema-generate: CREATE_DROP
      dialect: MYSQL
    bar:
      db-type: mariadb
      schema-generate: CREATE_DROP
      dialect: MYSQL

test-resources:
  containers:
    mysql:
      image-name: mysql:8.2
