plugins {
    id "groovy"
    id "io.micronaut.build.internal.data-example"
}

application {
    mainClass = "example.Application"
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime "netty"
    testRuntime "junit5"
}

dependencies {
    // Override app plugin version
    compileOnly projects.micronautDataProcessor
    compileOnly projects.micronautDataDocumentProcessor

    implementation projects.micronautDataNitrite
    implementation libs.nitrite.spatial
    implementation libs.jackson.datatype.jts
    implementation mnSql.jakarta.persistence.api

    testRuntimeOnly "org.apache.groovy:groovy:${libs.versions.groovy.get()}"

    runtimeOnly mnLogging.logback.classic
}

