package example;

import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Requires;
import io.micronaut.data.jdbc.runtime.multitenancy.TenantDataSourceResolver;
import io.micronaut.data.jdbc.runtime.multitenancy.TenantRoutingDataSource;
import jakarta.inject.Named;
import jakarta.inject.Singleton;
import org.apache.tomcat.jdbc.pool.PoolProperties;

import javax.sql.DataSource;

@Factory
@Requires(property = "example.runtime-routing.enabled", value = "true")
public class RuntimeRoutingDataSourceFactory {

    // tag::factory[]
    @Singleton
    @Named("default")
    DataSource defaultDataSource(RuntimeRoutingTenantResolver tenantResolver,
                                 TenantDataSourceResolver tenantDataSourceResolver) {
        return new TenantRoutingDataSource(
            buildPooledDataSource("default"),
            tenantResolver,
            tenantDataSourceResolver
        );
    }
    // end::factory[]

    static DataSource buildPooledDataSource(String tenantId) {
        PoolProperties properties = new PoolProperties();
        properties.setName("tenant-" + tenantId);
        properties.setDriverClassName("org.h2.Driver");
        properties.setUrl("jdbc:h2:mem:" + tenantId + ";LOCK_TIMEOUT=10000;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE TABLE IF NOT EXISTS BOOK (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TITLE VARCHAR(255), PAGES INTEGER)");
        properties.setUsername("sa");
        properties.setPassword("");
        properties.setInitialSize(1);
        properties.setMaxActive(4);
        properties.setMinIdle(1);
        properties.setTestOnBorrow(true);
        properties.setValidationQuery("SELECT 1");
        return new org.apache.tomcat.jdbc.pool.DataSource(properties);
    }
}
