plugins {
    id "io.micronaut.build.internal.data-add-lombok-first"
    id "io.micronaut.build.internal.data-native-example"
    id "io.micronaut.test-resources"
}

application {
    mainClass = "example.Application"
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime "netty"
    testRuntime "junit5"
    testResources {
        additionalModules.add("jdbc-oracle-free")
        clientTimeout = 300
        version = libs.versions.micronaut.testresources.get()
    }
}

dependencies {
    annotationProcessor projects.micronautDataProcessor
    annotationProcessor mnValidation.micronaut.validation
    implementation projects.micronautDataJdbc
    implementation mn.micronaut.http.client
    implementation mnValidation.micronaut.validation
    implementation(mnSql.jakarta.persistence.api)
    testImplementation(mnTestResources.micronaut.test.resources.extensions.junit.platform)

    runtimeOnly mnSql.micronaut.jdbc.tomcat
    runtimeOnly mnLogging.logback.classic
    runtimeOnly mnSql.ojdbc11
}

sourceSets {
    generated {
        java {
            srcDirs = ["$build/generated/java"]
        }
    }
}
