micronaut:
  application:
    name: example
  propagation: thread_local

r2dbc:
  datasources:
    default:
      db-type: mariadb
      dialect: mysql
datasources:
  default:
    db-type: mariadb
    dialect: mysql

test-resources:
  containers:
    mysql:
      image-name: container-registry.oracle.com/mysql/community-server:9.6.0
