micronaut:
  application:
    name: example

r2dbc:
  datasources:
    default:
      db-type: postgres
      dialect: postgres
datasources:
  default:
    db-type: postgres
    dialect: postgres

test-resources:
  containers:
    mysql:
      image-name: container-registry.oracle.com/mysql/community-server:9.6.0
