/*
 * Copyright 2017-2020 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.data.processor.sql

import io.micronaut.data.intercept.InsertEntityInterceptor
import io.micronaut.data.intercept.annotation.DataMethod
import io.micronaut.data.model.DataType
import io.micronaut.data.model.entities.Person
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder
import io.micronaut.data.processor.model.SourcePersistentEntity
import io.micronaut.data.processor.visitors.AbstractDataSpec
import io.micronaut.inject.BeanDefinition
import io.micronaut.inject.ast.ClassElement
import io.micronaut.inject.writer.BeanDefinitionVisitor
import spock.lang.PendingFeature
import spock.lang.Unroll

import static io.micronaut.data.processor.visitors.TestUtils.getDataInterceptor
import static io.micronaut.data.processor.visitors.TestUtils.getDataResultType
import static io.micronaut.data.processor.visitors.TestUtils.getDataTypes
import static io.micronaut.data.processor.visitors.TestUtils.getOperationType
import static io.micronaut.data.processor.visitors.TestUtils.getOutBindingParameters
import static io.micronaut.data.processor.visitors.TestUtils.getParameterPropertyPaths
import static io.micronaut.data.processor.visitors.TestUtils.getQuery
import static io.micronaut.data.processor.visitors.TestUtils.getRawQuery
import static io.micronaut.data.processor.visitors.TestUtils.getResultDataType

class BuildInsertSpec extends AbstractDataSpec {

    @Unroll
    void "test build create table for identity generation and dialect - #dialect"() {
        given:
        ClassElement element = buildClassElement("""
package test;
import io.micronaut.data.annotation.*;

class Test {
    @Id
    @GeneratedValue(GeneratedValue.Type.IDENTITY)
    private Long id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}

""")
        SqlQueryBuilder builder = new SqlQueryBuilder(dialect)
        def entity = new SourcePersistentEntity(element, {})
        def sql = builder.buildBatchCreateTableStatement(List.of(), entity)

        expect:
        sql == query

        where:
        dialect            | query
        Dialect.ORACLE     | 'CREATE TABLE "TEST" ("ID" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY (MINVALUE 1 START WITH 1 CACHE 100 NOCYCLE) PRIMARY KEY,"NAME" VARCHAR(255) NOT NULL)'
        Dialect.H2         | 'CREATE TABLE `test` (`id` BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,`name` VARCHAR(255) NOT NULL);'
        Dialect.POSTGRES   | 'CREATE TABLE "test" ("id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"name" VARCHAR(255) NOT NULL);'
        Dialect.SQL_SERVER | 'CREATE TABLE [test] ([id] BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,[name] VARCHAR(255) NOT NULL);'
        Dialect.MYSQL      | 'CREATE TABLE `test` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT,`name` VARCHAR(255) NOT NULL);'
    }

    @Unroll
    void "test build insert for identity generation and dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import java.util.UUID;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Version;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    Test save(String name);

    Test findById(Long id);
}

@MappedEntity
class Test {
    @Id
    @GeneratedValue(GeneratedValue.Type.IDENTITY)
    private Long id;
    private String name;
    @Version
    @GeneratedValue
    private Long version;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}

""")
        expect:
        getQuery(beanDefinition.getRequiredMethod("save", String)) == query

        where:
        dialect            | query
        Dialect.MYSQL      | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.ORACLE     | 'INSERT INTO "TEST" ("NAME") VALUES (?)'
        Dialect.H2         | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.POSTGRES   | 'INSERT INTO "test" ("name") VALUES (?)'
        Dialect.SQL_SERVER | 'INSERT INTO [test] ([name]) VALUES (?)'
    }

    @Unroll
    void "test build create table for UUID and dialect - #dialect"() {
        given:
        ClassElement element = buildClassElement("""
package test;
import java.util.UUID;
import io.micronaut.data.annotation.*;

class Test {
    @Id
    @GeneratedValue
    private UUID id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}

""")
        SqlQueryBuilder builder = new SqlQueryBuilder(dialect)
        def entity = new SourcePersistentEntity(element, {})
        def sql = builder.buildBatchCreateTableStatement(List.of(), entity)

        expect:
        sql == query

        where:
        dialect            | query
        Dialect.ORACLE     | 'CREATE TABLE "TEST" ("ID" VARCHAR(36) NOT NULL DEFAULT SYS_GUID() PRIMARY KEY,"NAME" VARCHAR(255) NOT NULL)'
        Dialect.H2         | 'CREATE TABLE `test` (`id` UUID NOT NULL DEFAULT random_uuid() PRIMARY KEY,`name` VARCHAR(255) NOT NULL);'
        Dialect.POSTGRES   | 'CREATE TABLE "test" ("id" UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),"name" VARCHAR(255) NOT NULL);'
        Dialect.SQL_SERVER | 'CREATE TABLE [test] ([id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),[name] VARCHAR(255) NOT NULL);'
        Dialect.MYSQL      | 'CREATE TABLE `test` (`id` VARCHAR(36) PRIMARY KEY NOT NULL,`name` VARCHAR(255) NOT NULL);'
    }

    @Unroll
    void "test build insert for UUID and dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import java.util.UUID;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, UUID> {
    Test save(String name);

    Test findById(UUID id);
}

@MappedEntity
class Test {
    @Id
    @GeneratedValue
    private UUID id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}

""")
        expect:
        getQuery(beanDefinition.getRequiredMethod("save", String)) == query
        getDataTypes(beanDefinition.getRequiredMethod("findById", UUID)) == [DataType.UUID]

        where:
        dialect            | query
        Dialect.MYSQL      | 'INSERT INTO `test` (`name`,`id`) VALUES (?,?)'
        Dialect.ORACLE     | 'INSERT INTO "TEST" ("NAME") VALUES (?)'
        Dialect.H2         | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.POSTGRES   | 'INSERT INTO "test" ("name") VALUES (?)'
        Dialect.SQL_SERVER | 'INSERT INTO [test] ([name]) VALUES (?)'
    }

    void "test build SQL insert statement with custom name and escaping"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.annotation.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.DataType;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<TableRatings, Long> {
}

@MappedEntity(value = "T-Table-Ratings", escape = true)
class TableRatings {
    @Id
    @GeneratedValue
    private Long id;

    @MappedProperty(value = "T-Rating", type = DataType.INTEGER)
    private final int rating;

    public TableRatings(int rating) {
        this.rating = rating;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRating() {
        return rating;
    }
}

""")

        def method = beanDefinition.findPossibleMethods("save").findFirst().get()

        expect:
        getQuery(method) == 'INSERT INTO "T-Table-Ratings" ("T-Rating") VALUES (?)'
    }

    void "test build SQL insert statement"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.model.entities.Person;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<Person, Long> {
}
""")

        def method = beanDefinition.getRequiredMethod("save", Person)

        expect:
        getQuery(method) == 'INSERT INTO "person" ("name","age","enabled","public_id","company_id") VALUES (?,?,?,?,?)'
        getParameterPropertyPaths(method) == ['name', 'age', 'enabled', 'publicId', 'company.myId'] as String[]
    }

    @PendingFeature(reason = "Bug in Micronaut core. Fixed by https://github.com/micronaut-projects/micronaut-core/commit/f6a488677d587be309d5b0abd8925c9a098cfdf9")
    void "test build SQL insert statement for repo with no super interface"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.TestBookPageRepository' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.annotation.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
interface TestBookPageRepository extends io.micronaut.data.tck.repositories.BookPageRepository {

}
""")

        def method = beanDefinition.findPossibleMethods("save").findFirst().get()
        expect:

        getQuery(method) == 'INSERT INTO "shelf_book" ("shelf_id","book_id") VALUES (?,?)'
        getParameterPropertyPaths(method) == ['name', 'age', 'enabled', 'publicId'] as String[]
    }

    void "test build SQL update"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.tck.entities.Food;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import java.util.UUID;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<Food, UUID> {
}
""")

        def method = beanDefinition.findPossibleMethods("update").findFirst().get()
        expect:

        getQuery(method) == 'UPDATE "food" SET "key"=?,"carbohydrates"=?,"portion_grams"=?,"updated_on"=?,"fk_meal_id"=?,"fk_alt_meal"=?,"loooooooooooooooooooooooooooooooooooooooooooooooooooooooong_name"=?,"fresh"=? WHERE ("fid" = ? AND fresh = \'Y\')'
        getParameterPropertyPaths(method) == ["key", "carbohydrates", "portionGrams", "updatedOn", "meal.mid", "alternativeMeal.mid", "longName", "fresh", "fid"] as String[]
    }

    void "test build custom SQL insert"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.tck.entities.Food;
import io.micronaut.data.tck.entities.Meal;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import java.util.UUID;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Food, UUID> {

    @Query("INSERT INTO food(key, carbohydrates) VALUES (:key, :carbohydrates)")
    void saveCustom(java.util.List<Food> food);

    @Query("INSERT INTO food(key, carbohydrates) VALUES (:key, :carbohydrates)")
    void saveCustomSingle(Food food);

    Food save(UUID fid, String key, int carbohydrates, Meal meal);

}
""")
        when:
        def saveCustom = beanDefinition.findPossibleMethods("saveCustom").findFirst().get()
        then:
        getRawQuery(saveCustom) == 'INSERT INTO food(key, carbohydrates) VALUES (?, ?)'
        getParameterPropertyPaths(saveCustom) == ["key", "carbohydrates"] as String[]
        when:
        def saveCustomSingle = beanDefinition.findPossibleMethods("saveCustomSingle").findFirst().get()
        then:
        getRawQuery(saveCustomSingle) == 'INSERT INTO food(key, carbohydrates) VALUES (?, ?)'
        getParameterPropertyPaths(saveCustomSingle) == ["key", "carbohydrates"] as String[]
        when:
        def save = beanDefinition.findPossibleMethods("save").findFirst().get()
        then:
        getQuery(save) == 'INSERT INTO "food" ("key","carbohydrates","portion_grams","created_on","updated_on","fk_meal_id","fk_alt_meal","loooooooooooooooooooooooooooooooooooooooooooooooooooooooong_name","fresh","fid") VALUES (?,?,?,?,?,?,?,?,?,?)'
        getDataInterceptor(save) == "io.micronaut.data.intercept.SaveOneInterceptor"
    }

    void "POSTGRES test build save returning "() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.tck.entities.Author;

@JdbcRepository(dialect= Dialect.POSTGRES)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {

    Book saveReturning(Book book);

}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO "book" ("author_id","genre_id","title","total_pages","publisher_id","last_updated") VALUES (?,?,?,?,?,?) RETURNING "author_id","genre_id","title","total_pages","publisher_id","last_updated","id"'
            getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
            getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
            getResultDataType(saveReturningMethod) == DataType.ENTITY
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
    }

    void "POSTGRES test build save all"() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.tck.entities.Author;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.POSTGRES)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {

    List<Book> saveReturning(List<Book> books);

}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO "book" ("author_id","genre_id","title","total_pages","publisher_id","last_updated") VALUES (?,?,?,?,?,?) RETURNING "author_id","genre_id","title","total_pages","publisher_id","last_updated","id"'
            getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
            getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveAllInterceptor"
            getResultDataType(saveReturningMethod) == DataType.ENTITY
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
    }

    void "test build custom SQL insert - expressions"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import java.util.UUID;

@JdbcRepository(dialect = Dialect.ANSI)
interface MyInterface extends GenericRepository<Book, UUID> {

    @Query("INSERT INTO Book(title, totalPages) VALUES (:title, :totalPages)")
    @ParameterExpression(name = "title", expression = "#{book.title}")
    @ParameterExpression(name = "totalPages", expression = "#{book.totalPages}")
    void saveCustom(Book book);

}
""")
        when:
            def saveCustom = beanDefinition.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getRawQuery(saveCustom) == 'INSERT INTO Book(title, totalPages) VALUES (?, ?)'
            getDataTypes(saveCustom) == [DataType.STRING, DataType.INTEGER]
            getParameterPropertyPaths(saveCustom) == ["title", "totalPages"] as String[]
            getDataInterceptor(saveCustom) == "io.micronaut.data.intercept.InsertEntityInterceptor"
    }

    void "test custom insert save all - JPA"() {
        given:
            def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Person;

@Repository
interface PersonRepository extends GenericRepository<Person, Long> {

    @Query("INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)")
    int saveCustom(List<Person> people);
}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)'
            getDataResultType(saveReturningMethod) == "int"
            getParameterPropertyPaths(saveReturningMethod) == ["name", "age"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.InsertAllInterceptor"
            getResultDataType(saveReturningMethod) == DataType.INTEGER
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT
    }

    void "test custom insert save one - JPA"() {
        given:
            def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Person;

@Repository
interface PersonRepository extends GenericRepository<Person, Long> {

    @Query("INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)")
    int saveCustom(Person person);
}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)'
            getDataResultType(saveReturningMethod) == "int"
            getParameterPropertyPaths(saveReturningMethod) == ["name", "age"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.InsertEntityInterceptor"
            getResultDataType(saveReturningMethod) == DataType.INTEGER
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT
    }

    void "POSTGRES save with tenant id"() {
        given:
            def repository = buildRepository('test.AccountRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.CrudRepository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Account;

@JdbcRepository(dialect= Dialect.POSTGRES)
interface AccountRepository extends CrudRepository<Account, Long> {
}
""")
        when:
            def saveMethod = repository.findPossibleMethods("save").findFirst().get()
        then:
            getQuery(saveMethod) == 'INSERT INTO "account" ("name","tenancy") VALUES (?,?)'
            getDataResultType(saveMethod) == "io.micronaut.data.tck.entities.Account"
            getParameterPropertyPaths(saveMethod) == ["name", "tenancy"] as String[]
            getDataInterceptor(saveMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
            getResultDataType(saveMethod) == DataType.ENTITY
            getOperationType(saveMethod) == DataMethod.OperationType.INSERT
    }

    @Unroll
    void "test build insert with CTE"() {
        given:
        def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.tck.entities.Person;

@JdbcRepository(dialect= Dialect.MYSQL)
@io.micronaut.context.annotation.Executable
interface PersonRepository extends CrudRepository<Person, Long> {

    @Query(\"""
            WITH ids AS (SELECT id FROM person)
            INSERT INTO person(name, age, enabled)
            VALUES (:name, :age, TRUE)
            \""")
    void customInsert(Person person);

}
""")
        def method = repository.findPossibleMethods("customInsert").findFirst().get()
        def insertQuery = getQuery(method)

        expect:
        insertQuery.replace('\n', ' ') == "WITH ids AS (SELECT id FROM person) INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE) "
        method.classValue(DataMethod, "interceptor").get() == InsertEntityInterceptor
    }

    void "ORACLE test build save returning"() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    Book saveReturning(Book book);
}
""")
        when:
        def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        def outBindingParameters = getOutBindingParameters(saveReturningMethod)
        then:
        getQuery(saveReturningMethod) == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?; END;'
        getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
        getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
        getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
        getResultDataType(saveReturningMethod) == DataType.ENTITY
        getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 7
        outBindingParameters[0].name == "author_id"
        outBindingParameters[0].dataType == DataType.LONG
        outBindingParameters[1].name == "genre_id"
        outBindingParameters[1].dataType == DataType.LONG
        outBindingParameters[2].name == "title"
        outBindingParameters[2].dataType == DataType.STRING
        outBindingParameters[3].name == "total_pages"
        outBindingParameters[3].dataType == DataType.INTEGER
        outBindingParameters[4].name == "publisher_id"
        outBindingParameters[4].dataType == DataType.LONG
        outBindingParameters[5].name == "last_updated"
        outBindingParameters[5].dataType == DataType.TIMESTAMP
        outBindingParameters[6].name == "id"
        outBindingParameters[6].dataType == DataType.LONG
    }

    void "ORACLE custom @Query insert returning multiple columns should fail for scalar return"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query("INSERT INTO book (author_id,genre_id,title,total_pages,publisher_id,last_updated) VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated) RETURNING id, title INTO ?, ?")
    String brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, java.time.LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("multiple columns require an entity return type")
    }

    void "ORACLE custom @Query insert returning with explicit INTO produces valid SQL"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?
        \""")
    Book customInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);

    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE" INTO ?
        \""")
    String customInsertReturningTitle(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def customInsertReturningMethod = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        def outBindingEntityParameters = getOutBindingParameters(customInsertReturningMethod)
        def customInsertReturningTitleMethod = repository.findPossibleMethods("customInsertReturningTitle").findFirst().get()
        def outBindingTitleParameters = getOutBindingParameters(customInsertReturningTitleMethod)
        then:
        getRawQuery(customInsertReturningMethod).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,? ; END;'
        getDataResultType(customInsertReturningMethod) == "io.micronaut.data.tck.entities.Book"
        getDataInterceptor(customInsertReturningMethod) == "io.micronaut.data.intercept.InsertReturningOneInterceptor"
        getResultDataType(customInsertReturningMethod) == DataType.ENTITY
        getOperationType(customInsertReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingEntityParameters.length == 7
        outBindingEntityParameters[0].name == "author_id"
        outBindingEntityParameters[0].dataType == DataType.LONG
        outBindingEntityParameters[1].name == "genre_id"
        outBindingEntityParameters[1].dataType == DataType.LONG
        outBindingEntityParameters[2].name == "title"
        outBindingEntityParameters[2].dataType == DataType.STRING
        outBindingEntityParameters[3].name == "total_pages"
        outBindingEntityParameters[3].dataType == DataType.INTEGER
        outBindingEntityParameters[4].name == "publisher_id"
        outBindingEntityParameters[4].dataType == DataType.LONG
        outBindingEntityParameters[5].name == "last_updated"
        outBindingEntityParameters[5].dataType == DataType.TIMESTAMP
        outBindingEntityParameters[6].name == "id"
        outBindingEntityParameters[6].dataType == DataType.LONG

        getRawQuery(customInsertReturningTitleMethod).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "TITLE" INTO ? ; END;'
        outBindingTitleParameters[0].name == "title"
        outBindingTitleParameters[0].dataType == DataType.STRING
        getDataResultType(customInsertReturningTitleMethod) == "java.lang.String"
        getDataInterceptor(customInsertReturningTitleMethod) == "io.micronaut.data.intercept.InsertReturningOneInterceptor"
        getOperationType(customInsertReturningTitleMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingTitleParameters.length == 1
    }

    void "ORACLE custom @Query insert returning Restaurant validates embedded out bindings"() {
        given:
        def repository = buildRepository('test.RestaurantRepository', '''
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Restaurant;
import io.micronaut.data.annotation.Query;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface RestaurantRepository extends GenericRepository<Restaurant, Long> {
    @Query("""
        INSERT INTO "RESTAURANT" ("NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code")
        VALUES (:name,:addressStreet,:addressZipCode,:hqAddressStreet,:hqAddressZipCode)
        RETURNING "NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code","ID" INTO ?,?,?,?,?,?
        """)
    Restaurant customInsertReturning(String name, String addressStreet, String addressZipCode, String hqAddressStreet, String hqAddressZipCode);
}
''')
        when:
        def method = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        def outBindingParameters = getOutBindingParameters(method)
        then:
        getRawQuery(method).replace('\n', ' ') == 'BEGIN INSERT INTO "RESTAURANT" ("NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code") VALUES (?,?,?,?,?) RETURNING "NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code","ID" INTO ?,?,?,?,?,? ; END;'
        getDataResultType(method) == "io.micronaut.data.tck.entities.Restaurant"
        getResultDataType(method) == DataType.ENTITY
        getOperationType(method) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 6
        outBindingParameters[0].name == "name"
        outBindingParameters[0].dataType == DataType.STRING
        outBindingParameters[1].name == "address_street"
        outBindingParameters[1].dataType == DataType.STRING
        outBindingParameters[2].name == "address_zip_code"
        outBindingParameters[2].dataType == DataType.STRING
        outBindingParameters[3].name == "hqaddress_street"
        outBindingParameters[3].dataType == DataType.STRING
        outBindingParameters[4].name == "hqaddress_zip_code"
        outBindingParameters[4].dataType == DataType.STRING
        outBindingParameters[5].name == "id"
        outBindingParameters[5].dataType == DataType.LONG
    }

    void "ORACLE custom @Query insert returning preserves existing BEGIN END block"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        BEGIN
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?;
        END;
        \""")
    Book customInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def method = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        then:
        getRawQuery(method).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?; END; '
    }

    void "ORACLE raw @Query insert returning ignores quoted returning text after clause in block"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        BEGIN
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE" INTO ?;
        DBMS_OUTPUT.PUT_LINE('ignored returning into ?');
        END;
        \""")
    String customInsertReturningTitle(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def method = repository.findPossibleMethods("customInsertReturningTitle").findFirst().get()
        def outBindingParameters = getOutBindingParameters(method)
        then:
        getRawQuery(method).replace('\n', ' ') == "BEGIN INSERT INTO \"BOOK\" (\"AUTHOR_ID\",\"GENRE_ID\",\"TITLE\",\"TOTAL_PAGES\",\"PUBLISHER_ID\",\"LAST_UPDATED\") VALUES (?,?,?,?,?,?) RETURNING \"TITLE\" INTO ?; DBMS_OUTPUT.PUT_LINE('ignored returning into ?'); END; "
        getOperationType(method) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 1
        outBindingParameters[0].name == "title"
        outBindingParameters[0].dataType == DataType.STRING
    }

    void "ORACLE raw @Query insert returning without INTO is rejected"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE"
        \""")
    String brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("must declare explicit returned columns and an INTO clause")
    }

    void "ORACLE raw @Query insert returning star is rejected"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING * INTO ?
        \""")
    Book brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("must declare explicit returned columns instead of RETURNING *")
    }

    void "duplicate physical insert columns fail fast unless reused for shared identity"() {
        when:
        buildRepository('test.ConflictingInsertEntityRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;

@JdbcRepository(dialect = Dialect.H2)
@io.micronaut.context.annotation.Executable
interface ConflictingInsertEntityRepository extends CrudRepository<ConflictingInsertEntity, Long> {
}

@MappedEntity("conflicting_insert_entity")
class ConflictingInsertEntity {
    @Id
    private Long id;

    @MappedProperty("shared_value")
    private String firstValue;

    @MappedProperty("shared_value")
    private String secondValue;

    Long getId() {
        return id;
    }

    void setId(Long id) {
        this.id = id;
    }

    String getFirstValue() {
        return firstValue;
    }

    void setFirstValue(String firstValue) {
        this.firstValue = firstValue;
    }

    String getSecondValue() {
        return secondValue;
    }

    void setSecondValue(String secondValue) {
        this.secondValue = secondValue;
    }
}
""")

        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("Conflicting insert mapping for column [shared_value]")
    }

    void "shared identity sequence insert keeps contiguous postgres placeholders for r2dbc"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.SharedSequenceAssetRepository', """
import io.micronaut.context.annotation.AliasFor;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.annotation.RepositoryConfiguration;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import io.micronaut.data.model.query.builder.sql.SqlQueryConfiguration;
import jakarta.persistence.JoinColumn;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@RepositoryConfiguration(queryBuilder = SqlQueryBuilder.class, implicitQueries = false, namedParameters = false)
@SqlQueryConfiguration(
    @SqlQueryConfiguration.DialectConfiguration(
        dialect = Dialect.POSTGRES,
        positionalParameterFormat = "\$%s"
    )
)
@Retention(RetentionPolicy.RUNTIME)
@Repository
@interface TestPostgresRepository {
    @AliasFor(annotation = Repository.class, member = "dialect")
    Dialect dialect() default Dialect.ANSI;
}

@TestPostgresRepository(dialect = Dialect.POSTGRES)
@io.micronaut.context.annotation.Executable
interface SharedSequenceAssetRepository extends CrudRepository<SharedSequenceAsset, Long> {
}

@MappedEntity("sequence_asset")
class SharedSequenceAsset {
    @Id
    @GeneratedValue(value = GeneratedValue.Type.SEQUENCE, ref = "sequence_asset_seq")
    private Long id;

    private String title;

    @Version
    private Long version;

    @Relation(value = Relation.Kind.ONE_TO_ONE, cascade = Relation.Cascade.NONE)
    @JoinColumn(name = "id", referencedColumnName = "id")
    private SharedSequenceAssetMetadata metadata;

    Long getId() {
        return id;
    }

    void setId(Long id) {
        this.id = id;
    }

    String getTitle() {
        return title;
    }

    void setTitle(String title) {
        this.title = title;
    }

    Long getVersion() {
        return version;
    }

    void setVersion(Long version) {
        this.version = version;
    }

    SharedSequenceAssetMetadata getMetadata() {
        return metadata;
    }

    void setMetadata(SharedSequenceAssetMetadata metadata) {
        this.metadata = metadata;
    }
}

@MappedEntity("sequence_assetmetadata")
class SharedSequenceAssetMetadata {
    @Id
    private Long id;

    private String author;

    Long getId() {
        return id;
    }

    void setId(Long id) {
        this.id = id;
    }

    String getAuthor() {
        return author;
    }

    void setAuthor(String author) {
        this.author = author;
    }
}
""")

        def method = beanDefinition.findPossibleMethods("save")
            .toList()
            .find { it.arguments.length == 1 && it.arguments[0].type.name == 'test.SharedSequenceAsset' }

        expect:
        method != null
        getQuery(method) == 'INSERT INTO "sequence_asset" ("title","id","version") VALUES ($1,nextval(\'sequence_asset_seq\'),$2)'
        getParameterPropertyPaths(method) == ["title", "version"] as String[]
    }

}
