/*
 * Copyright 2017-2020 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.data.processor.sql

import io.micronaut.data.intercept.InsertEntityInterceptor
import io.micronaut.data.intercept.UpdateAllEntitiesInterceptor
import io.micronaut.data.intercept.UpdateEntityInterceptor
import io.micronaut.data.intercept.async.UpdateAllEntriesAsyncInterceptor
import io.micronaut.data.intercept.async.UpdateEntityAsyncInterceptor
import io.micronaut.data.intercept.annotation.DataMethod
import io.micronaut.data.intercept.reactive.UpdateAllEntitiesReactiveInterceptor
import io.micronaut.data.intercept.reactive.UpdateEntityReactiveInterceptor
import io.micronaut.data.model.DataType
import io.micronaut.data.model.entities.Person
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder
import io.micronaut.data.processor.model.SourcePersistentEntity
import io.micronaut.data.processor.visitors.AbstractDataSpec
import io.micronaut.inject.BeanDefinition
import io.micronaut.inject.ast.ClassElement
import io.micronaut.inject.writer.BeanDefinitionVisitor
import spock.lang.PendingFeature
import spock.lang.Unroll

import static io.micronaut.data.processor.visitors.TestUtils.getDataInterceptor
import static io.micronaut.data.processor.visitors.TestUtils.getDataResultType
import static io.micronaut.data.processor.visitors.TestUtils.getDataTypes
import static io.micronaut.data.processor.visitors.TestUtils.getOperationType
import static io.micronaut.data.processor.visitors.TestUtils.getOutBindingParameters
import static io.micronaut.data.processor.visitors.TestUtils.getParameterPropertyPaths
import static io.micronaut.data.processor.visitors.TestUtils.getQuery
import static io.micronaut.data.processor.visitors.TestUtils.getRawQuery
import static io.micronaut.data.processor.visitors.TestUtils.getResultDataType

class BuildInsertSpec extends AbstractDataSpec {

    @Unroll
    void "test build create table for identity generation and dialect - #dialect"() {
        given:
        ClassElement element = buildClassElement("""
package test;
import io.micronaut.data.annotation.*;

class Test {
    @Id
    @GeneratedValue(GeneratedValue.Type.IDENTITY)
    private Long id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}

""")
        SqlQueryBuilder builder = new SqlQueryBuilder(dialect)
        def entity = new SourcePersistentEntity(element, {})
        def sql = builder.buildBatchCreateTableStatement(List.of(), entity)

        expect:
        sql == query

        where:
        dialect            | query
        Dialect.ORACLE     | 'CREATE TABLE "TEST" ("ID" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY (MINVALUE 1 START WITH 1 CACHE 100 NOCYCLE) PRIMARY KEY,"NAME" VARCHAR(255) NOT NULL)'
        Dialect.H2         | 'CREATE TABLE `test` (`id` BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,`name` VARCHAR(255) NOT NULL);'
        Dialect.POSTGRES   | 'CREATE TABLE "test" ("id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"name" VARCHAR(255) NOT NULL);'
        Dialect.SQL_SERVER | 'CREATE TABLE [test] ([id] BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,[name] VARCHAR(255) NOT NULL);'
        Dialect.MYSQL      | 'CREATE TABLE `test` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT,`name` VARCHAR(255) NOT NULL);'
    }

    @Unroll
    void "test build insert for identity generation and dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import java.util.UUID;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Version;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    Test save(String name);

    Test findById(Long id);
}

@MappedEntity
class Test {
    @Id
    @GeneratedValue(GeneratedValue.Type.IDENTITY)
    private Long id;
    private String name;
    @Version
    @GeneratedValue
    private Long version;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}

""")
        expect:
        getQuery(beanDefinition.getRequiredMethod("save", String)) == query

        where:
        dialect            | query
        Dialect.MYSQL      | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.ORACLE     | 'INSERT INTO "TEST" ("NAME") VALUES (?)'
        Dialect.H2         | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.POSTGRES   | 'INSERT INTO "test" ("name") VALUES (?)'
        Dialect.SQL_SERVER | 'INSERT INTO [test] ([name]) VALUES (?)'
    }

    @Unroll
    void "test build create table for UUID and dialect - #dialect"() {
        given:
        ClassElement element = buildClassElement("""
package test;
import java.util.UUID;
import io.micronaut.data.annotation.*;

class Test {
    @Id
    @GeneratedValue
    private UUID id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}

""")
        SqlQueryBuilder builder = new SqlQueryBuilder(dialect)
        def entity = new SourcePersistentEntity(element, {})
        def sql = builder.buildBatchCreateTableStatement(List.of(), entity)

        expect:
        sql == query

        where:
        dialect            | query
        Dialect.ORACLE     | 'CREATE TABLE "TEST" ("ID" VARCHAR(36) NOT NULL DEFAULT SYS_GUID() PRIMARY KEY,"NAME" VARCHAR(255) NOT NULL)'
        Dialect.H2         | 'CREATE TABLE `test` (`id` UUID NOT NULL DEFAULT random_uuid() PRIMARY KEY,`name` VARCHAR(255) NOT NULL);'
        Dialect.POSTGRES   | 'CREATE TABLE "test" ("id" UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),"name" VARCHAR(255) NOT NULL);'
        Dialect.SQL_SERVER | 'CREATE TABLE [test] ([id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),[name] VARCHAR(255) NOT NULL);'
        Dialect.MYSQL      | 'CREATE TABLE `test` (`id` VARCHAR(36) PRIMARY KEY NOT NULL,`name` VARCHAR(255) NOT NULL);'
    }

    @Unroll
    void "test build insert for UUID and dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import java.util.UUID;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, UUID> {
    Test save(String name);

    Test findById(UUID id);
}

@MappedEntity
class Test {
    @Id
    @GeneratedValue
    private UUID id;
    private String name;

    public Test(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}

""")
        expect:
        getQuery(beanDefinition.getRequiredMethod("save", String)) == query
        getDataTypes(beanDefinition.getRequiredMethod("findById", UUID)) == [DataType.UUID]

        where:
        dialect            | query
        Dialect.MYSQL      | 'INSERT INTO `test` (`name`,`id`) VALUES (?,?)'
        Dialect.ORACLE     | 'INSERT INTO "TEST" ("NAME") VALUES (?)'
        Dialect.H2         | 'INSERT INTO `test` (`name`) VALUES (?)'
        Dialect.POSTGRES   | 'INSERT INTO "test" ("name") VALUES (?)'
        Dialect.SQL_SERVER | 'INSERT INTO [test] ([name]) VALUES (?)'
    }

    void "test build SQL insert statement with custom name and escaping"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.annotation.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.DataType;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<TableRatings, Long> {
}

@MappedEntity(value = "T-Table-Ratings", escape = true)
class TableRatings {
    @Id
    @GeneratedValue
    private Long id;

    @MappedProperty(value = "T-Rating", type = DataType.INTEGER)
    private final int rating;

    public TableRatings(int rating) {
        this.rating = rating;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRating() {
        return rating;
    }
}

""")

        def method = beanDefinition.findPossibleMethods("save").findFirst().get()

        expect:
        getQuery(method) == 'INSERT INTO "T-Table-Ratings" ("T-Rating") VALUES (?)'
    }

    void "test build SQL insert statement"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.model.entities.Person;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<Person, Long> {
}
""")

        def method = beanDefinition.getRequiredMethod("save", Person)

        expect:
        getQuery(method) == 'INSERT INTO "person" ("name","age","enabled","public_id","company_id") VALUES (?,?,?,?,?)'
        getParameterPropertyPaths(method) == ['name', 'age', 'enabled', 'publicId', 'company.myId'] as String[]
    }

    @PendingFeature(reason = "Bug in Micronaut core. Fixed by https://github.com/micronaut-projects/micronaut-core/commit/f6a488677d587be309d5b0abd8925c9a098cfdf9")
    void "test build SQL insert statement for repo with no super interface"() {
        given:
        BeanDefinition beanDefinition = buildBeanDefinition('test.TestBookPageRepository' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.annotation.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
interface TestBookPageRepository extends io.micronaut.data.tck.repositories.BookPageRepository {

}
""")

        def method = beanDefinition.findPossibleMethods("save").findFirst().get()
        expect:

        getQuery(method) == 'INSERT INTO "shelf_book" ("shelf_id","book_id") VALUES (?,?)'
        getParameterPropertyPaths(method) == ['name', 'age', 'enabled', 'publicId'] as String[]
    }

    void "test build SQL update"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.tck.entities.Food;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import java.util.UUID;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends CrudRepository<Food, UUID> {
}
""")

        def method = beanDefinition.findPossibleMethods("update").findFirst().get()
        expect:

        getQuery(method) == 'UPDATE "food" SET "key"=?,"carbohydrates"=?,"portion_grams"=?,"updated_on"=?,"fk_meal_id"=?,"fk_alt_meal"=?,"loooooooooooooooooooooooooooooooooooooooooooooooooooooooong_name"=?,"fresh"=? WHERE ("fid" = ? AND fresh = \'Y\')'
        getParameterPropertyPaths(method) == ["key", "carbohydrates", "portionGrams", "updatedOn", "meal.mid", "alternativeMeal.mid", "longName", "fresh", "fid"] as String[]
    }

    void "test build custom SQL insert"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.tck.entities.Food;
import io.micronaut.data.tck.entities.Meal;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import io.micronaut.data.model.query.builder.sql.SqlQueryBuilder;
import java.util.UUID;

@Repository
@RepositoryConfiguration(queryBuilder=SqlQueryBuilder.class, implicitQueries = false)
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Food, UUID> {

    @Query("INSERT INTO food(key, carbohydrates) VALUES (:key, :carbohydrates)")
    void saveCustom(java.util.List<Food> food);

    @Query("INSERT INTO food(key, carbohydrates) VALUES (:key, :carbohydrates)")
    void saveCustomSingle(Food food);

    Food save(UUID fid, String key, int carbohydrates, Meal meal);

}
""")
        when:
        def saveCustom = beanDefinition.findPossibleMethods("saveCustom").findFirst().get()
        then:
        getRawQuery(saveCustom) == 'INSERT INTO food(key, carbohydrates) VALUES (?, ?)'
        getParameterPropertyPaths(saveCustom) == ["key", "carbohydrates"] as String[]
        when:
        def saveCustomSingle = beanDefinition.findPossibleMethods("saveCustomSingle").findFirst().get()
        then:
        getRawQuery(saveCustomSingle) == 'INSERT INTO food(key, carbohydrates) VALUES (?, ?)'
        getParameterPropertyPaths(saveCustomSingle) == ["key", "carbohydrates"] as String[]
        when:
        def save = beanDefinition.findPossibleMethods("save").findFirst().get()
        then:
        getQuery(save) == 'INSERT INTO "food" ("key","carbohydrates","portion_grams","created_on","updated_on","fk_meal_id","fk_alt_meal","loooooooooooooooooooooooooooooooooooooooooooooooooooooooong_name","fresh","fid") VALUES (?,?,?,?,?,?,?,?,?,?)'
        getDataInterceptor(save) == "io.micronaut.data.intercept.SaveOneInterceptor"
    }

    @Unroll
    void "test build upsert for dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import java.util.concurrent.CompletionStage;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    Test upsert(Test test);

    @Upsert
    Test put(Test test);

    @Upsert
    java.util.List<Test> putAll(java.util.List<Test> tests);

    @Upsert
    CompletionStage<Test> putAsync(Test test);

    @Upsert
    CompletionStage<java.util.List<Test>> putAllAsync(java.util.List<Test> tests);

    @Upsert
    Mono<Test> putReactive(Test test);

    @Upsert
    Flux<Test> putAllReactive(java.util.List<Test> tests);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    private Long id;
    private String name;
    private Integer pages;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }
}
""")

        when:
        def upsertMethod = beanDefinition.findPossibleMethods("upsert").findFirst().get()
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()
        def putAllMethod = beanDefinition.findPossibleMethods("putAll").findFirst().get()
        def putAsyncMethod = beanDefinition.findPossibleMethods("putAsync").findFirst().get()
        def putAllAsyncMethod = beanDefinition.findPossibleMethods("putAllAsync").findFirst().get()
        def putReactiveMethod = beanDefinition.findPossibleMethods("putReactive").findFirst().get()
        def putAllReactiveMethod = beanDefinition.findPossibleMethods("putAllReactive").findFirst().get()

        then:
        getOperationType(upsertMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(upsertMethod) == UpdateEntityInterceptor.name
        getQuery(upsertMethod) == query
        getParameterPropertyPaths(upsertMethod) == parameterPropertyPaths as String[]
        getOperationType(putMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putMethod) == UpdateEntityInterceptor.name
        getQuery(putMethod) == query
        getParameterPropertyPaths(putMethod) == parameterPropertyPaths as String[]
        getOperationType(putAllMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAllMethod) == UpdateAllEntitiesInterceptor.name
        getQuery(putAllMethod) == query
        getParameterPropertyPaths(putAllMethod) == parameterPropertyPaths as String[]
        getOperationType(putAsyncMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAsyncMethod) == UpdateEntityAsyncInterceptor.name
        getQuery(putAsyncMethod) == query
        getParameterPropertyPaths(putAsyncMethod) == parameterPropertyPaths as String[]
        getOperationType(putAllAsyncMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAllAsyncMethod) == UpdateAllEntriesAsyncInterceptor.name
        getQuery(putAllAsyncMethod) == query
        getParameterPropertyPaths(putAllAsyncMethod) == parameterPropertyPaths as String[]
        getOperationType(putReactiveMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putReactiveMethod) == UpdateEntityReactiveInterceptor.name
        getQuery(putReactiveMethod) == query
        getParameterPropertyPaths(putReactiveMethod) == parameterPropertyPaths as String[]
        getOperationType(putAllReactiveMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAllReactiveMethod) == UpdateAllEntitiesReactiveInterceptor.name
        getQuery(putAllReactiveMethod) == query
        getParameterPropertyPaths(putAllReactiveMethod) == parameterPropertyPaths as String[]

        where:
        dialect            | query                                                                                                                                                                                                                                                                                              | parameterPropertyPaths
        Dialect.ANSI       | 'MERGE INTO "upsert_test" target USING (VALUES (?,?,?)) source (c0,c1,c2) ON (target."id"=source.c2) WHEN MATCHED THEN UPDATE SET target."name"=source.c0,target."pages"=source.c1 WHEN NOT MATCHED THEN INSERT ("name","pages","id") VALUES (source.c0,source.c1,source.c2)'                      | ["name", "pages", "id"]
        Dialect.H2         | 'MERGE INTO `upsert_test` (`name`,`pages`,`id`) KEY(`id`) VALUES (?,?,?)'                                                                                                                                                                                                                          | ["name", "pages", "id"]
        Dialect.MYSQL      | 'INSERT INTO `upsert_test` (`name`,`pages`,`id`) VALUES (?,?,?) ON DUPLICATE KEY UPDATE `name`=?,`pages`=?'                                                                                                                                                                                        | ["name", "pages", "id", "name", "pages"]
        Dialect.ORACLE     | 'MERGE INTO "UPSERT_TEST" target USING (SELECT ? c0,? c1,? c2 FROM DUAL) source ON (target."ID"=source.c2) WHEN MATCHED THEN UPDATE SET target."NAME"=source.c0,target."PAGES"=source.c1 WHEN NOT MATCHED THEN INSERT ("NAME","PAGES","ID") VALUES (source.c0,source.c1,source.c2)'                | ["name", "pages", "id"]
        Dialect.POSTGRES   | 'INSERT INTO "upsert_test" ("name","pages","id") VALUES (?,?,?) ON CONFLICT ("id") DO UPDATE SET "name"=EXCLUDED."name","pages"=EXCLUDED."pages"'                                                                                                                                                  | ["name", "pages", "id"]
        Dialect.SQL_SERVER | 'MERGE INTO [upsert_test] WITH (HOLDLOCK) AS target USING (VALUES (?,?,?)) AS source (c0,c1,c2) ON target.[id]=source.c2 WHEN MATCHED THEN UPDATE SET target.[name]=source.c0,target.[pages]=source.c1 WHEN NOT MATCHED THEN INSERT ([name],[pages],[id]) VALUES (source.c0,source.c1,source.c2);' | ["name", "pages", "id"]
    }

    @Unroll
    void "test build upsert with conflict properties for dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import java.util.List;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    @Upsert(conflictProperties = "name")
    Test put(Test test);

    @Upsert(conflictProperties = "name")
    List<Test> putAll(List<Test> tests);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    private Long id;
    private String name;
    private Integer pages;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }
}
""")

        when:
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()

        then:
        getOperationType(putMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putMethod) == UpdateEntityInterceptor.name
        getQuery(putMethod) == query
        getParameterPropertyPaths(putMethod) == parameterPropertyPaths as String[]

        where:
        dialect            | query                                                                                                                                                                                                                                                                        | parameterPropertyPaths
        Dialect.ANSI       | 'MERGE INTO "upsert_test" target USING (VALUES (?,?,?)) source (c0,c1,c2) ON (target."name"=source.c0) WHEN MATCHED THEN UPDATE SET target."pages"=source.c1 WHEN NOT MATCHED THEN INSERT ("name","pages","id") VALUES (source.c0,source.c1,source.c2)'                      | ["name", "pages", "id"]
        Dialect.H2         | 'MERGE INTO `upsert_test` (`name`,`pages`,`id`) KEY(`name`) VALUES (?,?,?)'                                                                                                                                                                                                  | ["name", "pages", "id"]
        Dialect.MYSQL      | 'INSERT INTO `upsert_test` (`name`,`pages`,`id`) VALUES (?,?,?) ON DUPLICATE KEY UPDATE `pages`=?'                                                                                                                                                                           | ["name", "pages", "id", "pages"]
        Dialect.ORACLE     | 'MERGE INTO "UPSERT_TEST" target USING (SELECT ? c0,? c1,? c2 FROM DUAL) source ON (target."NAME"=source.c0) WHEN MATCHED THEN UPDATE SET target."PAGES"=source.c1 WHEN NOT MATCHED THEN INSERT ("NAME","PAGES","ID") VALUES (source.c0,source.c1,source.c2)'                | ["name", "pages", "id"]
        Dialect.POSTGRES   | 'INSERT INTO "upsert_test" ("name","pages","id") VALUES (?,?,?) ON CONFLICT ("name") DO UPDATE SET "pages"=EXCLUDED."pages"'                                                                                                                                                 | ["name", "pages", "id"]
        Dialect.SQL_SERVER | 'MERGE INTO [upsert_test] WITH (HOLDLOCK) AS target USING (VALUES (?,?,?)) AS source (c0,c1,c2) ON target.[name]=source.c0 WHEN MATCHED THEN UPDATE SET target.[pages]=source.c1 WHEN NOT MATCHED THEN INSERT ([name],[pages],[id]) VALUES (source.c0,source.c1,source.c2);' | ["name", "pages", "id"]
    }

    @Unroll
    void "test build upsert with generated identity and conflict properties for dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import java.util.List;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    @Upsert(conflictProperties = "name")
    Test put(Test test);

    @Upsert(conflictProperties = "name")
    List<Test> putAll(List<Test> tests);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    @GeneratedValue
    private Long id;
    private String name;
    private Integer pages;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }
}
""")

        when:
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()
        def outBindingParameters = getOutBindingParameters(putMethod)
        def putAllMethod = beanDefinition.findPossibleMethods("putAll").findFirst().get()
        def putAllOutBindingParameters = getOutBindingParameters(putAllMethod)

        then:
        getOperationType(putMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putMethod) == UpdateEntityInterceptor.name
        getQuery(putMethod) == query
        getParameterPropertyPaths(putMethod) == parameterPropertyPaths as String[]
        outBindingParameters.length == outBindingParameterNames.size()
        outBindingParameters*.name == outBindingParameterNames
        outBindingParameters*.dataType == outBindingParameterDataTypes
        getOperationType(putAllMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAllMethod) == UpdateAllEntitiesInterceptor.name
        getQuery(putAllMethod) == query
        getParameterPropertyPaths(putAllMethod) == parameterPropertyPaths as String[]
        putAllOutBindingParameters.length == outBindingParameterNames.size()
        putAllOutBindingParameters*.name == outBindingParameterNames
        putAllOutBindingParameters*.dataType == outBindingParameterDataTypes

        where:
        dialect            | query                                                                                                                                                                                                                                                                                          | parameterPropertyPaths     | outBindingParameterNames | outBindingParameterDataTypes
        Dialect.ANSI       | 'MERGE INTO "upsert_test" target USING (VALUES (?,?)) source (c0,c1) ON (target."name"=source.c0) WHEN MATCHED THEN UPDATE SET target."pages"=source.c1 WHEN NOT MATCHED THEN INSERT ("name","pages") VALUES (source.c0,source.c1)'                                                            | ["name", "pages"]          | []                       | []
        Dialect.H2         | 'MERGE INTO `upsert_test` (`name`,`pages`) KEY(`name`) VALUES (?,?)'                                                                                                                                                                                                                           | ["name", "pages"]          | []                       | []
        Dialect.MYSQL      | 'INSERT INTO `upsert_test` (`name`,`pages`) VALUES (?,?) ON DUPLICATE KEY UPDATE `pages`=?'                                                                                                                                                                                                    | ["name", "pages", "pages"] | []                       | []
        Dialect.ORACLE     | 'MERGE INTO "UPSERT_TEST" target USING (SELECT ? c0,? c1 FROM DUAL) source ON (target."NAME"=source.c0) WHEN MATCHED THEN UPDATE SET target."PAGES"=source.c1 WHEN NOT MATCHED THEN INSERT ("NAME","PAGES","ID") VALUES (source.c0,source.c1,"UPSERT_TEST_SEQ".nextval) RETURNING "ID" INTO ?' | ["name", "pages"]          | ["id"]                   | [DataType.LONG]
        Dialect.POSTGRES   | 'INSERT INTO "upsert_test" ("name","pages") VALUES (?,?) ON CONFLICT ("name") DO UPDATE SET "pages"=EXCLUDED."pages"'                                                                                                                                                                          | ["name", "pages"]          | []                       | []
        Dialect.SQL_SERVER | 'MERGE INTO [upsert_test] WITH (HOLDLOCK) AS target USING (VALUES (?,?)) AS source (c0,c1) ON target.[name]=source.c0 WHEN MATCHED THEN UPDATE SET target.[pages]=source.c1 WHEN NOT MATCHED THEN INSERT ([name],[pages]) VALUES (source.c0,source.c1) OUTPUT inserted.[id];'                  | ["name", "pages"]          | ["id"]                   | [DataType.LONG]
    }

    @Unroll
    void "test build Oracle upsert with generated #generationType identity and conflict properties"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import java.util.List;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@JdbcRepository(dialect=Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    @Upsert(conflictProperties = "name")
    Test put(Test test);

    @Upsert(conflictProperties = "name")
    Mono<Test> putMono(Test test);

    @Upsert(conflictProperties = "name")
    Flux<Test> putFlux(List<Test> tests);

    @Upsert(conflictProperties = "name")
    void putNoResult(Test test);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    @GeneratedValue(value = GeneratedValue.Type.${generationType})
    private Long id;
    private String name;
    private Integer pages;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }
}
""")

        when:
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()
        def putMonoMethod = beanDefinition.findPossibleMethods("putMono").findFirst().get()
        def putFluxMethod = beanDefinition.findPossibleMethods("putFlux").findFirst().get()
        def putNoResultMethod = beanDefinition.findPossibleMethods("putNoResult").findFirst().get()

        then:
        [putMethod, putMonoMethod, putFluxMethod, putNoResultMethod].each { method ->
            assert getQuery(method) == 'MERGE INTO "UPSERT_TEST" target USING (SELECT ? c0,? c1 FROM DUAL) source ON (target."NAME"=source.c0) WHEN MATCHED THEN UPDATE SET target."PAGES"=source.c1 WHEN NOT MATCHED THEN INSERT ("NAME","PAGES","ID") VALUES (source.c0,source.c1,"UPSERT_TEST_SEQ".nextval) RETURNING "ID" INTO ?'
            assert getParameterPropertyPaths(method) == ["name", "pages"] as String[]
            assert getOutBindingParameters(method)*.name == ["id"]
        }

        where:
        generationType << ["AUTO", "SEQUENCE"]
    }

    @Unroll
    void "test build upsert with multiple conflict properties for dialect - #dialect"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;

@JdbcRepository(dialect=Dialect.${dialect.name()})
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    @Upsert(conflictProperties = {"name", "pages"})
    Test put(Test test);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    private Long id;
    private String name;
    private Integer pages;
    private String description;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
""")

        when:
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()

        then:
        getOperationType(putMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putMethod) == UpdateEntityInterceptor.name
        getQuery(putMethod) == query
        getParameterPropertyPaths(putMethod) == parameterPropertyPaths as String[]

        where:
        dialect            | query                                                                                                                                                                                                                                                                                                                                        | parameterPropertyPaths
        Dialect.ANSI       | 'MERGE INTO "upsert_test" target USING (VALUES (?,?,?,?)) source (c0,c1,c2,c3) ON (target."name"=source.c0 AND target."pages"=source.c1) WHEN MATCHED THEN UPDATE SET target."description"=source.c2 WHEN NOT MATCHED THEN INSERT ("name","pages","description","id") VALUES (source.c0,source.c1,source.c2,source.c3)'                      | ["name", "pages", "description", "id"]
        Dialect.H2         | 'MERGE INTO `upsert_test` (`name`,`pages`,`description`,`id`) KEY(`name`,`pages`) VALUES (?,?,?,?)'                                                                                                                                                                                                                                          | ["name", "pages", "description", "id"]
        Dialect.MYSQL      | 'INSERT INTO `upsert_test` (`name`,`pages`,`description`,`id`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `description`=?'                                                                                                                                                                                                                     | ["name", "pages", "description", "id", "description"]
        Dialect.ORACLE     | 'MERGE INTO "UPSERT_TEST" target USING (SELECT ? c0,? c1,? c2,? c3 FROM DUAL) source ON (target."NAME"=source.c0 AND target."PAGES"=source.c1) WHEN MATCHED THEN UPDATE SET target."DESCRIPTION"=source.c2 WHEN NOT MATCHED THEN INSERT ("NAME","PAGES","DESCRIPTION","ID") VALUES (source.c0,source.c1,source.c2,source.c3)'                | ["name", "pages", "description", "id"]
        Dialect.POSTGRES   | 'INSERT INTO "upsert_test" ("name","pages","description","id") VALUES (?,?,?,?) ON CONFLICT ("name","pages") DO UPDATE SET "description"=EXCLUDED."description"'                                                                                                                                                                             | ["name", "pages", "description", "id"]
        Dialect.SQL_SERVER | 'MERGE INTO [upsert_test] WITH (HOLDLOCK) AS target USING (VALUES (?,?,?,?)) AS source (c0,c1,c2,c3) ON target.[name]=source.c0 AND target.[pages]=source.c1 WHEN MATCHED THEN UPDATE SET target.[description]=source.c2 WHEN NOT MATCHED THEN INSERT ([name],[pages],[description],[id]) VALUES (source.c0,source.c1,source.c2,source.c3);' | ["name", "pages", "description", "id"]
    }

    void "test annotated upsert on repository without base interface"() {
        given:
        BeanDefinition beanDefinition = buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import java.util.List;

@JdbcRepository(dialect=Dialect.H2)
@io.micronaut.context.annotation.Executable
interface MyInterface {
    @Upsert
    Test put(Test test);

    @Upsert
    List<Test> putAll(List<Test> tests);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
""")

        when:
        def putMethod = beanDefinition.findPossibleMethods("put").findFirst().get()
        def putAllMethod = beanDefinition.findPossibleMethods("putAll").findFirst().get()

        then:
        getOperationType(putMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putMethod) == UpdateEntityInterceptor.name
        getQuery(putMethod) == 'MERGE INTO `upsert_test` (`name`,`id`) KEY(`id`) VALUES (?,?)'
        getParameterPropertyPaths(putMethod) == ["name", "id"] as String[]
        getOperationType(putAllMethod) == DataMethod.OperationType.UPSERT
        getDataInterceptor(putAllMethod) == UpdateAllEntitiesInterceptor.name
        getQuery(putAllMethod) == 'MERGE INTO `upsert_test` (`name`,`id`) KEY(`id`) VALUES (?,?)'
        getParameterPropertyPaths(putAllMethod) == ["name", "id"] as String[]
    }

    @Unroll
    void "test build upsert fails for unsupported explicit upsert - #description"() {
        when:
        buildRepository('test.MyInterface', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;

@JdbcRepository(dialect=Dialect.H2)
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    ${methodRepresentation}
    Test upsert(Test test);
}

${entityRepresentation}
@MappedEntity("upsert_test")
class Test {
    ${idAnnotation}
    private Long id;
    private String name;
    ${versionAnnotation}
    private Long version;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}
""")

        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("Cannot implement explicit upsert query: ${message}")

        where:
        description                  | methodRepresentation                                                                                                | entityRepresentation                                                                                                | idAnnotation               | versionAnnotation | message
        "method JSON representation" | "@EntityRepresentation(type = EntityRepresentation.Type.COLUMN, columnType = EntityRepresentation.ColumnType.JSON)" | ""                                                                                                                  | "@Id"                      | ""                | "JSON entity representation is not supported"
        "entity JSON representation" | ""                                                                                                                  | "@EntityRepresentation(type = EntityRepresentation.Type.COLUMN, columnType = EntityRepresentation.ColumnType.JSON)" | "@Id"                      | ""                | "JSON entity representation is not supported"
        "missing identity"           | ""                                                                                                                  | ""                                                                                                                  | ""                         | ""                | "entity does not define an identity"
        "versioned entity"           | ""                                                                                                                  | ""                                                                                                                  | "@Id"                      | "@Version"        | "versioned entities are not supported"
        "generated identity"         | ""                                                                                                                  | ""                                                                                                                  | "@Id\n    @GeneratedValue" | ""                | "generated identity properties are not supported"
        "blank conflict property"    | "@Upsert(conflictProperties = \"\")"                                                                                | ""                                                                                                                  | "@Id"                      | ""                | "conflict property cannot be blank"
        "unknown conflict property"  | "@Upsert(conflictProperties = \"missing\")"                                                                         | ""                                                                                                                  | "@Id"                      | ""                | "conflict property does not exist: missing"
    }

    void "test build upsert fails with both entity and iterable entity parameters"() {
        when:
        buildRepository('test.MyInterface', """
import io.micronaut.data.annotation.*;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import java.util.List;

@JdbcRepository(dialect=Dialect.H2)
@io.micronaut.context.annotation.Executable
interface MyInterface extends GenericRepository<Test, Long> {
    @Upsert
    List<Test> put(Test test, List<Test> tests);
}

@MappedEntity("upsert_test")
class Test {
    @Id
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
""")

        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("Cannot implement upsert method with both entity and iterable entity parameters")
    }

    void "POSTGRES test build save returning "() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.tck.entities.Author;

@JdbcRepository(dialect= Dialect.POSTGRES)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {

    Book saveReturning(Book book);

}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO "book" ("author_id","genre_id","title","total_pages","publisher_id","last_updated") VALUES (?,?,?,?,?,?) RETURNING "author_id","genre_id","title","total_pages","publisher_id","last_updated","id"'
            getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
            getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
            getResultDataType(saveReturningMethod) == DataType.ENTITY
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
    }

    void "POSTGRES test build save all"() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.tck.entities.Author;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.POSTGRES)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {

    List<Book> saveReturning(List<Book> books);

}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO "book" ("author_id","genre_id","title","total_pages","publisher_id","last_updated") VALUES (?,?,?,?,?,?) RETURNING "author_id","genre_id","title","total_pages","publisher_id","last_updated","id"'
            getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
            getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveAllInterceptor"
            getResultDataType(saveReturningMethod) == DataType.ENTITY
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
    }

    void "test build custom SQL insert - expressions"() {
        given:
            BeanDefinition beanDefinition = buildBeanDefinition('test.MyInterface' + BeanDefinitionVisitor.PROXY_SUFFIX, """
package test;

import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.*;
import io.micronaut.data.repository.*;
import java.util.UUID;

@JdbcRepository(dialect = Dialect.ANSI)
interface MyInterface extends GenericRepository<Book, UUID> {

    @Query("INSERT INTO Book(title, totalPages) VALUES (:title, :totalPages)")
    @ParameterExpression(name = "title", expression = "#{book.title}")
    @ParameterExpression(name = "totalPages", expression = "#{book.totalPages}")
    void saveCustom(Book book);

}
""")
        when:
            def saveCustom = beanDefinition.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getRawQuery(saveCustom) == 'INSERT INTO Book(title, totalPages) VALUES (?, ?)'
            getDataTypes(saveCustom) == [DataType.STRING, DataType.INTEGER]
            getParameterPropertyPaths(saveCustom) == ["title", "totalPages"] as String[]
            getDataInterceptor(saveCustom) == "io.micronaut.data.intercept.InsertEntityInterceptor"
    }

    void "test custom insert save all - JPA"() {
        given:
            def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Person;

@Repository
interface PersonRepository extends GenericRepository<Person, Long> {

    @Query("INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)")
    int saveCustom(List<Person> people);
}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)'
            getDataResultType(saveReturningMethod) == "int"
            getParameterPropertyPaths(saveReturningMethod) == ["name", "age"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.InsertAllInterceptor"
            getResultDataType(saveReturningMethod) == DataType.INTEGER
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT
    }

    void "test custom insert save one - JPA"() {
        given:
            def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Person;

@Repository
interface PersonRepository extends GenericRepository<Person, Long> {

    @Query("INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)")
    int saveCustom(Person person);
}
""")
        when:
            def saveReturningMethod = repository.findPossibleMethods("saveCustom").findFirst().get()
        then:
            getQuery(saveReturningMethod) == 'INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE)'
            getDataResultType(saveReturningMethod) == "int"
            getParameterPropertyPaths(saveReturningMethod) == ["name", "age"] as String[]
            getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.InsertEntityInterceptor"
            getResultDataType(saveReturningMethod) == DataType.INTEGER
            getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT
    }

    void "POSTGRES save with tenant id"() {
        given:
            def repository = buildRepository('test.AccountRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.CrudRepository;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Account;

@JdbcRepository(dialect= Dialect.POSTGRES)
interface AccountRepository extends CrudRepository<Account, Long> {
}
""")
        when:
            def saveMethod = repository.findPossibleMethods("save").findFirst().get()
        then:
            getQuery(saveMethod) == 'INSERT INTO "account" ("name","tenancy") VALUES (?,?)'
            getDataResultType(saveMethod) == "io.micronaut.data.tck.entities.Account"
            getParameterPropertyPaths(saveMethod) == ["name", "tenancy"] as String[]
            getDataInterceptor(saveMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
            getResultDataType(saveMethod) == DataType.ENTITY
            getOperationType(saveMethod) == DataMethod.OperationType.INSERT
    }

    @Unroll
    void "test build insert with CTE"() {
        given:
        def repository = buildRepository('test.PersonRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.tck.entities.Person;

@JdbcRepository(dialect= Dialect.MYSQL)
@io.micronaut.context.annotation.Executable
interface PersonRepository extends CrudRepository<Person, Long> {

    @Query(\"""
            WITH ids AS (SELECT id FROM person)
            INSERT INTO person(name, age, enabled)
            VALUES (:name, :age, TRUE)
            \""")
    void customInsert(Person person);

}
""")
        def method = repository.findPossibleMethods("customInsert").findFirst().get()
        def insertQuery = getQuery(method)

        expect:
        insertQuery.replace('\n', ' ') == "WITH ids AS (SELECT id FROM person) INSERT INTO person(name, age, enabled) VALUES (:name, :age, TRUE) "
        method.classValue(DataMethod, "interceptor").get() == InsertEntityInterceptor
    }

    void "ORACLE test build save returning"() {
        given:
            def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    Book saveReturning(Book book);
}
""")
        when:
        def saveReturningMethod = repository.findPossibleMethods("saveReturning").findFirst().get()
        def outBindingParameters = getOutBindingParameters(saveReturningMethod)
        then:
        getQuery(saveReturningMethod) == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?; END;'
        getDataResultType(saveReturningMethod) == "io.micronaut.data.tck.entities.Book"
        getParameterPropertyPaths(saveReturningMethod) == ["author.id", "genre.id", "title", "totalPages", "publisher.id", "lastUpdated"] as String[]
        getDataInterceptor(saveReturningMethod) == "io.micronaut.data.intercept.SaveEntityInterceptor"
        getResultDataType(saveReturningMethod) == DataType.ENTITY
        getOperationType(saveReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 7
        outBindingParameters[0].name == "author_id"
        outBindingParameters[0].dataType == DataType.LONG
        outBindingParameters[1].name == "genre_id"
        outBindingParameters[1].dataType == DataType.LONG
        outBindingParameters[2].name == "title"
        outBindingParameters[2].dataType == DataType.STRING
        outBindingParameters[3].name == "total_pages"
        outBindingParameters[3].dataType == DataType.INTEGER
        outBindingParameters[4].name == "publisher_id"
        outBindingParameters[4].dataType == DataType.LONG
        outBindingParameters[5].name == "last_updated"
        outBindingParameters[5].dataType == DataType.TIMESTAMP
        outBindingParameters[6].name == "id"
        outBindingParameters[6].dataType == DataType.LONG
    }

    void "ORACLE custom @Query insert returning multiple columns should fail for scalar return"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query("INSERT INTO book (author_id,genre_id,title,total_pages,publisher_id,last_updated) VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated) RETURNING id, title INTO ?, ?")
    String brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, java.time.LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("multiple columns require an entity return type")
    }

    void "ORACLE custom @Query insert returning with explicit INTO produces valid SQL"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?
        \""")
    Book customInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);

    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE" INTO ?
        \""")
    String customInsertReturningTitle(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def customInsertReturningMethod = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        def outBindingEntityParameters = getOutBindingParameters(customInsertReturningMethod)
        def customInsertReturningTitleMethod = repository.findPossibleMethods("customInsertReturningTitle").findFirst().get()
        def outBindingTitleParameters = getOutBindingParameters(customInsertReturningTitleMethod)
        then:
        getRawQuery(customInsertReturningMethod).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,? ; END;'
        getDataResultType(customInsertReturningMethod) == "io.micronaut.data.tck.entities.Book"
        getDataInterceptor(customInsertReturningMethod) == "io.micronaut.data.intercept.InsertReturningOneInterceptor"
        getResultDataType(customInsertReturningMethod) == DataType.ENTITY
        getOperationType(customInsertReturningMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingEntityParameters.length == 7
        outBindingEntityParameters[0].name == "author_id"
        outBindingEntityParameters[0].dataType == DataType.LONG
        outBindingEntityParameters[1].name == "genre_id"
        outBindingEntityParameters[1].dataType == DataType.LONG
        outBindingEntityParameters[2].name == "title"
        outBindingEntityParameters[2].dataType == DataType.STRING
        outBindingEntityParameters[3].name == "total_pages"
        outBindingEntityParameters[3].dataType == DataType.INTEGER
        outBindingEntityParameters[4].name == "publisher_id"
        outBindingEntityParameters[4].dataType == DataType.LONG
        outBindingEntityParameters[5].name == "last_updated"
        outBindingEntityParameters[5].dataType == DataType.TIMESTAMP
        outBindingEntityParameters[6].name == "id"
        outBindingEntityParameters[6].dataType == DataType.LONG

        getRawQuery(customInsertReturningTitleMethod).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "TITLE" INTO ? ; END;'
        outBindingTitleParameters[0].name == "title"
        outBindingTitleParameters[0].dataType == DataType.STRING
        getDataResultType(customInsertReturningTitleMethod) == "java.lang.String"
        getDataInterceptor(customInsertReturningTitleMethod) == "io.micronaut.data.intercept.InsertReturningOneInterceptor"
        getOperationType(customInsertReturningTitleMethod) == DataMethod.OperationType.INSERT_RETURNING
        outBindingTitleParameters.length == 1
    }

    void "ORACLE custom @Query insert returning Restaurant validates embedded out bindings"() {
        given:
        def repository = buildRepository('test.RestaurantRepository', '''
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Restaurant;
import io.micronaut.data.annotation.Query;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface RestaurantRepository extends GenericRepository<Restaurant, Long> {
    @Query("""
        INSERT INTO "RESTAURANT" ("NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code")
        VALUES (:name,:addressStreet,:addressZipCode,:hqAddressStreet,:hqAddressZipCode)
        RETURNING "NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code","ID" INTO ?,?,?,?,?,?
        """)
    Restaurant customInsertReturning(String name, String addressStreet, String addressZipCode, String hqAddressStreet, String hqAddressZipCode);
}
''')
        when:
        def method = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        def outBindingParameters = getOutBindingParameters(method)
        then:
        getRawQuery(method).replace('\n', ' ') == 'BEGIN INSERT INTO "RESTAURANT" ("NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code") VALUES (?,?,?,?,?) RETURNING "NAME","address_street","address_zip_code","hqaddress_street","hqaddress_zip_code","ID" INTO ?,?,?,?,?,? ; END;'
        getDataResultType(method) == "io.micronaut.data.tck.entities.Restaurant"
        getResultDataType(method) == DataType.ENTITY
        getOperationType(method) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 6
        outBindingParameters[0].name == "name"
        outBindingParameters[0].dataType == DataType.STRING
        outBindingParameters[1].name == "address_street"
        outBindingParameters[1].dataType == DataType.STRING
        outBindingParameters[2].name == "address_zip_code"
        outBindingParameters[2].dataType == DataType.STRING
        outBindingParameters[3].name == "hqaddress_street"
        outBindingParameters[3].dataType == DataType.STRING
        outBindingParameters[4].name == "hqaddress_zip_code"
        outBindingParameters[4].dataType == DataType.STRING
        outBindingParameters[5].name == "id"
        outBindingParameters[5].dataType == DataType.LONG
    }

    void "ORACLE custom @Query insert returning preserves existing BEGIN END block"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        BEGIN
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?;
        END;
        \""")
    Book customInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def method = repository.findPossibleMethods("customInsertReturning").findFirst().get()
        then:
        getRawQuery(method).replace('\n', ' ') == 'BEGIN INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED") VALUES (?,?,?,?,?,?) RETURNING "AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED","ID" INTO ?,?,?,?,?,?,?; END; '
    }

    void "ORACLE raw @Query insert returning ignores quoted returning text after clause in block"() {
        given:
        def repository = buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        BEGIN
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE" INTO ?;
        DBMS_OUTPUT.PUT_LINE('ignored returning into ?');
        END;
        \""")
    String customInsertReturningTitle(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        when:
        def method = repository.findPossibleMethods("customInsertReturningTitle").findFirst().get()
        def outBindingParameters = getOutBindingParameters(method)
        then:
        getRawQuery(method).replace('\n', ' ') == "BEGIN INSERT INTO \"BOOK\" (\"AUTHOR_ID\",\"GENRE_ID\",\"TITLE\",\"TOTAL_PAGES\",\"PUBLISHER_ID\",\"LAST_UPDATED\") VALUES (?,?,?,?,?,?) RETURNING \"TITLE\" INTO ?; DBMS_OUTPUT.PUT_LINE('ignored returning into ?'); END; "
        getOperationType(method) == DataMethod.OperationType.INSERT_RETURNING
        outBindingParameters.length == 1
        outBindingParameters[0].name == "title"
        outBindingParameters[0].dataType == DataType.STRING
    }

    void "ORACLE raw @Query insert returning without INTO is rejected"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING "TITLE"
        \""")
    String brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("must declare explicit returned columns and an INTO clause")
    }

    void "ORACLE raw @Query insert returning star is rejected"() {
        when:
        buildRepository('test.BookRepository', """
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.GenericRepository;
import io.micronaut.data.tck.entities.Book;
import io.micronaut.data.annotation.Query;
import java.time.LocalDateTime;

@JdbcRepository(dialect= Dialect.ORACLE)
@io.micronaut.context.annotation.Executable
interface BookRepository extends GenericRepository<Book, Long> {
    @Query(\"""
        INSERT INTO "BOOK" ("AUTHOR_ID","GENRE_ID","TITLE","TOTAL_PAGES","PUBLISHER_ID","LAST_UPDATED")
        VALUES (:authorId,:genreId,:title,:totalPages,:publisherId,:lastUpdated)
        RETURNING * INTO ?
        \""")
    Book brokenInsertReturning(Long authorId, Long genreId, String title, int totalPages, Long publisherId, LocalDateTime lastUpdated);
}
""")
        then:
        def ex = thrown(RuntimeException)
        ex.message.contains("must declare explicit returned columns instead of RETURNING *")
    }

}
