plugins {
    id "io.micronaut.build.internal.data-module"
    id "groovy"
}

dependencies {
    annotationProcessor projects.micronautDataDocumentProcessor
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor mn.micronaut.graal
    annotationProcessor libs.micronaut.docs

    api projects.micronautDataRuntime
    api projects.micronautDataDocumentModel
    api projects.micronautDataConnection

    api libs.nitrite
    api libs.nitrite.mvstore.adapter
    api libs.nitrite.jackson.mapper
    api libs.jackson.datatype.jsr310
    api libs.jakarta.persistence.api

    compileOnly mn.micronaut.inject.groovy

    testAnnotationProcessor projects.micronautDataDocumentProcessor
    testAnnotationProcessor projects.micronautDataNitrite
    testAnnotationProcessor mn.micronaut.inject.java
    testAnnotationProcessor mnTest.micronaut.test.spock

    testImplementation project(':micronaut-data-document-tck')
    testImplementation project(':micronaut-data-tck')
    testImplementation project(':micronaut-data-runtime')
    testImplementation mn.micronaut.inject.groovy
    testImplementation mnTest.micronaut.test.spock
    testImplementation libs.spock.core
}

test {
    useJUnitPlatform()
}

// Disable baseline check for new module until first release
tasks.named("findBaseline").configure {
    enabled = false
}
