/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.data.model.schema;

import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.exceptions.MappingException;
import io.micronaut.data.model.DataType;
import io.micronaut.data.model.JsonDataType;
import io.micronaut.data.model.query.builder.sql.Dialect;


/**
 * Represents a database column from mapped entity persistent field.
 *
 * @author radovanradic
 * @since 4.13.0
 */
@Internal
public final class Column {

    private static final String NUMERIC_TYPE = "NUMERIC";
    private static final String NUMBER_TYPE = "NUMBER";

    private final String name;
    private final DataType dataType;
    private final int dbTypeCode;
    private final boolean primaryKey;
    private final @Nullable Integer length;
    private final @Nullable Integer precision;
    private final @Nullable Integer scale;
    private final boolean required;
    private final boolean autoGenerated;
    private final @Nullable GeneratedValue.Type generatedValueType;
    private final @Nullable String definition;
    private final @Nullable JsonDataType jsonDataType;
    private String sqlType;

    /**
     * Constructs a new Column instance.
     *
     * @param name              the name of the column
     * @param dataType          the data type of the column
     * @param dbTypeCode        the database-specific type code
     * @param primaryKey        whether the column is a primary key
     * @param length            the length of the column (optional)
     * @param precision         the precision of the column (optional)
     * @param scale             the scale of the column (optional)
     * @param required          whether the column is required
     * @param autoGenerated     whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition        the definition of the column (optional)
     * @param jsonDataType      the JSON data type (optional)
     */
    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, Integer length, Integer precision, Integer scale,
                  boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition, JsonDataType jsonDataType) {
        this.name = name;
        this.dataType = dataType;
        this.dbTypeCode = dbTypeCode;
        this.primaryKey = primaryKey;
        this.length = length;
        this.precision = precision;
        this.scale = scale;
        this.required = required;
        this.autoGenerated = autoGenerated;
        this.generatedValueType = generatedValueType;
        this.definition = definition;
        this.jsonDataType = jsonDataType;
    }

    /**
     * Constructs a new Column instance with simplified parameters.
     *
     * @param name              the name of the column
     * @param dataType          the data type of the column
     * @param dbTypeCode        the database-specific type code
     * @param primaryKey        whether the column is a primary key
     * @param length            the length of the column (optional)
     * @param required          whether the column is required
     * @param autoGenerated     whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition        the definition of the column (optional)
     */
    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, @Nullable Integer length, boolean required,
                  boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition) {
        this(name, dataType, dbTypeCode, primaryKey, length, null, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    /**
     * Constructs a new Column instance with additional precision parameter.
     *
     * @param name              the name of the column
     * @param dataType          the data type of the column
     * @param dbTypeCode        the database-specific type code
     * @param primaryKey        whether the column is a primary key
     * @param length            the length of the column (optional)
     * @param precision         the precision of the column (optional)
     * @param required          whether the column is required
     * @param autoGenerated     whether the column is auto-generated
     * @param generatedValueType the type of generated value (optional)
     * @param definition        the definition of the column (optional)
     */
    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, @Nullable Integer length,
                  @Nullable Integer precision, boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition) {
        this(name, dataType, dbTypeCode, primaryKey, length, precision, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    /**
     * Returns the name of the column.
     *
     * @return the name of the column
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the data type of the column.
     *
     * @return the data type of the column
     */
    public DataType getDataType() {
        return dataType;
    }

    /**
     * Returns whether the column is required.
     *
     * @return true if the column is required, false otherwise
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Indicates whether the column is automatically generated.
     *
     * @return true if the column is auto-generated, false otherwise
     */
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    /**
     * Returns the type of generated value for this column, if any.
     *
     * @return the type of generated value, or null if no generated value is defined
     */
    public GeneratedValue.Type getGeneratedValueType() {
        return generatedValueType;
    }

    /**
     * Returns the definition of the column, if available.
     *
     * @return the definition of the column, or null if not specified
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Returns the SQL type representation of this column for the given dialect.
     *
     * @param dialect the SQL dialect to generate the type for
     * @return the SQL type representation of this column
     */
    public String getSqlType(Dialect dialect) {
        if (sqlType != null) {
            return sqlType;
        }
        String typeDef;
        switch (dataType) {
            case STRING:
                typeDef = "VARCHAR(" + length + ")";
                break;
            case UUID:
                if (dialect == Dialect.ORACLE || dialect == Dialect.MYSQL) {
                    typeDef = "VARCHAR(36)";
                } else if (dialect == Dialect.SQL_SERVER) {
                    typeDef = "UNIQUEIDENTIFIER";
                } else {
                    typeDef = "UUID";
                }
                break;
            case BOOLEAN:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(3)";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // TODO: was "BIT NOT NULL";
                    typeDef = "BIT";
                } else {
                    typeDef = "BOOLEAN";
                }
                break;
            case TIMESTAMP:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "TIMESTAMP";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // sql server timestamp is an internal type, use datetime instead
                    typeDef = "DATETIME2";
                } else if (dialect == Dialect.MYSQL) {
                    // mysql doesn't allow timestamp without default
                    typeDef = "TIMESTAMP(6)";
                } else {
                    typeDef = "TIMESTAMP";
                }
                break;
            case DATE:
                typeDef = "DATE";
                break;
            case TIME:
                if (dialect == Dialect.ORACLE) {
                    // OracleDB doesn't have a TIME type, so DATE is used
                    typeDef = "DATE ";
                } else {
                    typeDef = "TIME";
                }
                break;
            case LONG:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(19)";
                } else {
                    typeDef = "BIGINT";
                }
                break;
            case CHARACTER:
                typeDef = "CHAR(" + length + ")";
                break;
            case INTEGER:
                if (precision != null) {
                    String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                    typeDef = numericName + "(" + precision + ")";
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(10)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "INTEGER";
                } else {
                    typeDef = "INT";
                }
                break;
            case BIGDECIMAL:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "FLOAT(126)";
                } else {
                    typeDef = "DECIMAL";
                }
                break;
            case FLOAT:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE || dialect == Dialect.SQL_SERVER) {
                    typeDef = " FLOAT(53)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "REAL";
                } else {
                    typeDef = "FLOAT";
                }
                break;
            case BYTE_ARRAY:
                if (dialect == Dialect.POSTGRES) {
                    typeDef = "BYTEA";
                } else if (dialect == Dialect.SQL_SERVER) {
                    typeDef = "VARBINARY(MAX)";
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "BLOB";
                } else {
                    typeDef = "BLOB";
                }
                break;
            case DOUBLE:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? NUMBER_TYPE : NUMERIC_TYPE;
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "FLOAT(23)";
                } else if (dialect == Dialect.MYSQL || dialect == Dialect.H2) {
                    typeDef = "DOUBLE";
                } else {
                    typeDef = "DOUBLE PRECISION";
                }
                break;
            case SHORT:
            case BYTE:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(5)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "SMALLINT";
                } else {
                    typeDef = "TINYINT";
                }
                break;
            case JSON:
                typeDef = getJsonSqlType(dialect);
                break;
            case STRING_ARRAY:
            case CHARACTER_ARRAY:
                // TODO: Array types are not supported for all dialects so might throw an error?
                // Think only H2 and Postgres support these type defs
                typeDef = "VARCHAR(255) ARRAY";
                break;
            case SHORT_ARRAY:
                if (dialect == Dialect.POSTGRES) {
                    typeDef = "SMALLINT ARRAY";
                } else {
                    typeDef = " TINYINT ARRAY";
                }
                break;
            case INTEGER_ARRAY:
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    typeDef = "INTEGER ARRAY";
                } else {
                    typeDef = "INT ARRAY";
                }
                break;
            case LONG_ARRAY:
                typeDef = " BIGINT ARRAY";
                break;
            case FLOAT_ARRAY:
                if (dialect == Dialect.H2 || dialect == Dialect.POSTGRES) {
                    typeDef = "REAL ARRAY";
                } else {
                    typeDef = "FLOAT ARRAY";
                }
                break;
            case DOUBLE_ARRAY:
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    typeDef = "DOUBLE PRECISION ARRAY";
                } else {
                    typeDef = "DOUBLE ARRAY";
                }
                break;
            case BOOLEAN_ARRAY:
                typeDef = "BOOLEAN ARRAY";
                break;
            default:
                if (dbTypeCode == DbTypes.ENUM) {
                    // Special case for enum
                    typeDef = "VARCHAR(255)";
                } else if (dbTypeCode == DbTypes.CLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        typeDef = "TEXT";
                    } else {
                        typeDef = "CLOB";
                    }
                    if (required) {
                        typeDef = "NOT NULL";
                    }
                } else if (dbTypeCode == DbTypes.BLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        typeDef = "BYTEA";
                    } else {
                        typeDef = "BLOB";
                    }
                } else {
                    throw new MappingException("Unable to create table column for property [" + name + "] with unknown data type: " + dataType);
                }
                break;
        }
        sqlType = typeDef;
        return sqlType;
    }

    /**
     * Returns the SQL type representation for JSON data type based on the provided dialect.
     *
     * @param dialect the SQL dialect to determine the JSON SQL type for
     * @return the SQL type representation for JSON data type
     */
    private String getJsonSqlType(Dialect dialect) {
        String result;
        switch (dialect) {
            case POSTGRES:
                result = "JSONB";
                break;
            case SQL_SERVER:
                result = "NVARCHAR(MAX)";
                break;
            case ORACLE:
                if (jsonDataType == JsonDataType.DEFAULT) {
                    result = "JSON";
                } else if (jsonDataType == JsonDataType.BLOB) {
                    result = "BLOB";
                } else {
                    result = "CLOB";
                }
                break;
            default:
                result = "JSON";
                break;
        }
        return result;
    }
}
