package io.micronaut.data.model.schema;

import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.exceptions.MappingException;
import io.micronaut.data.model.DataType;
import io.micronaut.data.model.JsonDataType;
import io.micronaut.data.model.query.builder.sql.Dialect;


@Internal
public final class Column {
    private final String name;
    private final DataType dataType;
    private final int dbTypeCode;
    private final boolean primaryKey;
    private final @Nullable Integer length;
    private final @Nullable Integer precision;
    private final @Nullable Integer scale;
    private final boolean required;
    private final boolean autoGenerated;
    private final @Nullable GeneratedValue.Type generatedValueType;
    private final @Nullable String definition;
    private final @Nullable JsonDataType jsonDataType;
    private String sqlType;

    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, Integer length, Integer precision, Integer scale,
                  boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition, JsonDataType jsonDataType) {
        this.name = name;
        this.dataType = dataType;
        this.dbTypeCode = dbTypeCode;
        this.primaryKey = primaryKey;
        this.length = length;
        this.precision = precision;
        this.scale = scale;
        this.required = required;
        this.autoGenerated = autoGenerated;
        this.generatedValueType = generatedValueType;
        this.definition = definition;
        this.jsonDataType = jsonDataType;
    }

    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, @Nullable Integer length, boolean required,
                  boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition) {
        this(name, dataType, dbTypeCode, primaryKey, length, null, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    public Column(String name, DataType dataType, int dbTypeCode, boolean primaryKey, @Nullable Integer length,
                  @Nullable Integer precision, boolean required, boolean autoGenerated, GeneratedValue.Type generatedValueType, String definition) {
        this(name, dataType, dbTypeCode, primaryKey, length, precision, null, required, autoGenerated, generatedValueType, definition,
            null);
    }

    public String getName() {
        return name;
    }

    public DataType getDataType() {
        return dataType;
    }

    public int getDbTypeCode() {
        return dbTypeCode;
    }

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public Integer getLength() {
        return length;
    }

    public Integer getPrecision() {
        return precision;
    }

    public Integer getScale() {
        return scale;
    }

    public boolean isRequired() {
        return required;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public GeneratedValue.Type getGeneratedValueType() {
        return generatedValueType;
    }

    public String getDefinition() {
        return definition;
    }

    public JsonDataType getJsonDataType() {
        return jsonDataType;
    }

    public String getSqlType(Dialect dialect) {
        if (sqlType != null) {
            return sqlType;
        }
        String typeDef;
        switch (dataType) {
            case STRING:
                typeDef = "VARCHAR(" + length + ")";
                break;
            case UUID:
                if (dialect == Dialect.ORACLE || dialect == Dialect.MYSQL) {
                    typeDef = "VARCHAR(36)";
                } else if (dialect == Dialect.SQL_SERVER) {
                    typeDef = "UNIQUEIDENTIFIER";
                } else {
                    typeDef = "UUID";
                }
                break;
            case BOOLEAN:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(3)";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // TODO: was "BIT NOT NULL";
                    typeDef = "BIT";
                } else {
                    typeDef = "BOOLEAN";
                }
                break;
            case TIMESTAMP:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "TIMESTAMP";
                } else if (dialect == Dialect.SQL_SERVER) {
                    // sql server timestamp is an internal type, use datetime instead
                    typeDef = "DATETIME2";
                } else if (dialect == Dialect.MYSQL) {
                    // mysql doesn't allow timestamp without default
                    typeDef = "TIMESTAMP(6)";
                } else {
                    typeDef = "TIMESTAMP";
                }
                break;
            case DATE:
                typeDef = "DATE";
                break;
            case TIME:
                if (dialect == Dialect.ORACLE) {
                    // OracleDB doesn't have a TIME type, so DATE is used
                    typeDef = "DATE ";
                } else {
                    typeDef = "TIME";
                }
                break;
            case LONG:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(19)";
                } else {
                    typeDef = "BIGINT";
                }
                break;
            case CHARACTER:
                typeDef = "CHAR(" + length + ")";
                break;
            case INTEGER:
                if (precision != null) {
                    String numericName = dialect == Dialect.ORACLE ? "NUMBER" : "NUMERIC";
                    typeDef = numericName + "(" + precision + ")";
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(10)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "INTEGER";
                } else {
                    typeDef = "INT";
                }
                break;
            case BIGDECIMAL:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? "NUMBER" : "NUMERIC";
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "FLOAT(126)";
                } else {
                    typeDef = "DECIMAL";
                }
                break;
            case FLOAT:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? "NUMBER" : "NUMERIC";
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE || dialect == Dialect.SQL_SERVER) {
                    typeDef = " FLOAT(53)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "REAL";
                } else {
                    typeDef = "FLOAT";
                }
                break;
            case BYTE_ARRAY:
                if (dialect == Dialect.POSTGRES) {
                    typeDef = "BYTEA";
                } else if (dialect == Dialect.SQL_SERVER) {
                    typeDef = "VARBINARY(MAX)";
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "BLOB";
                } else {
                    typeDef = "BLOB";
                }
                break;
            case DOUBLE:
                if (precision != null) {
                    if (scale != null) {
                        String numericName = dialect == Dialect.ORACLE ? "NUMBER" : "NUMERIC";
                        typeDef = numericName + "(" + precision + "," + scale + ")";
                    } else {
                        typeDef = "FLOAT(" + precision + ")";
                    }
                } else if (dialect == Dialect.ORACLE) {
                    typeDef = "FLOAT(23)";
                } else if (dialect == Dialect.MYSQL || dialect == Dialect.H2) {
                    typeDef = "DOUBLE";
                } else {
                    typeDef = "DOUBLE PRECISION";
                }
                break;
            case SHORT:
            case BYTE:
                if (dialect == Dialect.ORACLE) {
                    typeDef = "NUMBER(5)";
                } else if (dialect == Dialect.POSTGRES) {
                    typeDef = "SMALLINT";
                } else {
                    typeDef = "TINYINT";
                }
                break;
            case JSON:
                typeDef = getJsonSqlType(dialect);
                break;
            case STRING_ARRAY:
            case CHARACTER_ARRAY:
                // TODO: Array types are not supported for all dialects so might throw an error?
                // Think only H2 and Postgres support these type defs
                typeDef = "VARCHAR(255) ARRAY";
                break;
            case SHORT_ARRAY:
                if (dialect == Dialect.POSTGRES) {
                    typeDef = "SMALLINT ARRAY";
                } else {
                    typeDef = " TINYINT ARRAY";
                }
                break;
            case INTEGER_ARRAY:
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    typeDef = "INTEGER ARRAY";
                } else {
                    typeDef = "INT ARRAY";
                }
                break;
            case LONG_ARRAY:
                typeDef = " BIGINT ARRAY";
                break;
            case FLOAT_ARRAY:
                if (dialect == Dialect.H2 || dialect == Dialect.POSTGRES) {
                    typeDef = "REAL ARRAY";
                } else {
                    typeDef = "FLOAT ARRAY";
                }
                break;
            case DOUBLE_ARRAY:
                if (dialect == Dialect.POSTGRES || dialect == Dialect.H2) {
                    typeDef = "DOUBLE PRECISION ARRAY";
                } else {
                    typeDef = "DOUBLE ARRAY";
                }
                break;
            case BOOLEAN_ARRAY:
                typeDef = "BOOLEAN ARRAY";
                break;
            default:
                if (dbTypeCode == DbTypes.ENUM) {
                    // Special case for enum
                    typeDef = "VARCHAR(255)";
                } else if (dbTypeCode == DbTypes.CLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        typeDef = "TEXT";
                    } else {
                        typeDef = "CLOB";
                    }
                    if (required) {
                        typeDef = "NOT NULL";
                    }
                } else if (dbTypeCode == DbTypes.BLOB) {
                    if (dialect == Dialect.POSTGRES) {
                        typeDef = "BYTEA";
                    } else {
                        typeDef = "BLOB";
                    }
                } else {
                    throw new MappingException("Unable to create table column for property [" + name + "] with unknown data type: " + dataType);
                }
                break;
        }
        sqlType = typeDef;
        return sqlType;
    }

    private String getJsonSqlType(Dialect dialect) {
        String result;
        switch (dialect) {
            case POSTGRES:
                result = "JSONB";
                break;
            case SQL_SERVER:
                result = "NVARCHAR(MAX)";
                break;
            case ORACLE:
                if (jsonDataType == JsonDataType.DEFAULT) {
                    result = "JSON";
                } else if (jsonDataType == JsonDataType.BLOB) {
                    result = "BLOB";
                } else {
                    result = "CLOB";
                }
                break;
            default:
                result = "JSON";
                break;
        }
        return result;
    }
}
