The quickest way to get started is to create a new Micronaut application with https://micronaut.io/launch/[Micronaut Launch] and `data-r2dbc`, a database driver and a database migration framework features. This can also be done via CLI.

Clicking on one of the links in the table below will take you to https://micronaut.io/launch/[Micronaut Launch] with the appropriate options already pre-configured with your selected language and build tool:

.Creating a R2DBC application with Micronaut Launch
[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*

|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=JAVA&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=JAVA&build=MAVEN[Open,role=external]

|*Kotlin*

|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=KOTLIN&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=KOTLIN&build=MAVEN[Open,role=external]

|*Groovy*

|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=GROOVY&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-r2dbc&features=mysql&lang=GROOVY&build=MAVEN[Open,role=external]

|===

.Creating an application with the CLI
[source,bash]
----
# For Maven add: --build maven
$ mn create-app --lang java example --features data-r2dbc,flyway,mysql
----

Or via `curl`:

.Creating an application with `curl`
[source,bash]
----
# For Maven add to the URL: &build=maven
$ curl https://launch.micronaut.io/demo.zip?lang=java&features=data-r2dbc,flyway,mysql -o demo.zip && unzip demo.zip -d demo && cd demo
----

The generated application will use MySQL since we passed the `mysql` feature adding dependency on the R2DBC driver for MySQL:

dependency:dev.miku:r2dbc-mysql[scope="runtimeOnly"]

And for flyway the JDBC driver:

dependency:mysql:mysql-connector-java[scope="runtimeOnly"]

TIP: To create configurations for other drivers you can select the appropriate feature: `oracle`, `postgres`, `sqlserver`, `h2` or `mariadb`.

Now define a SQL script that creates your initial schema in `src/main/resources/db/migration`. For example:

.Example `V1__create-schema.sql`
[source,sql]
----
include::doc-examples/r2dbc-example-java/src/main/resources/db/migration/V1__create-schema.sql[]
----

You can now configure your application to connect to the database using the application configuration file under `src/main/resources`:

[configuration]
----
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mydatabase
r2dbc:
  datasources:
    default: # <3>
      url: r2dbc:mysql:///mydatabase
----

- The `enabled` setting ensures the Flyway schema migration is applied. See https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Micronaut Flyway] for more information.
- The Flyway configuration needs a JDBC datasource. `datasources.defaul.url` configures one. See <<dbcConfiguration, datasource configuration>> for more information.
- `r2dbc.datasources.default.url` is used to configure the default R2DBC `ConnectionFactory`

TIP: The R2DBC `ConnectionFactory` object can be injected anywhere in your code with dependency injection.

Now define a `@MappedEntity` that maps to the `author` table defined in the schema:

snippet::example.Author[project-base="doc-examples/r2dbc-example", source="main", indent="0"]

And a repository interface to access the database that extends from `ReactiveStreamsRepository`:

snippet::example.AuthorRepository[project-base="doc-examples/r2dbc-example", source="main", indent="0"]

<1> The ann:data.r2dbc.annotation.R2dbcRepository[] annotation can be used to specify the datasource and dialect
<2> You can override methods from the super interface to specialize the default rs:Publisher[] return type with a concrete implementation

You can now inject this interface into controllers and use it to perform R2DBC queries:

snippet::example.AuthorController[project-base="doc-examples/r2dbc-example", source="main", indent="0"]

<1> By returning a reactive type that emits many items you can stream data (either rx:Flowable[] or `Flux`)
<1> By returning a reactive type that emits a single item you return the entire response (either rx:Single[] or `Mono`)



