=== R2DBC driver

Micronaut Data R2DBC requires driver configuration using https://micronaut-projects.github.io/micronaut-r2dbc/latest/guide/#jdbc[Micronaut R2DBC]

.The following drivers are available as of this writing.
[cols=2*]
|===
|*Database*
|*Dependency*

|The H2 database
|`io.r2dbc:r2dbc-h2`

|MySQL
|`dev.miku:r2dbc-mysql`

|MariaDB
|`org.mariadb:r2dbc-mariadb`

|Postgres
|`org.postgresql:r2dbc-postgresql`

|SQL Server
|`io.r2dbc:r2dbc-mssql`

|Oracle
|`com.oracle.database.r2dbc:oracle-r2dbc`

|===

=== SQL Logging

You can enable SQL logging by enabling trace logging for the `io.micronaut.data.query` logger. For example in `logback.xml`:

.Enabling SQL Query Logging
[source,xml]
----
<logger name="io.micronaut.data.query" level="trace" />
----

=== Creating the Schema

To create the database schema it is recommended you pair Micronaut Data with a SQL migration tool such as https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Flyway] or https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html[Liquibase].

SQL migration tools provide more complete support for creating and evolving your schema across a range of databases.

NOTE: Most of the database migration tools use JDBC driver to make DB changes. Therefore it is likely that you will in addition to the R2DBC driver need to include a https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[JDBC driver module] for the schema migration to work.

If you want to quickly test out Micronaut Data R2DBC then you can set the `schema-generate` option of the data source to `create-drop` as well as the appropriate schema name:

.Using `schema-generate`
[source,yaml]
----
include::doc-examples/r2dbc-example-java/src/main/resources/application.yml[]
----

The `schema-generate` option is currently only recommended for simple applications, testing and demos and is not considered production-ready. The dialect set in configuration is the dialect that will be used to generate the schema.

=== Setting the Dialect

As seen in the YAML above you should also configure the dialect. Although queries are precomputed in the repository some cases (like pagination) still require the dialect to specified. The following table summarizes the supported dialects:

.Supported JDBC / R2DBC Dialects
[cols=2*]
|===
|*Dialect*
|*Description*

|api:data.model.query.builder.sql.Dialect#H2[]
|The H2 database (typically used for in-memory testing)

|api:data.model.query.builder.sql.Dialect#MYSQL[]
|MySQL 5.5 or above

|api:data.model.query.builder.sql.Dialect#POSTGRES[]
|Postgres 9.5 or above

|api:data.model.query.builder.sql.Dialect#SQL_SERVER[]
|SQL Server 2012 or above

|api:data.model.query.builder.sql.Dialect#ORACLE[]
|Oracle 12c or above

|===

IMPORTANT: The dialect setting in configuration does *not* replace the need to ensure the correct dialect is set at the repository. If the dialect is H2 in configuration, the repository should have `@R2dbcRepository(dialect = Dialect.H2)`. Because repositories are computed at compile time, the configuration value is not known at that time.
