package io.micronaut.data.model.query.builder.sql;

import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.model.DataType;
import io.micronaut.data.model.JsonDataType;

record ColumnDef(String name, DataType dataType, int sqlTypeCode, @Nullable Integer length, @Nullable Integer precision, @Nullable Integer scale,
                 boolean required, boolean autoGenerated, @Nullable String definition, @Nullable
                 JsonDataType jsonDataType) {

    public ColumnDef(String name, DataType dataType, int sqlTypeCode, @Nullable Integer length, boolean required, boolean autoGenerated, String definition) {
        this(name, dataType, sqlTypeCode, length, null, null, required, autoGenerated, definition, null);
    }

    public ColumnDef(String name, DataType dataType, int sqlTypeCode, @Nullable Integer length, @Nullable Integer precision, boolean required, boolean autoGenerated,
                     String definition) {
        this(name, dataType, sqlTypeCode, length, precision, null, required, autoGenerated, definition, null);
    }

    public String getTypeName(Dialect dialect) {
        // TODO: Based on dbTypeCode, dataType should return appropriate type for create command
        return null;
    }
}
