import io.micronaut.testresources.buildtools.KnownModules

plugins {
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.kapt"
    id "org.jetbrains.kotlin.plugin.allopen"
    id "io.micronaut.build.internal.data-kotlin-example"
    id "io.micronaut.test-resources"
}

application {
    mainClass = "example.ApplicationKt"
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime "netty"
    testRuntime "junit5"
    testResources {
        inferClasspath = false
        additionalModules.add(KnownModules.JDBC_POSTGRESQL)
        clientTimeout = 300
        version = libs.versions.micronaut.testresources.get()
    }
}

dependencies {
    kapt projects.micronautDataProcessor

    implementation projects.micronautDataJdbc
    implementation mnKotlin.micronaut.kotlin.runtime

    runtimeOnly mnSql.postgresql
    runtimeOnly mnSql.micronaut.jdbc.hikari
    runtimeOnly mnLogging.logback.classic

    testImplementation(libs.jupiter.api)
    testRuntimeOnly(libs.jupiter.engine)
}
