micronaut:
  multitenancy:
    tenantresolver:
      httpheader:
        enabled: true

r2dbc:
  datasources:
    default:
      db-type: mariadb
      schema-generate: CREATE_DROP
      dialect: MYSQL
