datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/freepdb1
    driverClassName: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: test
    schema-generate: CREATE_DROP
    dialect: ORACLE
