name: GraalVM Latest CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  call-graalvm-base:
    strategy:
      matrix:
        graalvm: [ 'latest' ]
        java: [ '17' ]
    uses: ./.github/workflows/graalvm-base.yml
    with:
      graalvm: ${{ matrix.graalvm }}
      java: ${{ matrix.java }}
    secrets: inherit
