The quickest way to get started is to create a new Micronaut application with https://micronaut.io/launch/[Micronaut Launch] and choose the `data-jdbc`, a database driver and a database migration framework features. This can also be done via CLI.

TIP: You can also find a great guide on building Micronaut Data JDBC applications including sample code in a variety of languages in the Micronaut Guide: https://guides.micronaut.io/latest/micronaut-data-jdbc-repository.html[Access a Database with Micronaut Data JDBC]

Clicking on one of the links in the table below will take you to https://micronaut.io/launch/[Micronaut Launch] with the appropriate options already pre-configured with your selected language and build tool:


.Creating a JDBC application with Micronaut Launch
[cols=3*]
|===
|
|*Gradle*
|*Maven*

|*Java*

|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=JAVA&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=JAVA&build=MAVEN[Open,role=external]


|*Kotlin*

|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=KOTLIN&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=KOTLIN&build=MAVEN[Open,role=external]

|*Groovy*

|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=GROOVY&build=GRADLE[Open,role=external]
|https://micronaut.io/launch?features=data-jdbc&features=flyway&features=mysql&features=jdbc-hikari&lang=GROOVY&build=MAVEN[Open,role=external]

|===

.Creating an application with the CLI
[source,bash]
----
# For Maven add: --build maven
$ mn create-app --lang java example --features data-jdbc,flyway,mysql,jdbc-hikari
----

Or via `curl`:

.Creating an application with `curl`
[source,bash]
----
# For Maven add to the URL: &build=maven
$ curl https://launch.micronaut.io/demo.zip?lang=java&features=data-jdbc,flyway,mysql,jdbc-hikari -o demo.zip && unzip demo.zip -d demo && cd demo
----

The generated application will have a compile-scoped dependency on the `micronaut-data-jdbc` module and will use MySQL since we passed the `mysql` feature adding dependency on the JDBC driver for MySQL:

dependency:io.micronaut.data:micronaut-data-jdbc[]

You should also ensure you have the JDBC driver and connection pool dependencies configured:

dependency:io.micronaut.sql:micronaut-jdbc-hikari[scope="runtime"]

The annotation processor needs to have the Micronaut Data processor dependency properly setup to enable compile-time generation and evaluation:

dependency:io.micronaut.data:micronaut-data-processor[scope="annotationProcessor"]

NOTE: For Kotlin the dependency should be in the `kapt` scope and for Groovy it should be in `compileOnly` scope.

Next up you need to configure at least one data source. The following snippet from the application configuration file is an example of configuring the default JDBC data source:

[configuration]
----
include::doc-examples/jdbc-example-java/src/main/resources/application.yml[]
----

NOTE: The `schema-generate` setting is only useful for demos and testing trivial examples, for production usage it is recommended you pair Micronaut Data with a SQL migration tool such as https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Flyway] or https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html[Liquibase].

To retrieve objects from the database you need to define a class annotated with ann:data.annotation.MappedEntity[]. Note that this is a meta annotation and in fact if you prefer you can use JPA annotations (only a subset are supported, more on that later). If you wish to use JPA annotations include the following `compileOnly` scoped dependency:

dependency:jakarta.persistence:jakarta.persistence-api[version="3.0.0", scope="compileOnly"]

To use JPA annotations in the `javax.persistence` package use:

dependency:jakarta.persistence:jakarta.persistence-api[version="2.2.3", scope="compileOnly"]

WARNING: If you want to use JPA annotations in your entities with Micronaut Data JDBC, we strongly recommend you use `jakarta.persistence` annotations.  Micronaut Data will remove support for `javax.persistence` annotations in the future.

As above since only the annotations are used the dependency can be included only for compilation and not at runtime so you don't drag along the rest of the API, reducing your JAR file size.

You can then define an `@Entity`:

snippet::example.Book[project-base="doc-examples/jdbc-example", source="main"]

Followed by an interface that extends from api:data.repository.CrudRepository[]

snippet::example.BookRepository[project-base="doc-examples/jdbc-example", source="main", tags="repository"]

<1> The interface is annotated with ann:data.jdbc.annotation.JdbcRepository[] and specifies a dialect of `H2` used to generate queries
<2> The `CrudRepository` interface take 2 generic arguments, the entity type (in this case `Book`) and the ID type (in this case `Long`)

You can now perform CRUD (Create, Read, Update, Delete) operations on the entity. The implementation of `example.BookRepository` is created at compilation time. To obtain a reference to it simply inject the bean:

snippet::example.BookRepositorySpec[project-base="doc-examples/jdbc-example", tags="inject", indent="0"]

=== Saving an Instance (Create)

To save an instance use the `save` method of the `CrudRepository` interface:

snippet::example.BookRepositorySpec[project-base="doc-examples/jdbc-example", tags="save", indent="0"]

NOTE: Unlike the JPA implementation there is no dirty checking so `save` always performs a SQL `INSERT`. For batch updates use an `update` method (see following section).

=== Retrieving an Instance (Read)

To read a book back use `findById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/jdbc-example", tags="read", indent="0"]

=== Updating an Instance (Update)

With Micronaut Data JDBC, you must manually implement an `update` method since the JDBC implementation doesn't include any dirty checking or persistence session notion. So you have to define explicit update methods for updates in your repository. For example:

snippet::example.BookRepository[project-base="doc-examples/jdbc-example", source="main" tags="update", indent="0"]

Which can then be called like so:

snippet::example.BookRepositorySpec[project-base="doc-examples/jdbc-example", tags="update", indent="0"]

=== Deleting an Instance (Delete)

To delete an instance use `deleteById`:

snippet::example.BookRepositorySpec[project-base="doc-examples/hibernate-example", tags="delete", indent="0"]

Congratulations you have implemented your first Micronaut Data JDBC repository! Read on to find out more.
