=== JDBC driver

Micronaut Data JDBC requires that an appropriate `java.sql.DataSource` bean is configured.

You can either do this manually or use the https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[Micronaut JDBC] module which provides out-of-the-box support for configuring connection pooling with either Tomcat JDBC, Hikari, Commons DBCP or Oracle UCP.

=== SQL Logging

You can enable SQL logging by enabling trace logging for the `io.micronaut.data.query` logger. For example in `logback.xml`:

.Enabling SQL Query Logging
[source,xml]
----
<logger name="io.micronaut.data.query" level="trace" />
----

=== Creating the Schema

To create the database schema it is recommended you pair Micronaut Data with a SQL migration tool such as https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Flyway] or https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html[Liquibase].

SQL migration tools provide more complete support for creating and evolving your schema across a range of databases.

If you want to quickly test out Micronaut Data then you can set the `schema-generate` option of the data source to `create-drop` as well as the appropriate schema name:

NOTE: Most of the database migration tools use JDBC driver to make DB changes. If you use R2DBC you would need to separately configure JDBC data source.

.Using `schema-generate`
[configuration]
----
include::doc-examples/jdbc-example-java/src/main/resources/application.yml[]
----

The `schema-generate` option is currently only recommended for simple applications, testing and demos and is not considered production-ready. The dialect set in configuration is the dialect that will be used to generate the schema.

==== Schema Validation

In order to validate mapped entities against current schema state set `schema-generate=validate` in the configuration.
If mapped entity does not have corresponding table in the schema or some field does not have column in the database table or
types are not matching then the application will report an error and stop.

Please note this option is currently regarded as experimental.

=== Setting the Dialect

As seen in the configuration above you should also configure the dialect. Although queries are precomputed in the repository some cases (like pagination) still require the dialect to specify. The following table summarizes the supported dialects:

.Supported JDBC / R2DBC Dialects
[cols=2*]
|===
|*Dialect*
|*Description*

|api:data.model.query.builder.sql.Dialect#H2[]
|The H2 database (typically used for in-memory testing)

|api:data.model.query.builder.sql.Dialect#MYSQL[]
|MySQL 5.5 or above

|api:data.model.query.builder.sql.Dialect#POSTGRES[]
|Postgres 9.5 or above

|api:data.model.query.builder.sql.Dialect#SQL_SERVER[]
|SQL Server 2012 or above

|api:data.model.query.builder.sql.Dialect#ORACLE[]
|Oracle 12c or above

|api:data.model.query.builder.sql.Dialect#SQLITE[]
|SQLite
| io.micronaut.sql:micronaut-sql-sqlite
|===

IMPORTANT: To use SQLite, add the dependency `io.micronaut.sql:micronaut-sql-sqlite`, which adds the https://github.com/xerial/sqlite-jdbc[SQLite JDBC Driver] and configures a custom api:data.connection.ConnectionCapabilities[] implementation.

IMPORTANT: The dialect setting in configuration does *not* replace the need to ensure the correct dialect is set at the repository. If the dialect is H2 in configuration, the repository should have `@JdbcRepository(dialect = Dialect.H2)` / `@R2dbcRepository(dialect = Dialect.H2)`. Because repositories are computed at compile time, the configuration value is not known at that time.

=== Tracing calls from Java to Oracle Database sessions

Specify the configuration property `datasources.<datasource-name>.enable-oracle-client-info=true` on a per datasource basis to link database sessions with Java thread activity. By default, this will set:

- The value of `micronaut.application.name` as the `CLIENTID`.
- The class/interface name of the repository as the `MODULE`, potentially with the package name shortened.
- The method name from the repository as the `ACTION`.
- The JVM thread name as the `CLIENT_INFO`.

This metadata appears in the `V$SESSION` view and can be used to figure out what a thread is doing inside the database. The following query is useful to see what SQL is executing:

[source,sql]
----
SELECT
    s.sid,
    s.serial#,
    s.client_identifier as app_name,
    s.client_info as thread_name,
    s.module as repository_name,
    s.action as repository_method,
    q.sql_text,
    s.event,
    s.wait_time,
    s.seconds_in_wait
FROM v$session s
LEFT JOIN v$sql q ON s.sql_id = q.sql_id
WHERE s.username = USER
----

You can control the values of `ACTION`, `MODULE`, `CLIENTID` and `CLIENT_INFO` with the ann:data.connection.annotation.ClientInfo[] annotation on repositories. Note that the ann:data.connection.annotation.ClientInfo.Attribute[] annotation can be used on either the class or the method, thus allowing customization of the  module or action individually. You should prefix the key with `OCSID.` e.g. `OCSID.ACTION` when setting client info this way. Oracle imposes a maximum length of 64 characters for these values, therefore thread, class and method names may be shortened or truncated to fit.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-data-jdbc-repository.html[Access a Database with Micronaut Data JDBC] to learn more.

