plugins {
    id "io.micronaut.build.internal.data-tck"
    id "io.micronaut.build.internal.data-tck-module"
}

dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor projects.micronautDataDocumentProcessor
    annotationProcessor mnValidation.micronaut.validation.processor

    api projects.micronautDataModel
    api mnValidation.micronaut.validation
    api projects.micronautDataTx
    api mnTest.micronaut.test.spock
    api mnTest.micronaut.test.core
    api(mnSql.jakarta.persistence.api)

    compileOnly mn.micronaut.inject.groovy
}
